locus-tag	class	description
TPANIC_RS00005	GO:0005737	cytoplasm
TPANIC_RS00005	GO:0005524	ATP binding
TPANIC_RS00005	GO:0003688	DNA replication origin binding
TPANIC_RS00005	GO:0006270	DNA replication initiation
TPANIC_RS00005	GO:0006275	regulation of DNA replication
TPANIC_RS00010	GO:0003887	DNA-directed DNA polymerase activity
TPANIC_RS00010	GO:0003677	DNA binding
TPANIC_RS00010	GO:0006260	DNA replication
TPANIC_RS00010	GO:0009360	DNA polymerase III complex
TPANIC_RS00010	GO:0005737	cytoplasm
TPANIC_RS00010	GO:0008408	3'-5' exonuclease activity
TPANIC_RS00015	GO:0005737	cytoplasm
TPANIC_RS00015	GO:0005524	ATP binding
TPANIC_RS00015	GO:0003697	single-stranded DNA binding
TPANIC_RS00015	GO:0006281	DNA repair
TPANIC_RS00015	GO:0006260	DNA replication
TPANIC_RS00015	GO:0009432	SOS response
TPANIC_RS00025	GO:0006265	DNA topological change
TPANIC_RS00025	GO:0046677	response to antibiotic
TPANIC_RS00025	GO:0006261	DNA-dependent DNA replication
TPANIC_RS00025	GO:0003918	DNA topoisomerase type II (double strand cut, ATP-hydrolyzing) activity
TPANIC_RS00025	GO:0005694	chromosome
TPANIC_RS00025	GO:0005524	ATP binding
TPANIC_RS00025	GO:0005737	cytoplasm
TPANIC_RS00025	GO:0003677	DNA binding
TPANIC_RS00055	GO:0005737	cytoplasm
TPANIC_RS00055	GO:0005524	ATP binding
TPANIC_RS00055	GO:0000287	magnesium ion binding
TPANIC_RS00055	GO:0004826	phenylalanine-tRNA ligase activity
TPANIC_RS00055	GO:0003723	RNA binding
TPANIC_RS00055	GO:0006432	phenylalanyl-tRNA aminoacylation
TPANIC_RS00060	GO:0030163	protein catabolic process
TPANIC_RS00060	GO:0005524	ATP binding
TPANIC_RS00060	GO:0004176	ATP-dependent peptidase activity
TPANIC_RS00060	GO:0004252	serine-type endopeptidase activity
TPANIC_RS00115	GO:0015293	symporter activity
TPANIC_RS00115	GO:0016021	integral component of membrane
TPANIC_RS00115	GO:0005886	plasma membrane
TPANIC_RS00125	GO:0046872	metal ion binding
TPANIC_RS00125	GO:0006508	proteolysis
TPANIC_RS00130	GO:0009288	bacterial-type flagellum
TPANIC_RS00130	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS00130	GO:0005886	plasma membrane
TPANIC_RS00130	GO:0003774	motor activity
TPANIC_RS00130	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS00130	GO:0006935	chemotaxis
TPANIC_RS00135	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS00135	GO:0016021	integral component of membrane
TPANIC_RS00135	GO:0005886	plasma membrane
TPANIC_RS00140	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS00140	GO:0005886	plasma membrane
TPANIC_RS00140	GO:0016021	integral component of membrane
TPANIC_RS00145	GO:0008360	regulation of cell shape
TPANIC_RS00145	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS00145	GO:0051301	cell division
TPANIC_RS00145	GO:0005737	cytoplasm
TPANIC_RS00145	GO:0008760	UDP-N-acetylglucosamine 1-carboxyvinyltransferase activity
TPANIC_RS00145	GO:0007049	cell cycle
TPANIC_RS00145	GO:0019277	UDP-N-acetylgalactosamine biosynthetic process
TPANIC_RS00145	GO:0071555	cell wall organization
TPANIC_RS00150	GO:0005524	ATP binding
TPANIC_RS00150	GO:0042026	protein refolding
TPANIC_RS00150	GO:0005737	cytoplasm
TPANIC_RS00150	GO:0051082	unfolded protein binding
TPANIC_RS00155	GO:0016021	integral component of membrane
TPANIC_RS00160	GO:0032259	methylation
TPANIC_RS00160	GO:0005737	cytoplasm
TPANIC_RS00160	GO:0008168	methyltransferase activity
TPANIC_RS00160	GO:0006364	rRNA processing
TPANIC_RS00170	GO:0030001	metal ion transport
TPANIC_RS00170	GO:0046872	metal ion binding
TPANIC_RS00170	GO:0042597	periplasmic space
TPANIC_RS00170	GO:0007155	cell adhesion
TPANIC_RS00175	GO:0005886	plasma membrane
TPANIC_RS00175	GO:0005524	ATP binding
TPANIC_RS00180	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS00180	GO:0005887	integral component of plasma membrane
TPANIC_RS00180	GO:0042626	ATPase-coupled transmembrane transporter activity
TPANIC_RS00185	GO:0008720	D-lactate dehydrogenase activity
TPANIC_RS00185	GO:0051287	NAD binding
TPANIC_RS00200	GO:0010247	detection of phosphate ion
TPANIC_RS00200	GO:0016021	integral component of membrane
TPANIC_RS00200	GO:0005886	plasma membrane
TPANIC_RS00200	GO:0004888	transmembrane signaling receptor activity
TPANIC_RS00200	GO:0006935	chemotaxis
TPANIC_RS00200	GO:0007165	signal transduction
TPANIC_RS00215	GO:0002098	tRNA wobble uridine modification
TPANIC_RS00215	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS00215	GO:0005737	cytoplasm
TPANIC_RS00220	GO:0019239	deaminase activity
TPANIC_RS00220	GO:0046872	metal ion binding
TPANIC_RS00220	GO:0009117	nucleotide metabolic process
TPANIC_RS00240	GO:0000270	peptidoglycan metabolic process
TPANIC_RS00240	GO:0009254	peptidoglycan turnover
TPANIC_RS00240	GO:0000920	septum digestion after cytokinesis
TPANIC_RS00240	GO:0016021	integral component of membrane
TPANIC_RS00240	GO:0005886	plasma membrane
TPANIC_RS00240	GO:0004175	endopeptidase activity
TPANIC_RS00240	GO:0046872	metal ion binding
TPANIC_RS00240	GO:0004222	metalloendopeptidase activity
TPANIC_RS00240	GO:0045227	capsule polysaccharide biosynthetic process
TPANIC_RS00240	GO:0071555	cell wall organization
TPANIC_RS00250	GO:0016149	translation release factor activity, codon specific
TPANIC_RS00250	GO:0005737	cytoplasm
TPANIC_RS00255	GO:0003676	nucleic acid binding
TPANIC_RS00255	GO:0036009	protein-glutamine N-methyltransferase activity
TPANIC_RS00255	GO:0018364	peptidyl-glutamine methylation
TPANIC_RS00255	GO:0102559	protein-(glutamine-N5) methyltransferase activity
TPANIC_RS00260	GO:0046872	metal ion binding
TPANIC_RS00260	GO:0004748	ribonucleoside-diphosphate reductase activity, thioredoxin disulfide as acceptor
TPANIC_RS00260	GO:0009263	deoxyribonucleotide biosynthetic process
TPANIC_RS00260	GO:0006260	DNA replication
TPANIC_RS00270	GO:0016021	integral component of membrane
TPANIC_RS00270	GO:0005886	plasma membrane
TPANIC_RS00270	GO:0008948	oxaloacetate decarboxylase activity
TPANIC_RS00270	GO:0015081	sodium ion transmembrane transporter activity
TPANIC_RS00270	GO:0036376	sodium ion export across plasma membrane
TPANIC_RS00275	GO:0015451	decarboxylation-driven active transmembrane transporter activity
TPANIC_RS00275	GO:0008948	oxaloacetate decarboxylase activity
TPANIC_RS00275	GO:0006814	sodium ion transport
TPANIC_RS00280	GO:0015451	decarboxylation-driven active transmembrane transporter activity
TPANIC_RS00280	GO:0006814	sodium ion transport
TPANIC_RS00280	GO:0016829	lyase activity
TPANIC_RS00280	GO:0005886	plasma membrane
TPANIC_RS00280	GO:0016021	integral component of membrane
TPANIC_RS00285	GO:1990077	primosome complex
TPANIC_RS00285	GO:0005524	ATP binding
TPANIC_RS00285	GO:0003677	DNA binding
TPANIC_RS00285	GO:0003678	DNA helicase activity
TPANIC_RS00285	GO:0006269	DNA replication, synthesis of RNA primer
TPANIC_RS00290	GO:0005840	ribosome
TPANIC_RS00290	GO:0019843	rRNA binding
TPANIC_RS00290	GO:0003735	structural constituent of ribosome
TPANIC_RS00290	GO:0006412	translation
TPANIC_RS00295	GO:0003735	structural constituent of ribosome
TPANIC_RS00295	GO:0006412	translation
TPANIC_RS00295	GO:0005840	ribosome
TPANIC_RS00295	GO:0019843	rRNA binding
TPANIC_RS00300	GO:0003697	single-stranded DNA binding
TPANIC_RS00300	GO:0006260	DNA replication
TPANIC_RS00305	GO:0019843	rRNA binding
TPANIC_RS00305	GO:0006412	translation
TPANIC_RS00305	GO:0003735	structural constituent of ribosome
TPANIC_RS00305	GO:0005840	ribosome
TPANIC_RS00330	GO:0000049	tRNA binding
TPANIC_RS00330	GO:0070475	rRNA base methylation
TPANIC_RS00330	GO:0070040	rRNA (adenine-C2-)-methyltransferase activity
TPANIC_RS00330	GO:0002935	tRNA (adenine-C2-)-methyltransferase activity
TPANIC_RS00330	GO:0046872	metal ion binding
TPANIC_RS00330	GO:0019843	rRNA binding
TPANIC_RS00330	GO:0005737	cytoplasm
TPANIC_RS00330	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS00340	GO:0016021	integral component of membrane
TPANIC_RS00340	GO:0005886	plasma membrane
TPANIC_RS00345	GO:0005737	cytoplasm
TPANIC_RS00345	GO:0005524	ATP binding
TPANIC_RS00345	GO:0016887	ATPase activity
TPANIC_RS00345	GO:0042026	protein refolding
TPANIC_RS00345	GO:0009408	response to heat
TPANIC_RS00365	GO:0055085	transmembrane transport
TPANIC_RS00365	GO:0005886	plasma membrane
TPANIC_RS00365	GO:0016021	integral component of membrane
TPANIC_RS00365	GO:0015774	polysaccharide transport
TPANIC_RS00370	GO:0016021	integral component of membrane
TPANIC_RS00370	GO:0005886	plasma membrane
TPANIC_RS00370	GO:0008643	carbohydrate transport
TPANIC_RS00370	GO:0055085	transmembrane transport
TPANIC_RS00375	GO:0005886	plasma membrane
TPANIC_RS00375	GO:0016021	integral component of membrane
TPANIC_RS00375	GO:0045227	capsule polysaccharide biosynthetic process
TPANIC_RS00380	GO:0030170	pyridoxal phosphate binding
TPANIC_RS00380	GO:0008483	transaminase activity
TPANIC_RS00380	GO:0000271	polysaccharide biosynthetic process
TPANIC_RS00395	GO:0009114	hypoxanthine catabolic process
TPANIC_RS00395	GO:0004854	xanthine dehydrogenase activity
TPANIC_RS00395	GO:0071949	FAD binding
TPANIC_RS00400	GO:0006352	DNA-templated transcription, initiation
TPANIC_RS00400	GO:2000142	regulation of DNA-templated transcription, initiation
TPANIC_RS00400	GO:0008134	transcription factor binding
TPANIC_RS00400	GO:0003677	DNA binding
TPANIC_RS00400	GO:0000160	phosphorelay signal transduction system
TPANIC_RS00400	GO:0005524	ATP binding
TPANIC_RS00415	GO:0016021	integral component of membrane
TPANIC_RS00415	GO:0005886	plasma membrane
TPANIC_RS00415	GO:0005351	carbohydrate:proton symporter activity
TPANIC_RS00415	GO:0022877	protein-N(PI)-phosphohistidine-fructose phosphotransferase system transporter activity
TPANIC_RS00415	GO:0090563	protein-phosphocysteine-sugar phosphotransferase activity
TPANIC_RS00415	GO:0009401	phosphoenolpyruvate-dependent sugar phosphotransferase system
TPANIC_RS00420	GO:0035438	cyclic-di-GMP binding
TPANIC_RS00435	GO:0010628	positive regulation of gene expression
TPANIC_RS00435	GO:0045893	positive regulation of transcription, DNA-templated
TPANIC_RS00435	GO:0000976	transcription regulatory region sequence-specific DNA binding
TPANIC_RS00435	GO:0043565	sequence-specific DNA binding
TPANIC_RS00435	GO:0042803	protein homodimerization activity
TPANIC_RS00435	GO:0003677	DNA binding
TPANIC_RS00435	GO:0030552	cAMP binding
TPANIC_RS00435	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS00440	GO:0005737	cytoplasm
TPANIC_RS00440	GO:0071555	cell wall organization
TPANIC_RS00440	GO:0008360	regulation of cell shape
TPANIC_RS00440	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS00440	GO:0051301	cell division
TPANIC_RS00440	GO:0007049	cell cycle
TPANIC_RS00440	GO:0008762	UDP-N-acetylmuramate dehydrogenase activity
TPANIC_RS00440	GO:0071949	FAD binding
TPANIC_RS00445	GO:0005524	ATP binding
TPANIC_RS00445	GO:0005737	cytoplasm
TPANIC_RS00445	GO:0008270	zinc ion binding
TPANIC_RS00445	GO:0006423	cysteinyl-tRNA aminoacylation
TPANIC_RS00445	GO:0004817	cysteine-tRNA ligase activity
TPANIC_RS00450	GO:0005737	cytoplasm
TPANIC_RS00450	GO:0003677	DNA binding
TPANIC_RS00450	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS00450	GO:0003899	DNA-directed 5'-3' RNA polymerase activity
TPANIC_RS00450	GO:0001123	transcription initiation from bacterial-type RNA polymerase promoter
TPANIC_RS00450	GO:0006355	regulation of transcription, DNA-templated
TPANIC_RS00450	GO:0016987	sigma factor activity
TPANIC_RS00450	GO:2000147	positive regulation of cell motility
TPANIC_RS00455	GO:0016021	integral component of membrane
TPANIC_RS00460	GO:0006085	acetyl-CoA biosynthetic process
TPANIC_RS00460	GO:0008959	phosphate acetyltransferase activity
TPANIC_RS00460	GO:0005737	cytoplasm
TPANIC_RS00475	GO:0043022	ribosome binding
TPANIC_RS00475	GO:0019843	rRNA binding
TPANIC_RS00475	GO:0005737	cytoplasm
TPANIC_RS00475	GO:0003743	translation initiation factor activity
TPANIC_RS00480	GO:0005524	ATP binding
TPANIC_RS00480	GO:0031072	heat shock protein binding
TPANIC_RS00480	GO:0051082	unfolded protein binding
TPANIC_RS00480	GO:0006260	DNA replication
TPANIC_RS00480	GO:0006457	protein folding
TPANIC_RS00480	GO:0009408	response to heat
TPANIC_RS00480	GO:0008270	zinc ion binding
TPANIC_RS00480	GO:0005737	cytoplasm
TPANIC_RS00485	GO:0005737	cytoplasm
TPANIC_RS00485	GO:0005524	ATP binding
TPANIC_RS00485	GO:0033862	UMP kinase activity
TPANIC_RS00485	GO:0044210	'de novo' CTP biosynthetic process
TPANIC_RS00490	GO:0005886	plasma membrane
TPANIC_RS00490	GO:0016209	antioxidant activity
TPANIC_RS00490	GO:0015036	disulfide oxidoreductase activity
TPANIC_RS00490	GO:0017004	cytochrome complex assembly
TPANIC_RS00490	GO:0016021	integral component of membrane
TPANIC_RS00495	GO:0005886	plasma membrane
TPANIC_RS00495	GO:0017004	cytochrome complex assembly
TPANIC_RS00495	GO:0055114	oxidation-reduction process
TPANIC_RS00495	GO:0016021	integral component of membrane
TPANIC_RS00500	GO:0005737	cytoplasm
TPANIC_RS00500	GO:0005524	ATP binding
TPANIC_RS00500	GO:0003678	DNA helicase activity
TPANIC_RS00500	GO:0006268	DNA unwinding involved in DNA replication
TPANIC_RS00500	GO:0003677	DNA binding
TPANIC_RS00505	GO:0003677	DNA binding
TPANIC_RS00505	GO:0009432	SOS response
TPANIC_RS00505	GO:0006260	DNA replication
TPANIC_RS00505	GO:0006281	DNA repair
TPANIC_RS00505	GO:0006310	DNA recombination
TPANIC_RS00505	GO:0005524	ATP binding
TPANIC_RS00505	GO:0043138	3'-5' DNA helicase activity
TPANIC_RS00510	GO:0009166	nucleotide catabolic process
TPANIC_RS00510	GO:0000166	nucleotide binding
TPANIC_RS00510	GO:0046872	metal ion binding
TPANIC_RS00510	GO:0005886	plasma membrane
TPANIC_RS00510	GO:0008253	5'-nucleotidase activity
TPANIC_RS00515	GO:0003887	DNA-directed DNA polymerase activity
TPANIC_RS00515	GO:0006261	DNA-dependent DNA replication
TPANIC_RS00515	GO:0008408	3'-5' exonuclease activity
TPANIC_RS00515	GO:0003677	DNA binding
TPANIC_RS00515	GO:0006281	DNA repair
TPANIC_RS00520	GO:0005886	plasma membrane
TPANIC_RS00520	GO:0044667	(R)-carnitine:4-(trimethylammonio)butanoate antiporter activity
TPANIC_RS00520	GO:1900751	4-(trimethylammonio)butanoate transport
TPANIC_RS00520	GO:0009437	carnitine metabolic process
TPANIC_RS00520	GO:0016021	integral component of membrane
TPANIC_RS00530	GO:0005737	cytoplasm
TPANIC_RS00530	GO:0003872	6-phosphofructokinase activity
TPANIC_RS00530	GO:0005524	ATP binding
TPANIC_RS00530	GO:0046872	metal ion binding
TPANIC_RS00530	GO:0006002	fructose 6-phosphate metabolic process
TPANIC_RS00535	GO:0008173	RNA methyltransferase activity
TPANIC_RS00535	GO:0006396	RNA processing
TPANIC_RS00535	GO:0003723	RNA binding
TPANIC_RS00560	GO:0006352	DNA-templated transcription, initiation
TPANIC_RS00560	GO:0016987	sigma factor activity
TPANIC_RS00560	GO:0003899	DNA-directed 5'-3' RNA polymerase activity
TPANIC_RS00560	GO:0001216	DNA-binding transcription activator activity
TPANIC_RS00560	GO:0003677	DNA binding
TPANIC_RS00565	GO:0004197	cysteine-type endopeptidase activity
TPANIC_RS00565	GO:0004177	aminopeptidase activity
TPANIC_RS00570	GO:0016021	integral component of membrane
TPANIC_RS00575	GO:0016021	integral component of membrane
TPANIC_RS00575	GO:0052547	regulation of peptidase activity
TPANIC_RS00580	GO:0008972	phosphomethylpyrimidine kinase activity
TPANIC_RS00580	GO:0009228	thiamine biosynthetic process
TPANIC_RS00580	GO:0008478	pyridoxal kinase activity
TPANIC_RS00580	GO:0046872	metal ion binding
TPANIC_RS00580	GO:0005524	ATP binding
TPANIC_RS00585	GO:0004386	helicase activity
TPANIC_RS00585	GO:0006289	nucleotide-excision repair
TPANIC_RS00585	GO:0009432	SOS response
TPANIC_RS00585	GO:0009381	excinuclease ABC activity
TPANIC_RS00585	GO:0003677	DNA binding
TPANIC_RS00585	GO:0005524	ATP binding
TPANIC_RS00585	GO:0005737	cytoplasm
TPANIC_RS00585	GO:0009380	excinuclease repair complex
TPANIC_RS00600	GO:0016021	integral component of membrane
TPANIC_RS00600	GO:0048473	D-methionine transport
TPANIC_RS00600	GO:0006865	amino acid transport
TPANIC_RS00600	GO:0042626	ATPase-coupled transmembrane transporter activity
TPANIC_RS00600	GO:0005886	plasma membrane
TPANIC_RS00605	GO:0015821	methionine transport
TPANIC_RS00605	GO:0015424	ATPase-coupled amino acid transmembrane transporter activity
TPANIC_RS00605	GO:0016887	ATPase activity
TPANIC_RS00605	GO:0005524	ATP binding
TPANIC_RS00605	GO:0005886	plasma membrane
TPANIC_RS00610	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS00610	GO:0016853	isomerase activity
TPANIC_RS00610	GO:0046872	metal ion binding
TPANIC_RS00615	GO:0005525	GTP binding
TPANIC_RS00615	GO:0030145	manganese ion binding
TPANIC_RS00615	GO:0004613	phosphoenolpyruvate carboxykinase (GTP) activity
TPANIC_RS00615	GO:0006094	gluconeogenesis
TPANIC_RS00615	GO:0005737	cytoplasm
TPANIC_RS00625	GO:0005524	ATP binding
TPANIC_RS00625	GO:0016887	ATPase activity
TPANIC_RS00625	GO:0005525	GTP binding
TPANIC_RS00625	GO:0046872	metal ion binding
TPANIC_RS00625	GO:0043023	ribosomal large subunit binding
TPANIC_RS00625	GO:0043022	ribosome binding
TPANIC_RS00625	GO:0005737	cytoplasm
TPANIC_RS00630	GO:0006284	base-excision repair
TPANIC_RS00630	GO:0046872	metal ion binding
TPANIC_RS00630	GO:0008853	exodeoxyribonuclease III activity
TPANIC_RS00630	GO:0004519	endonuclease activity
TPANIC_RS00630	GO:0008311	double-stranded DNA 3'-5' exodeoxyribonuclease activity
TPANIC_RS00630	GO:0003906	DNA-(apurinic or apyrimidinic site) endonuclease activity
TPANIC_RS00630	GO:0003677	DNA binding
TPANIC_RS00630	GO:0005737	cytoplasm
TPANIC_RS00630	GO:0004528	phosphodiesterase I activity
TPANIC_RS00635	GO:0005886	plasma membrane
TPANIC_RS00635	GO:0016021	integral component of membrane
TPANIC_RS00675	GO:0005886	plasma membrane
TPANIC_RS00680	GO:0005886	plasma membrane
TPANIC_RS00695	GO:0005886	plasma membrane
TPANIC_RS00700	GO:0005886	plasma membrane
TPANIC_RS00700	GO:0016021	integral component of membrane
TPANIC_RS00705	GO:0006813	potassium ion transport
TPANIC_RS00705	GO:0005886	plasma membrane
TPANIC_RS00705	GO:0008324	cation transmembrane transporter activity
TPANIC_RS00710	GO:0015379	potassium:chloride symporter activity
TPANIC_RS00710	GO:0005886	plasma membrane
TPANIC_RS00710	GO:0016021	integral component of membrane
TPANIC_RS00715	GO:0003908	methylated-DNA-[protein]-cysteine S-methyltransferase activity
TPANIC_RS00715	GO:0005737	cytoplasm
TPANIC_RS00715	GO:0006307	DNA dealkylation involved in DNA repair
TPANIC_RS00715	GO:0032259	methylation
TPANIC_RS00720	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS00720	GO:0016887	ATPase activity
TPANIC_RS00720	GO:0015408	ATPase-coupled ferric iron transmembrane transporter activity
TPANIC_RS00720	GO:0033212	iron import into cell
TPANIC_RS00720	GO:0005524	ATP binding
TPANIC_RS00725	GO:0016021	integral component of membrane
TPANIC_RS00725	GO:0005886	plasma membrane
TPANIC_RS00725	GO:0022857	transmembrane transporter activity
TPANIC_RS00725	GO:0015888	thiamine transport
TPANIC_RS00730	GO:0015888	thiamine transport
TPANIC_RS00730	GO:0030975	thiamine binding
TPANIC_RS00730	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS00735	GO:0004467	long-chain fatty acid-CoA ligase activity
TPANIC_RS00735	GO:0102391	decanoate-CoA ligase activity
TPANIC_RS00735	GO:0016405	CoA-ligase activity
TPANIC_RS00735	GO:0005524	ATP binding
TPANIC_RS00755	GO:0005975	carbohydrate metabolic process
TPANIC_RS00755	GO:0103025	alpha-amylase activity (releasing maltohexaose)
TPANIC_RS00755	GO:0030246	carbohydrate binding
TPANIC_RS00755	GO:0004556	alpha-amylase activity
TPANIC_RS00755	GO:0005737	cytoplasm
TPANIC_RS00760	GO:0016021	integral component of membrane
TPANIC_RS00760	GO:0005886	plasma membrane
TPANIC_RS00765	GO:0005886	plasma membrane
TPANIC_RS00765	GO:0016021	integral component of membrane
TPANIC_RS00785	GO:0016021	integral component of membrane
TPANIC_RS00785	GO:0005886	plasma membrane
TPANIC_RS00820	GO:0005737	cytoplasm
TPANIC_RS00820	GO:0002161	aminoacyl-tRNA editing activity
TPANIC_RS00820	GO:0005524	ATP binding
TPANIC_RS00820	GO:0004827	proline-tRNA ligase activity
TPANIC_RS00820	GO:0006433	prolyl-tRNA aminoacylation
TPANIC_RS00825	GO:0006310	DNA recombination
TPANIC_RS00825	GO:0009378	four-way junction helicase activity
TPANIC_RS00825	GO:0003677	DNA binding
TPANIC_RS00825	GO:0005524	ATP binding
TPANIC_RS00825	GO:0009432	SOS response
TPANIC_RS00825	GO:0006281	DNA repair
TPANIC_RS00830	GO:0006829	zinc ion transport
TPANIC_RS00830	GO:0007155	cell adhesion
TPANIC_RS00830	GO:0046872	metal ion binding
TPANIC_RS00830	GO:0042597	periplasmic space
TPANIC_RS00835	GO:0006829	zinc ion transport
TPANIC_RS00835	GO:0016887	ATPase activity
TPANIC_RS00835	GO:0005524	ATP binding
TPANIC_RS00840	GO:0005887	integral component of plasma membrane
TPANIC_RS00840	GO:0042626	ATPase-coupled transmembrane transporter activity
TPANIC_RS00840	GO:0006829	zinc ion transport
TPANIC_RS00840	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS00845	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS00845	GO:0042626	ATPase-coupled transmembrane transporter activity
TPANIC_RS00845	GO:0006829	zinc ion transport
TPANIC_RS00845	GO:0005887	integral component of plasma membrane
TPANIC_RS00850	GO:0046914	transition metal ion binding
TPANIC_RS00850	GO:0046983	protein dimerization activity
TPANIC_RS00850	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS00850	GO:0005737	cytoplasm
TPANIC_RS00850	GO:0003677	DNA binding
TPANIC_RS00855	GO:0006096	glycolytic process
TPANIC_RS00855	GO:0006094	gluconeogenesis
TPANIC_RS00855	GO:0046538	2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity
TPANIC_RS00865	GO:0009164	nucleoside catabolic process
TPANIC_RS00865	GO:0019509	L-methionine salvage from methylthioadenosine
TPANIC_RS00865	GO:0008930	methylthioadenosine nucleosidase activity
TPANIC_RS00865	GO:0008782	adenosylhomocysteine nucleosidase activity
TPANIC_RS00870	GO:0010181	FMN binding
TPANIC_RS00870	GO:0005886	plasma membrane
TPANIC_RS00875	GO:0016021	integral component of membrane
TPANIC_RS00875	GO:0005886	plasma membrane
TPANIC_RS00900	GO:0005886	plasma membrane
TPANIC_RS00900	GO:0016021	integral component of membrane
TPANIC_RS00905	GO:0008033	tRNA processing
TPANIC_RS00905	GO:0061710	L-threonylcarbamoyladenylate synthase
TPANIC_RS00905	GO:0003725	double-stranded RNA binding
TPANIC_RS00905	GO:0005524	ATP binding
TPANIC_RS00905	GO:0005737	cytoplasm
TPANIC_RS00915	GO:0070929	trans-translation
TPANIC_RS00915	GO:0003723	RNA binding
TPANIC_RS00915	GO:0005737	cytoplasm
TPANIC_RS00920	GO:0016021	integral component of membrane
TPANIC_RS00920	GO:0004252	serine-type endopeptidase activity
TPANIC_RS00920	GO:0005886	plasma membrane
TPANIC_RS00925	GO:0005737	cytoplasm
TPANIC_RS00925	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS00925	GO:0004109	coproporphyrinogen oxidase activity
TPANIC_RS00925	GO:0046872	metal ion binding
TPANIC_RS00925	GO:0006779	porphyrin-containing compound biosynthetic process
TPANIC_RS00925	GO:0005886	plasma membrane
TPANIC_RS00930	GO:0005737	cytoplasm
TPANIC_RS00930	GO:0005525	GTP binding
TPANIC_RS00930	GO:0003924	GTPase activity
TPANIC_RS00930	GO:0003746	translation elongation factor activity
TPANIC_RS00935	GO:0005840	ribosome
TPANIC_RS00935	GO:0000049	tRNA binding
TPANIC_RS00935	GO:0006412	translation
TPANIC_RS00935	GO:0003735	structural constituent of ribosome
TPANIC_RS00940	GO:0006412	translation
TPANIC_RS00940	GO:0005840	ribosome
TPANIC_RS00940	GO:0019843	rRNA binding
TPANIC_RS00940	GO:0003735	structural constituent of ribosome
TPANIC_RS00945	GO:0006412	translation
TPANIC_RS00945	GO:0003735	structural constituent of ribosome
TPANIC_RS00945	GO:0019843	rRNA binding
TPANIC_RS00945	GO:0005840	ribosome
TPANIC_RS00950	GO:0005840	ribosome
TPANIC_RS00950	GO:0006412	translation
TPANIC_RS00950	GO:0003735	structural constituent of ribosome
TPANIC_RS00950	GO:0019843	rRNA binding
TPANIC_RS00955	GO:0006412	translation
TPANIC_RS00955	GO:0003735	structural constituent of ribosome
TPANIC_RS00955	GO:0019843	rRNA binding
TPANIC_RS00955	GO:0015934	large ribosomal subunit
TPANIC_RS00955	GO:0016740	transferase activity
TPANIC_RS00960	GO:0006412	translation
TPANIC_RS00960	GO:0003735	structural constituent of ribosome
TPANIC_RS00960	GO:0019843	rRNA binding
TPANIC_RS00960	GO:0015935	small ribosomal subunit
TPANIC_RS00965	GO:0006412	translation
TPANIC_RS00965	GO:0003735	structural constituent of ribosome
TPANIC_RS00965	GO:0019843	rRNA binding
TPANIC_RS00965	GO:0015934	large ribosomal subunit
TPANIC_RS00970	GO:0006412	translation
TPANIC_RS00970	GO:0019843	rRNA binding
TPANIC_RS00970	GO:0003729	mRNA binding
TPANIC_RS00970	GO:0005840	ribosome
TPANIC_RS00970	GO:0003735	structural constituent of ribosome
TPANIC_RS00975	GO:0003735	structural constituent of ribosome
TPANIC_RS00975	GO:0005840	ribosome
TPANIC_RS00975	GO:0006412	translation
TPANIC_RS00975	GO:0000049	tRNA binding
TPANIC_RS00975	GO:0019843	rRNA binding
TPANIC_RS00980	GO:0006412	translation
TPANIC_RS00980	GO:0003735	structural constituent of ribosome
TPANIC_RS00980	GO:0005840	ribosome
TPANIC_RS00985	GO:0006412	translation
TPANIC_RS00985	GO:0003735	structural constituent of ribosome
TPANIC_RS00985	GO:0019843	rRNA binding
TPANIC_RS00985	GO:0005840	ribosome
TPANIC_RS00990	GO:0015934	large ribosomal subunit
TPANIC_RS00990	GO:0003735	structural constituent of ribosome
TPANIC_RS00990	GO:0006412	translation
TPANIC_RS00990	GO:0019843	rRNA binding
TPANIC_RS00995	GO:0005840	ribosome
TPANIC_RS00995	GO:0019843	rRNA binding
TPANIC_RS00995	GO:0003735	structural constituent of ribosome
TPANIC_RS00995	GO:0006412	translation
TPANIC_RS01000	GO:0019843	rRNA binding
TPANIC_RS01000	GO:0003735	structural constituent of ribosome
TPANIC_RS01000	GO:0000049	tRNA binding
TPANIC_RS01000	GO:0006412	translation
TPANIC_RS01000	GO:0005840	ribosome
TPANIC_RS01005	GO:0019843	rRNA binding
TPANIC_RS01005	GO:0003735	structural constituent of ribosome
TPANIC_RS01005	GO:0006412	translation
TPANIC_RS01005	GO:0005840	ribosome
TPANIC_RS01010	GO:0005840	ribosome
TPANIC_RS01010	GO:0003735	structural constituent of ribosome
TPANIC_RS01010	GO:0006412	translation
TPANIC_RS01010	GO:0019843	rRNA binding
TPANIC_RS01015	GO:0005840	ribosome
TPANIC_RS01015	GO:0019843	rRNA binding
TPANIC_RS01015	GO:0006412	translation
TPANIC_RS01015	GO:0003735	structural constituent of ribosome
TPANIC_RS01020	GO:0019843	rRNA binding
TPANIC_RS01020	GO:0015935	small ribosomal subunit
TPANIC_RS01020	GO:0006412	translation
TPANIC_RS01020	GO:0003735	structural constituent of ribosome
TPANIC_RS01025	GO:0015934	large ribosomal subunit
TPANIC_RS01025	GO:0003735	structural constituent of ribosome
TPANIC_RS01025	GO:0006412	translation
TPANIC_RS01030	GO:0015934	large ribosomal subunit
TPANIC_RS01030	GO:0003735	structural constituent of ribosome
TPANIC_RS01030	GO:0006412	translation
TPANIC_RS01030	GO:0019843	rRNA binding
TPANIC_RS01035	GO:0043952	protein transport by the Sec complex
TPANIC_RS01035	GO:0006605	protein targeting
TPANIC_RS01035	GO:0065002	intracellular protein transmembrane transport
TPANIC_RS01035	GO:0005886	plasma membrane
TPANIC_RS01035	GO:0016021	integral component of membrane
TPANIC_RS01040	GO:0006412	translation
TPANIC_RS01040	GO:0003735	structural constituent of ribosome
TPANIC_RS01040	GO:0005840	ribosome
TPANIC_RS01045	GO:0000049	tRNA binding
TPANIC_RS01045	GO:0019843	rRNA binding
TPANIC_RS01045	GO:0005840	ribosome
TPANIC_RS01045	GO:0003735	structural constituent of ribosome
TPANIC_RS01045	GO:0006412	translation
TPANIC_RS01050	GO:0005840	ribosome
TPANIC_RS01050	GO:0019843	rRNA binding
TPANIC_RS01050	GO:0006412	translation
TPANIC_RS01050	GO:0003735	structural constituent of ribosome
TPANIC_RS01055	GO:0006351	transcription, DNA-templated
TPANIC_RS01055	GO:0046983	protein dimerization activity
TPANIC_RS01055	GO:0003899	DNA-directed 5'-3' RNA polymerase activity
TPANIC_RS01055	GO:0003677	DNA binding
TPANIC_RS01060	GO:0006412	translation
TPANIC_RS01060	GO:0003735	structural constituent of ribosome
TPANIC_RS01060	GO:0005840	ribosome
TPANIC_RS01070	GO:0000774	adenyl-nucleotide exchange factor activity
TPANIC_RS01070	GO:0006457	protein folding
TPANIC_RS01070	GO:0005737	cytoplasm
TPANIC_RS01070	GO:0051087	chaperone binding
TPANIC_RS01070	GO:0042803	protein homodimerization activity
TPANIC_RS01075	GO:0005524	ATP binding
TPANIC_RS01075	GO:0006457	protein folding
TPANIC_RS01075	GO:0051082	unfolded protein binding
TPANIC_RS01080	GO:0009408	response to heat
TPANIC_RS01080	GO:0005737	cytoplasm
TPANIC_RS01080	GO:0005524	ATP binding
TPANIC_RS01080	GO:0031072	heat shock protein binding
TPANIC_RS01080	GO:0051082	unfolded protein binding
TPANIC_RS01080	GO:0008270	zinc ion binding
TPANIC_RS01080	GO:0006260	DNA replication
TPANIC_RS01080	GO:0006457	protein folding
TPANIC_RS01095	GO:0043856	anti-sigma factor antagonist activity
TPANIC_RS01105	GO:0016021	integral component of membrane
TPANIC_RS01140	GO:0016021	integral component of membrane
TPANIC_RS01140	GO:0005886	plasma membrane
TPANIC_RS01145	GO:0016887	ATPase activity
TPANIC_RS01145	GO:0005524	ATP binding
TPANIC_RS01145	GO:0009236	cobalamin biosynthetic process
TPANIC_RS01145	GO:0006824	cobalt ion transport
TPANIC_RS01145	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS01150	GO:0016021	integral component of membrane
TPANIC_RS01150	GO:0005886	plasma membrane
TPANIC_RS01150	GO:0015225	biotin transmembrane transporter activity
TPANIC_RS01155	GO:0006281	DNA repair
TPANIC_RS01155	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS01155	GO:0046872	metal ion binding
TPANIC_RS01155	GO:0004844	uracil DNA N-glycosylase activity
TPANIC_RS01160	GO:1990077	primosome complex
TPANIC_RS01160	GO:0005524	ATP binding
TPANIC_RS01160	GO:0003677	DNA binding
TPANIC_RS01160	GO:0006268	DNA unwinding involved in DNA replication
TPANIC_RS01160	GO:0006269	DNA replication, synthesis of RNA primer
TPANIC_RS01160	GO:0008270	zinc ion binding
TPANIC_RS01160	GO:0003678	DNA helicase activity
TPANIC_RS01165	GO:0001522	pseudouridine synthesis
TPANIC_RS01165	GO:0120159	rRNA pseudouridine synthase activity
TPANIC_RS01165	GO:0003723	RNA binding
TPANIC_RS01165	GO:0006364	rRNA processing
TPANIC_RS01180	GO:0006412	translation
TPANIC_RS01180	GO:0003735	structural constituent of ribosome
TPANIC_RS01180	GO:0005840	ribosome
TPANIC_RS01190	GO:0005886	plasma membrane
TPANIC_RS01190	GO:0065002	intracellular protein transmembrane transport
TPANIC_RS01190	GO:0009306	protein secretion
TPANIC_RS01190	GO:0006605	protein targeting
TPANIC_RS01190	GO:0043952	protein transport by the Sec complex
TPANIC_RS01190	GO:0016021	integral component of membrane
TPANIC_RS01190	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
TPANIC_RS01195	GO:0031564	transcription antitermination
TPANIC_RS01195	GO:0006354	DNA-templated transcription, elongation
TPANIC_RS01195	GO:0032784	regulation of DNA-templated transcription, elongation
TPANIC_RS01195	GO:0006353	DNA-templated transcription, termination
TPANIC_RS01200	GO:0006412	translation
TPANIC_RS01200	GO:0003735	structural constituent of ribosome
TPANIC_RS01200	GO:0070180	large ribosomal subunit rRNA binding
TPANIC_RS01200	GO:0005840	ribosome
TPANIC_RS01205	GO:0006417	regulation of translation
TPANIC_RS01205	GO:0000049	tRNA binding
TPANIC_RS01205	GO:0019843	rRNA binding
TPANIC_RS01205	GO:0015934	large ribosomal subunit
TPANIC_RS01205	GO:0003735	structural constituent of ribosome
TPANIC_RS01205	GO:0006412	translation
TPANIC_RS01210	GO:0006412	translation
TPANIC_RS01210	GO:0042254	ribosome biogenesis
TPANIC_RS01210	GO:0003735	structural constituent of ribosome
TPANIC_RS01210	GO:0070180	large ribosomal subunit rRNA binding
TPANIC_RS01210	GO:0015934	large ribosomal subunit
TPANIC_RS01215	GO:0005840	ribosome
TPANIC_RS01215	GO:0006412	translation
TPANIC_RS01215	GO:0003735	structural constituent of ribosome
TPANIC_RS01220	GO:0003677	DNA binding
TPANIC_RS01220	GO:0006351	transcription, DNA-templated
TPANIC_RS01220	GO:0003899	DNA-directed 5'-3' RNA polymerase activity
TPANIC_RS01220	GO:0032549	ribonucleoside binding
TPANIC_RS01225	GO:0006351	transcription, DNA-templated
TPANIC_RS01225	GO:0003677	DNA binding
TPANIC_RS01225	GO:0003899	DNA-directed 5'-3' RNA polymerase activity
TPANIC_RS01225	GO:0000287	magnesium ion binding
TPANIC_RS01225	GO:0008270	zinc ion binding
TPANIC_RS01230	GO:0003735	structural constituent of ribosome
TPANIC_RS01230	GO:0000049	tRNA binding
TPANIC_RS01230	GO:0006412	translation
TPANIC_RS01230	GO:0015935	small ribosomal subunit
TPANIC_RS01230	GO:0019843	rRNA binding
TPANIC_RS01235	GO:0019843	rRNA binding
TPANIC_RS01235	GO:0003735	structural constituent of ribosome
TPANIC_RS01235	GO:0000049	tRNA binding
TPANIC_RS01235	GO:0006412	translation
TPANIC_RS01235	GO:0015935	small ribosomal subunit
TPANIC_RS01250	GO:0009253	peptidoglycan catabolic process
TPANIC_RS01250	GO:0008745	N-acetylmuramoyl-L-alanine amidase activity
TPANIC_RS01255	GO:0005886	plasma membrane
TPANIC_RS01260	GO:0055040	periplasmic flagellum
TPANIC_RS01260	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS01260	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS01265	GO:0003677	DNA binding
TPANIC_RS01265	GO:0030261	chromosome condensation
TPANIC_RS01270	GO:0016410	N-acyltransferase activity
TPANIC_RS01270	GO:0042158	lipoprotein biosynthetic process
TPANIC_RS01270	GO:0016021	integral component of membrane
TPANIC_RS01270	GO:0005886	plasma membrane
TPANIC_RS01280	GO:0005524	ATP binding
TPANIC_RS01280	GO:0003723	RNA binding
TPANIC_RS01280	GO:0008186	RNA-dependent ATPase activity
TPANIC_RS01280	GO:0006353	DNA-templated transcription, termination
TPANIC_RS01280	GO:0004386	helicase activity
TPANIC_RS01285	GO:0005840	ribosome
TPANIC_RS01285	GO:0046872	metal ion binding
TPANIC_RS01285	GO:0003735	structural constituent of ribosome
TPANIC_RS01285	GO:0006412	translation
TPANIC_RS01285	GO:0019843	rRNA binding
TPANIC_RS01290	GO:0006655	phosphatidylglycerol biosynthetic process
TPANIC_RS01290	GO:0008444	CDP-diacylglycerol-glycerol-3-phosphate 3-phosphatidyltransferase activity
TPANIC_RS01290	GO:0005886	plasma membrane
TPANIC_RS01290	GO:0016021	integral component of membrane
TPANIC_RS01295	GO:0006071	glycerol metabolic process
TPANIC_RS01295	GO:0005886	plasma membrane
TPANIC_RS01295	GO:0008889	glycerophosphodiester phosphodiesterase activity
TPANIC_RS01295	GO:0006629	lipid metabolic process
TPANIC_RS01310	GO:0016021	integral component of membrane
TPANIC_RS01320	GO:0003677	DNA binding
TPANIC_RS01320	GO:0030552	cAMP binding
TPANIC_RS01320	GO:0045893	positive regulation of transcription, DNA-templated
TPANIC_RS01320	GO:0000976	transcription regulatory region sequence-specific DNA binding
TPANIC_RS01320	GO:0010628	positive regulation of gene expression
TPANIC_RS01320	GO:0042803	protein homodimerization activity
TPANIC_RS01320	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS01320	GO:0043565	sequence-specific DNA binding
TPANIC_RS01330	GO:0046386	deoxyribose phosphate catabolic process
TPANIC_RS01330	GO:0009264	deoxyribonucleotide catabolic process
TPANIC_RS01330	GO:0004139	deoxyribose-phosphate aldolase activity
TPANIC_RS01330	GO:0005737	cytoplasm
TPANIC_RS01330	GO:0016052	carbohydrate catabolic process
TPANIC_RS01335	GO:0015188	L-isoleucine transmembrane transporter activity
TPANIC_RS01335	GO:0005886	plasma membrane
TPANIC_RS01335	GO:0015190	L-leucine transmembrane transporter activity
TPANIC_RS01335	GO:0005304	L-valine transmembrane transporter activity
TPANIC_RS01335	GO:0015818	isoleucine transport
TPANIC_RS01335	GO:0015820	leucine transport
TPANIC_RS01335	GO:0015829	valine transport
TPANIC_RS01335	GO:0016021	integral component of membrane
TPANIC_RS01370	GO:0006400	tRNA modification
TPANIC_RS01370	GO:0061712	tRNA (N(6)-L-threonylcarbamoyladenosine(37)-C(2))-methylthiotransferase
TPANIC_RS01370	GO:0046872	metal ion binding
TPANIC_RS01370	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS01370	GO:0005737	cytoplasm
TPANIC_RS01375	GO:0001680	tRNA 3'-terminal CCA addition
TPANIC_RS01375	GO:0016437	tRNA cytidylyltransferase activity
TPANIC_RS01375	GO:0000049	tRNA binding
TPANIC_RS01375	GO:0000287	magnesium ion binding
TPANIC_RS01375	GO:0052927	CTP:tRNA cytidylyltransferase activity
TPANIC_RS01375	GO:0052928	CTP:3'-cytidine-tRNA cytidylyltransferase activity
TPANIC_RS01375	GO:0052929	ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity
TPANIC_RS01375	GO:0005524	ATP binding
TPANIC_RS01375	GO:0042245	RNA repair
TPANIC_RS01380	GO:0007059	chromosome segregation
TPANIC_RS01380	GO:0003677	DNA binding
TPANIC_RS01385	GO:0016787	hydrolase activity
TPANIC_RS01385	GO:0005524	ATP binding
TPANIC_RS01390	GO:0005886	plasma membrane
TPANIC_RS01390	GO:0016021	integral component of membrane
TPANIC_RS01410	GO:0004252	serine-type endopeptidase activity
TPANIC_RS01410	GO:0005576	extracellular region
TPANIC_RS01415	GO:0003735	structural constituent of ribosome
TPANIC_RS01415	GO:0003729	mRNA binding
TPANIC_RS01415	GO:0022627	cytosolic small ribosomal subunit
TPANIC_RS01415	GO:0006412	translation
TPANIC_RS01420	GO:0005886	plasma membrane
TPANIC_RS01420	GO:0016021	integral component of membrane
TPANIC_RS01425	GO:0005737	cytoplasm
TPANIC_RS01425	GO:0005524	ATP binding
TPANIC_RS01425	GO:0004595	pantetheine-phosphate adenylyltransferase activity
TPANIC_RS01425	GO:0015937	coenzyme A biosynthetic process
TPANIC_RS01440	GO:0005829	cytosol
TPANIC_RS01445	GO:0050308	sugar-phosphatase activity
TPANIC_RS01445	GO:0050286	sorbitol-6-phosphatase activity
TPANIC_RS01445	GO:0005829	cytosol
TPANIC_RS01445	GO:0016791	phosphatase activity
TPANIC_RS01445	GO:0103026	fructose-1-phosphatase activity
TPANIC_RS01445	GO:0000287	magnesium ion binding
TPANIC_RS01455	GO:0006811	ion transport
TPANIC_RS01455	GO:0015288	porin activity
TPANIC_RS01455	GO:0046930	pore complex
TPANIC_RS01455	GO:0009279	cell outer membrane
TPANIC_RS01460	GO:0005737	cytoplasm
TPANIC_RS01460	GO:0000287	magnesium ion binding
TPANIC_RS01460	GO:0004749	ribose phosphate diphosphokinase activity
TPANIC_RS01460	GO:0006015	5-phosphoribose 1-diphosphate biosynthetic process
TPANIC_RS01460	GO:0009116	nucleoside metabolic process
TPANIC_RS01460	GO:0009165	nucleotide biosynthetic process
TPANIC_RS01460	GO:0009156	ribonucleoside monophosphate biosynthetic process
TPANIC_RS01460	GO:0016301	kinase activity
TPANIC_RS01460	GO:0005524	ATP binding
TPANIC_RS01470	GO:0005737	cytoplasm
TPANIC_RS01470	GO:0005524	ATP binding
TPANIC_RS01470	GO:0004140	dephospho-CoA kinase activity
TPANIC_RS01470	GO:0015937	coenzyme A biosynthetic process
TPANIC_RS01480	GO:0005886	plasma membrane
TPANIC_RS01485	GO:0005524	ATP binding
TPANIC_RS01485	GO:0016887	ATPase activity
TPANIC_RS01485	GO:0005886	plasma membrane
TPANIC_RS01490	GO:0016021	integral component of membrane
TPANIC_RS01490	GO:0022857	transmembrane transporter activity
TPANIC_RS01490	GO:0005886	plasma membrane
TPANIC_RS01495	GO:0022857	transmembrane transporter activity
TPANIC_RS01495	GO:0005886	plasma membrane
TPANIC_RS01495	GO:0016021	integral component of membrane
TPANIC_RS01500	GO:0006298	mismatch repair
TPANIC_RS01500	GO:0030983	mismatched DNA binding
TPANIC_RS01500	GO:0005524	ATP binding
TPANIC_RS01500	GO:0032300	mismatch repair complex
TPANIC_RS01500	GO:0016887	ATPase activity
TPANIC_RS01510	GO:0044210	'de novo' CTP biosynthetic process
TPANIC_RS01510	GO:0003883	CTP synthase activity
TPANIC_RS01510	GO:0005524	ATP binding
TPANIC_RS01510	GO:0046872	metal ion binding
TPANIC_RS01510	GO:0006541	glutamine metabolic process
TPANIC_RS01515	GO:0006412	translation
TPANIC_RS01515	GO:0003735	structural constituent of ribosome
TPANIC_RS01515	GO:0015935	small ribosomal subunit
TPANIC_RS01515	GO:0019843	rRNA binding
TPANIC_RS01525	GO:0006865	amino acid transport
TPANIC_RS01525	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS01565	GO:0005886	plasma membrane
TPANIC_RS01570	GO:0005886	plasma membrane
TPANIC_RS01570	GO:0016887	ATPase activity
TPANIC_RS01570	GO:0005524	ATP binding
TPANIC_RS01575	GO:0005887	integral component of plasma membrane
TPANIC_RS01575	GO:0022857	transmembrane transporter activity
TPANIC_RS01580	GO:0005886	plasma membrane
TPANIC_RS01580	GO:0016021	integral component of membrane
TPANIC_RS01580	GO:0022857	transmembrane transporter activity
TPANIC_RS01585	GO:0016021	integral component of membrane
TPANIC_RS01590	GO:0016021	integral component of membrane
TPANIC_RS01590	GO:0071709	membrane assembly
TPANIC_RS01590	GO:0009279	cell outer membrane
TPANIC_RS01600	GO:0005524	ATP binding
TPANIC_RS01600	GO:0003684	damaged DNA binding
TPANIC_RS01600	GO:0030983	mismatched DNA binding
TPANIC_RS01600	GO:0006298	mismatch repair
TPANIC_RS01625	GO:0050661	NADP binding
TPANIC_RS01625	GO:0004616	phosphogluconate dehydrogenase (decarboxylating) activity
TPANIC_RS01625	GO:0019521	D-gluconate metabolic process
TPANIC_RS01625	GO:0006098	pentose-phosphate shunt
TPANIC_RS01650	GO:0005737	cytoplasm
TPANIC_RS01650	GO:0003723	RNA binding
TPANIC_RS01650	GO:0000179	rRNA (adenine-N6,N6-)-dimethyltransferase activity
TPANIC_RS01650	GO:0052908	16S rRNA (adenine(1518)-N(6)/adenine(1519)-N(6))-dimethyltransferase activity
TPANIC_RS01655	GO:0016021	integral component of membrane
TPANIC_RS01655	GO:0005886	plasma membrane
TPANIC_RS01660	GO:0006364	rRNA processing
TPANIC_RS01660	GO:0003723	RNA binding
TPANIC_RS01660	GO:0120159	rRNA pseudouridine synthase activity
TPANIC_RS01660	GO:0001522	pseudouridine synthesis
TPANIC_RS01665	GO:0006730	one-carbon metabolic process
TPANIC_RS01665	GO:0046654	tetrahydrofolate biosynthetic process
TPANIC_RS01665	GO:0005524	ATP binding
TPANIC_RS01665	GO:0008841	dihydrofolate synthase activity
TPANIC_RS01665	GO:0046872	metal ion binding
TPANIC_RS01665	GO:0004326	tetrahydrofolylpolyglutamate synthase activity
TPANIC_RS01665	GO:0046656	folic acid biosynthetic process
TPANIC_RS01665	GO:0009396	folic acid-containing compound biosynthetic process
TPANIC_RS01665	GO:0005737	cytoplasm
TPANIC_RS01670	GO:0005737	cytoplasm
TPANIC_RS01670	GO:0008763	UDP-N-acetylmuramate-L-alanine ligase activity
TPANIC_RS01670	GO:0005524	ATP binding
TPANIC_RS01670	GO:0051301	cell division
TPANIC_RS01670	GO:0008360	regulation of cell shape
TPANIC_RS01670	GO:0007049	cell cycle
TPANIC_RS01670	GO:0071555	cell wall organization
TPANIC_RS01670	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS01675	GO:0005737	cytoplasm
TPANIC_RS01675	GO:0005524	ATP binding
TPANIC_RS01675	GO:0006220	pyrimidine nucleotide metabolic process
TPANIC_RS01675	GO:0004127	cytidylate kinase activity
TPANIC_RS01680	GO:0006284	base-excision repair
TPANIC_RS01680	GO:0046872	metal ion binding
TPANIC_RS01680	GO:0019104	DNA N-glycosylase activity
TPANIC_RS01680	GO:0003677	DNA binding
TPANIC_RS01680	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS01685	GO:0005524	ATP binding
TPANIC_RS01685	GO:0005737	cytoplasm
TPANIC_RS01685	GO:0006355	regulation of transcription, DNA-templated
TPANIC_RS01685	GO:0003684	damaged DNA binding
TPANIC_RS01685	GO:0004386	helicase activity
TPANIC_RS01685	GO:0000716	transcription-coupled nucleotide-excision repair, DNA damage recognition
TPANIC_RS01690	GO:0005886	plasma membrane
TPANIC_RS01690	GO:0051992	UDP-N-acetylmuramoyl-L-alanyl-D-glutamyl-meso-2,6-diaminopimelyl-D-alanyl-D-alanine:undecaprenyl-phosphate transferase activity
TPANIC_RS01690	GO:0007049	cell cycle
TPANIC_RS01690	GO:0051301	cell division
TPANIC_RS01690	GO:0071555	cell wall organization
TPANIC_RS01690	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS01690	GO:0008360	regulation of cell shape
TPANIC_RS01690	GO:0008963	phospho-N-acetylmuramoyl-pentapeptide-transferase activity
TPANIC_RS01690	GO:0016021	integral component of membrane
TPANIC_RS01710	GO:0042026	protein refolding
TPANIC_RS01710	GO:0046872	metal ion binding
TPANIC_RS01710	GO:0005737	cytoplasm
TPANIC_RS01710	GO:0003755	peptidyl-prolyl cis-trans isomerase activity
TPANIC_RS01715	GO:0005737	cytoplasm
TPANIC_RS01715	GO:0050661	NADP binding
TPANIC_RS01715	GO:0055129	L-proline biosynthetic process
TPANIC_RS01715	GO:0004350	glutamate-5-semialdehyde dehydrogenase activity
TPANIC_RS01720	GO:0005737	cytoplasm
TPANIC_RS01720	GO:0005524	ATP binding
TPANIC_RS01720	GO:0004349	glutamate 5-kinase activity
TPANIC_RS01720	GO:0055129	L-proline biosynthetic process
TPANIC_RS01725	GO:0003677	DNA binding
TPANIC_RS01725	GO:0006355	regulation of transcription, DNA-templated
TPANIC_RS01730	GO:0005737	cytoplasm
TPANIC_RS01730	GO:0000287	magnesium ion binding
TPANIC_RS01730	GO:0004523	RNA-DNA hybrid ribonuclease activity
TPANIC_RS01730	GO:0006401	RNA catabolic process
TPANIC_RS01730	GO:0003676	nucleic acid binding
TPANIC_RS01735	GO:0005524	ATP binding
TPANIC_RS01735	GO:0004798	thymidylate kinase activity
TPANIC_RS01735	GO:0006233	dTDP biosynthetic process
TPANIC_RS01735	GO:0006235	dTTP biosynthetic process
TPANIC_RS01745	GO:0003677	DNA binding
TPANIC_RS01745	GO:0042803	protein homodimerization activity
TPANIC_RS01745	GO:0009102	biotin biosynthetic process
TPANIC_RS01745	GO:0006768	biotin metabolic process
TPANIC_RS01745	GO:0009305	protein biotinylation
TPANIC_RS01745	GO:0006355	regulation of transcription, DNA-templated
TPANIC_RS01745	GO:0009374	biotin binding
TPANIC_RS01745	GO:0000984	bacterial-type RNA polymerase transcription regulatory region sequence-specific DNA binding
TPANIC_RS01745	GO:0005524	ATP binding
TPANIC_RS01745	GO:0017053	transcription repressor complex
TPANIC_RS01745	GO:0005737	cytoplasm
TPANIC_RS01745	GO:0004077	biotin-[acetyl-CoA-carboxylase] ligase activity
TPANIC_RS01750	GO:0030979	alpha-glucan biosynthetic process
TPANIC_RS01750	GO:0102752	1,4-alpha-glucan branching enzyme activity (using a glucosylated glycogenin as primer for glycogen synthesis)
TPANIC_RS01750	GO:0003844	1,4-alpha-glucan branching enzyme activity
TPANIC_RS01750	GO:0005978	glycogen biosynthetic process
TPANIC_RS01770	GO:0006935	chemotaxis
TPANIC_RS01770	GO:0005737	cytoplasm
TPANIC_RS01770	GO:0000155	phosphorelay sensor kinase activity
TPANIC_RS01770	GO:0005524	ATP binding
TPANIC_RS01775	GO:0005737	cytoplasm
TPANIC_RS01775	GO:0006935	chemotaxis
TPANIC_RS01775	GO:0007165	signal transduction
TPANIC_RS01785	GO:0005737	cytoplasm
TPANIC_RS01785	GO:0006935	chemotaxis
TPANIC_RS01785	GO:0046872	metal ion binding
TPANIC_RS01785	GO:0097588	archaeal or bacterial-type flagellum-dependent cell motility
TPANIC_RS01785	GO:0000160	phosphorelay signal transduction system
TPANIC_RS01795	GO:0016020	membrane
TPANIC_RS01795	GO:0005737	cytoplasm
TPANIC_RS01795	GO:0007062	sister chromatid cohesion
TPANIC_RS01795	GO:0007165	signal transduction
TPANIC_RS01795	GO:0030261	chromosome condensation
TPANIC_RS01795	GO:0003677	DNA binding
TPANIC_RS01795	GO:0005694	chromosome
TPANIC_RS01795	GO:0005524	ATP binding
TPANIC_RS01795	GO:0006260	DNA replication
TPANIC_RS01800	GO:0016021	integral component of membrane
TPANIC_RS01815	GO:0005524	ATP binding
TPANIC_RS01815	GO:0019288	isopentenyl diphosphate biosynthetic process, methylerythritol 4-phosphate pathway
TPANIC_RS01815	GO:0016114	terpenoid biosynthetic process
TPANIC_RS01815	GO:0050515	4-(cytidine 5'-diphospho)-2-C-methyl-D-erythritol kinase activity
TPANIC_RS01825	GO:0008097	5S rRNA binding
TPANIC_RS01825	GO:0003735	structural constituent of ribosome
TPANIC_RS01825	GO:0006412	translation
TPANIC_RS01825	GO:0005840	ribosome
TPANIC_RS01830	GO:0005737	cytoplasm
TPANIC_RS01830	GO:0005524	ATP binding
TPANIC_RS01830	GO:0006400	tRNA modification
TPANIC_RS01830	GO:0016879	ligase activity, forming carbon-nitrogen bonds
TPANIC_RS01855	GO:0065002	intracellular protein transmembrane transport
TPANIC_RS01855	GO:0017038	protein import
TPANIC_RS01855	GO:0006605	protein targeting
TPANIC_RS01855	GO:0005886	plasma membrane
TPANIC_RS01855	GO:0005524	ATP binding
TPANIC_RS01855	GO:0005737	cytoplasm
TPANIC_RS01855	GO:0046872	metal ion binding
TPANIC_RS01865	GO:0016021	integral component of membrane
TPANIC_RS01865	GO:0005886	plasma membrane
TPANIC_RS01870	GO:0005737	cytoplasm
TPANIC_RS01870	GO:0009295	nucleoid
TPANIC_RS01870	GO:0003677	DNA binding
TPANIC_RS01870	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS01875	GO:0071424	rRNA (cytosine-N4-)-methyltransferase activity
TPANIC_RS01875	GO:0005737	cytoplasm
TPANIC_RS01875	GO:0070475	rRNA base methylation
TPANIC_RS01885	GO:0005524	ATP binding
TPANIC_RS01885	GO:0005737	cytoplasm
TPANIC_RS01885	GO:0008360	regulation of cell shape
TPANIC_RS01885	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS01885	GO:0047480	UDP-N-acetylmuramoyl-tripeptide-D-alanyl-D-alanine ligase activity
TPANIC_RS01885	GO:0051301	cell division
TPANIC_RS01885	GO:0007049	cell cycle
TPANIC_RS01885	GO:0071555	cell wall organization
TPANIC_RS01890	GO:0016021	integral component of membrane
TPANIC_RS01890	GO:0005886	plasma membrane
TPANIC_RS01890	GO:0007049	cell cycle
TPANIC_RS01890	GO:0051301	cell division
TPANIC_RS01890	GO:0071555	cell wall organization
TPANIC_RS01890	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS01890	GO:0008360	regulation of cell shape
TPANIC_RS01890	GO:0008955	peptidoglycan glycosyltransferase activity
TPANIC_RS01895	GO:0032153	cell division site
TPANIC_RS01895	GO:0043093	FtsZ-dependent cytokinesis
TPANIC_RS01895	GO:0005887	integral component of plasma membrane
TPANIC_RS01900	GO:0043093	FtsZ-dependent cytokinesis
TPANIC_RS01900	GO:0051301	cell division
TPANIC_RS01900	GO:0009898	cytoplasmic side of plasma membrane
TPANIC_RS01900	GO:0032153	cell division site
TPANIC_RS01905	GO:0005525	GTP binding
TPANIC_RS01905	GO:0003924	GTPase activity
TPANIC_RS01905	GO:0000917	division septum assembly
TPANIC_RS01905	GO:0043093	FtsZ-dependent cytokinesis
TPANIC_RS01905	GO:0051258	protein polymerization
TPANIC_RS01905	GO:0032153	cell division site
TPANIC_RS01905	GO:0005737	cytoplasm
TPANIC_RS01910	GO:0009037	tyrosine-based site-specific recombinase activity
TPANIC_RS01910	GO:0005737	cytoplasm
TPANIC_RS01910	GO:0003677	DNA binding
TPANIC_RS01910	GO:0007049	cell cycle
TPANIC_RS01910	GO:0051301	cell division
TPANIC_RS01910	GO:0007059	chromosome segregation
TPANIC_RS01910	GO:0006313	transposition, DNA-mediated
TPANIC_RS01920	GO:0009294	DNA mediated transformation
TPANIC_RS01925	GO:0005694	chromosome
TPANIC_RS01925	GO:0003677	DNA binding
TPANIC_RS01925	GO:0003917	DNA topoisomerase type I (single strand cut, ATP-independent) activity
TPANIC_RS01925	GO:0046872	metal ion binding
TPANIC_RS01925	GO:0006265	DNA topological change
TPANIC_RS01930	GO:0005737	cytoplasm
TPANIC_RS01930	GO:0009037	tyrosine-based site-specific recombinase activity
TPANIC_RS01930	GO:0007049	cell cycle
TPANIC_RS01930	GO:0051301	cell division
TPANIC_RS01930	GO:0007059	chromosome segregation
TPANIC_RS01930	GO:0006313	transposition, DNA-mediated
TPANIC_RS01930	GO:0003677	DNA binding
TPANIC_RS01935	GO:0030694	bacterial-type flagellum basal body, rod
TPANIC_RS01935	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS01940	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS01940	GO:0030694	bacterial-type flagellum basal body, rod
TPANIC_RS01945	GO:0005198	structural molecule activity
TPANIC_RS01945	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS01945	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS01945	GO:0003774	motor activity
TPANIC_RS01950	GO:0009431	bacterial-type flagellum basal body, MS ring
TPANIC_RS01950	GO:0016021	integral component of membrane
TPANIC_RS01950	GO:0005886	plasma membrane
TPANIC_RS01950	GO:0003774	motor activity
TPANIC_RS01950	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS01955	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS01955	GO:0005886	plasma membrane
TPANIC_RS01955	GO:0003774	motor activity
TPANIC_RS01955	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS01955	GO:0006935	chemotaxis
TPANIC_RS01960	GO:0005737	cytoplasm
TPANIC_RS01960	GO:0044781	bacterial-type flagellum organization
TPANIC_RS01960	GO:0015031	protein transport
TPANIC_RS01965	GO:0009288	bacterial-type flagellum
TPANIC_RS01965	GO:0005737	cytoplasm
TPANIC_RS01965	GO:0030257	type III protein secretion system complex
TPANIC_RS01965	GO:0005524	ATP binding
TPANIC_RS01965	GO:0016887	ATPase activity
TPANIC_RS01965	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
TPANIC_RS01965	GO:0046961	proton-transporting ATPase activity, rotational mechanism
TPANIC_RS01965	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS01965	GO:0030254	protein secretion by the type III secretion system
TPANIC_RS01985	GO:0008881	glutamate racemase activity
TPANIC_RS01985	GO:0071555	cell wall organization
TPANIC_RS01985	GO:0008360	regulation of cell shape
TPANIC_RS01985	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS01990	GO:0018784	(S)-2-haloacid dehalogenase activity
TPANIC_RS02000	GO:0005886	plasma membrane
TPANIC_RS02000	GO:0015031	protein transport
TPANIC_RS02000	GO:0016021	integral component of membrane
TPANIC_RS02005	GO:0016021	integral component of membrane
TPANIC_RS02005	GO:0005886	plasma membrane
TPANIC_RS02005	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
TPANIC_RS02005	GO:0065002	intracellular protein transmembrane transport
TPANIC_RS02005	GO:0006605	protein targeting
TPANIC_RS02005	GO:0043952	protein transport by the Sec complex
TPANIC_RS02010	GO:0043952	protein transport by the Sec complex
TPANIC_RS02010	GO:0006605	protein targeting
TPANIC_RS02010	GO:0065002	intracellular protein transmembrane transport
TPANIC_RS02010	GO:0005886	plasma membrane
TPANIC_RS02010	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
TPANIC_RS02010	GO:0016021	integral component of membrane
TPANIC_RS02020	GO:0008966	phosphoglucosamine mutase activity
TPANIC_RS02020	GO:0000287	magnesium ion binding
TPANIC_RS02020	GO:0005975	carbohydrate metabolic process
TPANIC_RS02025	GO:0016021	integral component of membrane
TPANIC_RS02025	GO:0005886	plasma membrane
TPANIC_RS02025	GO:0015655	alanine:sodium symporter activity
TPANIC_RS02035	GO:0048500	signal recognition particle
TPANIC_RS02035	GO:0005525	GTP binding
TPANIC_RS02035	GO:0003924	GTPase activity
TPANIC_RS02035	GO:0006614	SRP-dependent cotranslational protein targeting to membrane
TPANIC_RS02035	GO:0008312	7S RNA binding
TPANIC_RS02040	GO:0005886	plasma membrane
TPANIC_RS02040	GO:0016410	N-acyltransferase activity
TPANIC_RS02040	GO:0042158	lipoprotein biosynthetic process
TPANIC_RS02040	GO:0016021	integral component of membrane
TPANIC_RS02045	GO:0005737	cytoplasm
TPANIC_RS02045	GO:0005524	ATP binding
TPANIC_RS02045	GO:0006012	galactose metabolic process
TPANIC_RS02045	GO:0004335	galactokinase activity
TPANIC_RS02045	GO:0046872	metal ion binding
TPANIC_RS02050	GO:0005737	cytoplasm
TPANIC_RS02050	GO:0000166	nucleotide binding
TPANIC_RS02050	GO:0046872	metal ion binding
TPANIC_RS02050	GO:0008253	5'-nucleotidase activity
TPANIC_RS02070	GO:0006754	ATP biosynthetic process
TPANIC_RS02070	GO:0006811	ion transport
TPANIC_RS02080	GO:0046961	proton-transporting ATPase activity, rotational mechanism
TPANIC_RS02080	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
TPANIC_RS02080	GO:0005524	ATP binding
TPANIC_RS02080	GO:0042777	plasma membrane ATP synthesis coupled proton transport
TPANIC_RS02085	GO:0005524	ATP binding
TPANIC_RS02085	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
TPANIC_RS02085	GO:0042777	plasma membrane ATP synthesis coupled proton transport
TPANIC_RS02090	GO:0005524	ATP binding
TPANIC_RS02090	GO:0042626	ATPase-coupled transmembrane transporter activity
TPANIC_RS02090	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
TPANIC_RS02090	GO:0042777	plasma membrane ATP synthesis coupled proton transport
TPANIC_RS02095	GO:0033179	proton-transporting V-type ATPase, V0 domain
TPANIC_RS02095	GO:0015078	proton transmembrane transporter activity
TPANIC_RS02095	GO:0016021	integral component of membrane
TPANIC_RS02095	GO:0005886	plasma membrane
TPANIC_RS02105	GO:0005524	ATP binding
TPANIC_RS02105	GO:0046872	metal ion binding
TPANIC_RS02105	GO:0004594	pantothenate kinase activity
TPANIC_RS02105	GO:0015937	coenzyme A biosynthetic process
TPANIC_RS02105	GO:0005737	cytoplasm
TPANIC_RS02120	GO:0005886	plasma membrane
TPANIC_RS02125	GO:0004427	inorganic diphosphatase activity
TPANIC_RS02125	GO:0030145	manganese ion binding
TPANIC_RS02125	GO:0005737	cytoplasm
TPANIC_RS02135	GO:0035870	dITP diphosphatase activity
TPANIC_RS02135	GO:0046872	metal ion binding
TPANIC_RS02135	GO:0017111	nucleoside-triphosphatase activity
TPANIC_RS02135	GO:0000166	nucleotide binding
TPANIC_RS02135	GO:0036222	XTP diphosphatase activity
TPANIC_RS02135	GO:0009117	nucleotide metabolic process
TPANIC_RS02135	GO:0009146	purine nucleoside triphosphate catabolic process
TPANIC_RS02140	GO:0007165	signal transduction
TPANIC_RS02140	GO:0006935	chemotaxis
TPANIC_RS02140	GO:0005737	cytoplasm
TPANIC_RS02150	GO:0046872	metal ion binding
TPANIC_RS02150	GO:0003951	NAD+ kinase activity
TPANIC_RS02150	GO:0019674	NAD metabolic process
TPANIC_RS02150	GO:0006741	NADP biosynthetic process
TPANIC_RS02150	GO:0005737	cytoplasm
TPANIC_RS02150	GO:0005524	ATP binding
TPANIC_RS02155	GO:0005524	ATP binding
TPANIC_RS02155	GO:0006281	DNA repair
TPANIC_RS02155	GO:0006310	DNA recombination
TPANIC_RS02175	GO:0046429	4-hydroxy-3-methylbut-2-en-1-yl diphosphate synthase activity
TPANIC_RS02175	GO:0005506	iron ion binding
TPANIC_RS02175	GO:0019288	isopentenyl diphosphate biosynthetic process, methylerythritol 4-phosphate pathway
TPANIC_RS02175	GO:0016114	terpenoid biosynthetic process
TPANIC_RS02175	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS02185	GO:0005525	GTP binding
TPANIC_RS02185	GO:0004845	uracil phosphoribosyltransferase activity
TPANIC_RS02185	GO:0009116	nucleoside metabolic process
TPANIC_RS02185	GO:0044206	UMP salvage
TPANIC_RS02190	GO:0005886	plasma membrane
TPANIC_RS02195	GO:0005525	GTP binding
TPANIC_RS02195	GO:0005737	cytoplasm
TPANIC_RS02195	GO:0003746	translation elongation factor activity
TPANIC_RS02195	GO:0003924	GTPase activity
TPANIC_RS02205	GO:0005737	cytoplasm
TPANIC_RS02205	GO:0002161	aminoacyl-tRNA editing activity
TPANIC_RS02205	GO:0005524	ATP binding
TPANIC_RS02205	GO:0004822	isoleucine-tRNA ligase activity
TPANIC_RS02205	GO:0000049	tRNA binding
TPANIC_RS02205	GO:0008270	zinc ion binding
TPANIC_RS02205	GO:0006428	isoleucyl-tRNA aminoacylation
TPANIC_RS02210	GO:0009279	cell outer membrane
TPANIC_RS02230	GO:0005886	plasma membrane
TPANIC_RS02240	GO:0006260	DNA replication
TPANIC_RS02240	GO:0005737	cytoplasm
TPANIC_RS02240	GO:0051304	chromosome separation
TPANIC_RS02240	GO:0051301	cell division
TPANIC_RS02245	GO:0001522	pseudouridine synthesis
TPANIC_RS02245	GO:0009982	pseudouridine synthase activity
TPANIC_RS02245	GO:0003723	RNA binding
TPANIC_RS02260	GO:0005886	plasma membrane
TPANIC_RS02265	GO:0008176	tRNA (guanine-N7-)-methyltransferase activity
TPANIC_RS02270	GO:0005886	plasma membrane
TPANIC_RS02270	GO:0016021	integral component of membrane
TPANIC_RS02295	GO:0009432	SOS response
TPANIC_RS02295	GO:0006289	nucleotide-excision repair
TPANIC_RS02295	GO:0003677	DNA binding
TPANIC_RS02295	GO:0009380	excinuclease repair complex
TPANIC_RS02295	GO:0005737	cytoplasm
TPANIC_RS02295	GO:0009381	excinuclease ABC activity
TPANIC_RS02300	GO:0005886	plasma membrane
TPANIC_RS02300	GO:0016021	integral component of membrane
TPANIC_RS02305	GO:0005737	cytoplasm
TPANIC_RS02305	GO:0003677	DNA binding
TPANIC_RS02305	GO:0006355	regulation of transcription, DNA-templated
TPANIC_RS02310	GO:0006096	glycolytic process
TPANIC_RS02310	GO:0005737	cytoplasm
TPANIC_RS02310	GO:0004347	glucose-6-phosphate isomerase activity
TPANIC_RS02310	GO:0006094	gluconeogenesis
TPANIC_RS02315	GO:0000287	magnesium ion binding
TPANIC_RS02315	GO:0005737	cytoplasm
TPANIC_RS02315	GO:0008776	acetate kinase activity
TPANIC_RS02315	GO:0006085	acetyl-CoA biosynthetic process
TPANIC_RS02315	GO:0006082	organic acid metabolic process
TPANIC_RS02315	GO:0005524	ATP binding
TPANIC_RS02320	GO:0017057	6-phosphogluconolactonase activity
TPANIC_RS02320	GO:0005975	carbohydrate metabolic process
TPANIC_RS02320	GO:0006098	pentose-phosphate shunt
TPANIC_RS02325	GO:0004345	glucose-6-phosphate dehydrogenase activity
TPANIC_RS02325	GO:0050661	NADP binding
TPANIC_RS02325	GO:0006006	glucose metabolic process
TPANIC_RS02325	GO:0006098	pentose-phosphate shunt
TPANIC_RS02335	GO:0016021	integral component of membrane
TPANIC_RS02335	GO:0005886	plasma membrane
TPANIC_RS02340	GO:0016021	integral component of membrane
TPANIC_RS02350	GO:0016021	integral component of membrane
TPANIC_RS02355	GO:0004016	adenylate cyclase activity
TPANIC_RS02355	GO:0005524	ATP binding
TPANIC_RS02355	GO:0046872	metal ion binding
TPANIC_RS02355	GO:0006171	cAMP biosynthetic process
TPANIC_RS02355	GO:0000160	phosphorelay signal transduction system
TPANIC_RS02370	GO:0016021	integral component of membrane
TPANIC_RS02370	GO:0005886	plasma membrane
TPANIC_RS02370	GO:0006935	chemotaxis
TPANIC_RS02370	GO:0007165	signal transduction
TPANIC_RS02395	GO:0005887	integral component of plasma membrane
TPANIC_RS02395	GO:0008932	lytic endotransglycosylase activity
TPANIC_RS02395	GO:0071555	cell wall organization
TPANIC_RS02395	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS02395	GO:0016829	lyase activity
TPANIC_RS02400	GO:1990077	primosome complex
TPANIC_RS02400	GO:0003677	DNA binding
TPANIC_RS02400	GO:0003896	DNA primase activity
TPANIC_RS02400	GO:0008270	zinc ion binding
TPANIC_RS02405	GO:0005737	cytoplasm
TPANIC_RS02405	GO:0003677	DNA binding
TPANIC_RS02405	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS02405	GO:0016987	sigma factor activity
TPANIC_RS02405	GO:0001123	transcription initiation from bacterial-type RNA polymerase promoter
TPANIC_RS02420	GO:0008360	regulation of cell shape
TPANIC_RS02420	GO:0000902	cell morphogenesis
TPANIC_RS02420	GO:0005524	ATP binding
TPANIC_RS02420	GO:0005737	cytoplasm
TPANIC_RS02435	GO:0008360	regulation of cell shape
TPANIC_RS02435	GO:0005887	integral component of plasma membrane
TPANIC_RS02435	GO:0008658	penicillin binding
TPANIC_RS02435	GO:0071972	peptidoglycan L,D-transpeptidase activity
TPANIC_RS02435	GO:0009002	serine-type D-Ala-D-Ala carboxypeptidase activity
TPANIC_RS02435	GO:0071555	cell wall organization
TPANIC_RS02435	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS02440	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS02440	GO:0051301	cell division
TPANIC_RS02440	GO:0008360	regulation of cell shape
TPANIC_RS02440	GO:0071555	cell wall organization
TPANIC_RS02440	GO:0008955	peptidoglycan glycosyltransferase activity
TPANIC_RS02440	GO:0005887	integral component of plasma membrane
TPANIC_RS02450	GO:0005886	plasma membrane
TPANIC_RS02475	GO:0007049	cell cycle
TPANIC_RS02475	GO:0051301	cell division
TPANIC_RS02475	GO:0006457	protein folding
TPANIC_RS02475	GO:0005737	cytoplasm
TPANIC_RS02475	GO:0015031	protein transport
TPANIC_RS02475	GO:0003755	peptidyl-prolyl cis-trans isomerase activity
TPANIC_RS02480	GO:0005737	cytoplasm
TPANIC_RS02480	GO:0004176	ATP-dependent peptidase activity
TPANIC_RS02480	GO:0004252	serine-type endopeptidase activity
TPANIC_RS02485	GO:0005524	ATP binding
TPANIC_RS02485	GO:0016887	ATPase activity
TPANIC_RS02485	GO:0046983	protein dimerization activity
TPANIC_RS02485	GO:0051082	unfolded protein binding
TPANIC_RS02485	GO:0006457	protein folding
TPANIC_RS02485	GO:0008270	zinc ion binding
TPANIC_RS02490	GO:0005829	cytosol
TPANIC_RS02490	GO:0102039	alkylhydroperoxide reductase activity
TPANIC_RS02490	GO:0008379	thioredoxin peroxidase activity
TPANIC_RS02490	GO:0045454	cell redox homeostasis
TPANIC_RS02490	GO:0006979	response to oxidative stress
TPANIC_RS02495	GO:0045727	positive regulation of translation
TPANIC_RS02495	GO:0005886	plasma membrane
TPANIC_RS02495	GO:0005525	GTP binding
TPANIC_RS02495	GO:0003924	GTPase activity
TPANIC_RS02495	GO:0043022	ribosome binding
TPANIC_RS02495	GO:0003746	translation elongation factor activity
TPANIC_RS02505	GO:0008685	2-C-methyl-D-erythritol 2,4-cyclodiphosphate synthase activity
TPANIC_RS02505	GO:0046872	metal ion binding
TPANIC_RS02505	GO:0019288	isopentenyl diphosphate biosynthetic process, methylerythritol 4-phosphate pathway
TPANIC_RS02505	GO:0016114	terpenoid biosynthetic process
TPANIC_RS02505	GO:0050518	2-C-methyl-D-erythritol 4-phosphate cytidylyltransferase activity
TPANIC_RS02515	GO:0005737	cytoplasm
TPANIC_RS02515	GO:0009380	excinuclease repair complex
TPANIC_RS02515	GO:0005524	ATP binding
TPANIC_RS02515	GO:0016887	ATPase activity
TPANIC_RS02515	GO:0003677	DNA binding
TPANIC_RS02515	GO:0009381	excinuclease ABC activity
TPANIC_RS02515	GO:0008270	zinc ion binding
TPANIC_RS02515	GO:0006289	nucleotide-excision repair
TPANIC_RS02515	GO:0009432	SOS response
TPANIC_RS02525	GO:0008360	regulation of cell shape
TPANIC_RS02525	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS02525	GO:0071555	cell wall organization
TPANIC_RS02525	GO:0005887	integral component of plasma membrane
TPANIC_RS02525	GO:0015648	lipid-linked peptidoglycan transporter activity
TPANIC_RS02530	GO:0006310	DNA recombination
TPANIC_RS02530	GO:0008821	crossover junction endodeoxyribonuclease activity
TPANIC_RS02530	GO:0000287	magnesium ion binding
TPANIC_RS02530	GO:0003676	nucleic acid binding
TPANIC_RS02530	GO:0006281	DNA repair
TPANIC_RS02540	GO:0010967	regulation of polyamine biosynthetic process
TPANIC_RS02540	GO:0000160	phosphorelay signal transduction system
TPANIC_RS02540	GO:0008134	transcription factor binding
TPANIC_RS02540	GO:0043565	sequence-specific DNA binding
TPANIC_RS02540	GO:0008073	ornithine decarboxylase inhibitor activity
TPANIC_RS02540	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS02540	GO:0005524	ATP binding
TPANIC_RS02540	GO:0005737	cytoplasm
TPANIC_RS02540	GO:0045893	positive regulation of transcription, DNA-templated
TPANIC_RS02545	GO:0016021	integral component of membrane
TPANIC_RS02545	GO:0005524	ATP binding
TPANIC_RS02545	GO:0000155	phosphorelay sensor kinase activity
TPANIC_RS02545	GO:0030435	sporulation resulting in formation of a cellular spore
TPANIC_RS02545	GO:0005886	plasma membrane
TPANIC_RS02550	GO:0009360	DNA polymerase III complex
TPANIC_RS02550	GO:0003677	DNA binding
TPANIC_RS02550	GO:0006260	DNA replication
TPANIC_RS02550	GO:0003887	DNA-directed DNA polymerase activity
TPANIC_RS02555	GO:0005886	plasma membrane
TPANIC_RS02555	GO:0016021	integral component of membrane
TPANIC_RS02555	GO:0009403	toxin biosynthetic process
TPANIC_RS02560	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS02560	GO:0005886	plasma membrane
TPANIC_RS02560	GO:0051991	UDP-N-acetyl-D-glucosamine:N-acetylmuramoyl-L-alanyl-D-glutamyl-meso-2,6-diaminopimelyl-D-alanyl-D-alanine-diphosphoundecaprenol 4-beta-N-acetylglucosaminlytransferase activity
TPANIC_RS02560	GO:0030259	lipid glycosylation
TPANIC_RS02560	GO:0008360	regulation of cell shape
TPANIC_RS02560	GO:0007049	cell cycle
TPANIC_RS02560	GO:0051301	cell division
TPANIC_RS02560	GO:0071555	cell wall organization
TPANIC_RS02560	GO:0050511	undecaprenyldiphospho-muramoylpentapeptide beta-N-acetylglucosaminyltransferase activity
TPANIC_RS02560	GO:0005975	carbohydrate metabolic process
TPANIC_RS02565	GO:0005737	cytoplasm
TPANIC_RS02565	GO:0004176	ATP-dependent peptidase activity
TPANIC_RS02565	GO:0043565	sequence-specific DNA binding
TPANIC_RS02565	GO:0004252	serine-type endopeptidase activity
TPANIC_RS02565	GO:0034605	cellular response to heat
TPANIC_RS02565	GO:0006515	protein quality control for misfolded or incompletely synthesized proteins
TPANIC_RS02565	GO:0005524	ATP binding
TPANIC_RS02570	GO:0005737	cytoplasm
TPANIC_RS02570	GO:0003746	translation elongation factor activity
TPANIC_RS02580	GO:0005524	ATP binding
TPANIC_RS02580	GO:0009405	pathogenesis
TPANIC_RS02580	GO:0003724	RNA helicase activity
TPANIC_RS02580	GO:0003676	nucleic acid binding
TPANIC_RS02585	GO:0042777	plasma membrane ATP synthesis coupled proton transport
TPANIC_RS02585	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
TPANIC_RS02585	GO:0042626	ATPase-coupled transmembrane transporter activity
TPANIC_RS02585	GO:0005524	ATP binding
TPANIC_RS02590	GO:0042777	plasma membrane ATP synthesis coupled proton transport
TPANIC_RS02590	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
TPANIC_RS02590	GO:0005524	ATP binding
TPANIC_RS02595	GO:0042777	plasma membrane ATP synthesis coupled proton transport
TPANIC_RS02595	GO:0046961	proton-transporting ATPase activity, rotational mechanism
TPANIC_RS02595	GO:0005524	ATP binding
TPANIC_RS02595	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
TPANIC_RS02615	GO:0016021	integral component of membrane
TPANIC_RS02615	GO:0015078	proton transmembrane transporter activity
TPANIC_RS02615	GO:0033179	proton-transporting V-type ATPase, V0 domain
TPANIC_RS02615	GO:0005886	plasma membrane
TPANIC_RS02630	GO:0016021	integral component of membrane
TPANIC_RS02630	GO:0005886	plasma membrane
TPANIC_RS02630	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
TPANIC_RS02630	GO:0009306	protein secretion
TPANIC_RS02635	GO:0005737	cytoplasm
TPANIC_RS02635	GO:0004807	triose-phosphate isomerase activity
TPANIC_RS02635	GO:0006094	gluconeogenesis
TPANIC_RS02635	GO:0006096	glycolytic process
TPANIC_RS02640	GO:0006096	glycolytic process
TPANIC_RS02640	GO:0005737	cytoplasm
TPANIC_RS02640	GO:0005524	ATP binding
TPANIC_RS02640	GO:0004618	phosphoglycerate kinase activity
TPANIC_RS02650	GO:0042802	identical protein binding
TPANIC_RS02650	GO:0043856	anti-sigma factor antagonist activity
TPANIC_RS02655	GO:0003924	GTPase activity
TPANIC_RS02655	GO:0005737	cytoplasm
TPANIC_RS02655	GO:0005886	plasma membrane
TPANIC_RS02655	GO:0042274	ribosomal small subunit biogenesis
TPANIC_RS02655	GO:0070181	small ribosomal subunit rRNA binding
TPANIC_RS02655	GO:0005525	GTP binding
TPANIC_RS02660	GO:0006002	fructose 6-phosphate metabolic process
TPANIC_RS02660	GO:0046872	metal ion binding
TPANIC_RS02660	GO:0047334	diphosphate-fructose-6-phosphate 1-phosphotransferase activity
TPANIC_RS02660	GO:0005524	ATP binding
TPANIC_RS02660	GO:0003872	6-phosphofructokinase activity
TPANIC_RS02660	GO:0005737	cytoplasm
TPANIC_RS02665	GO:0005524	ATP binding
TPANIC_RS02665	GO:0009378	four-way junction helicase activity
TPANIC_RS02665	GO:0006310	DNA recombination
TPANIC_RS02665	GO:0006281	DNA repair
TPANIC_RS02665	GO:0009432	SOS response
TPANIC_RS02665	GO:0003677	DNA binding
TPANIC_RS02675	GO:0042597	periplasmic space
TPANIC_RS02680	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS02680	GO:0004252	serine-type endopeptidase activity
TPANIC_RS02685	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS02685	GO:0051745	4-hydroxy-3-methylbut-2-en-1-yl diphosphate reductase activity
TPANIC_RS02685	GO:0046872	metal ion binding
TPANIC_RS02685	GO:0050992	dimethylallyl diphosphate biosynthetic process
TPANIC_RS02685	GO:0019288	isopentenyl diphosphate biosynthetic process, methylerythritol 4-phosphate pathway
TPANIC_RS02685	GO:0016114	terpenoid biosynthetic process
TPANIC_RS02700	GO:0044179	hemolysis in other organism
TPANIC_RS02700	GO:0009405	pathogenesis
TPANIC_RS02700	GO:0005524	ATP binding
TPANIC_RS02700	GO:0090729	toxin activity
TPANIC_RS02700	GO:0016887	ATPase activity
TPANIC_RS02705	GO:0003924	GTPase activity
TPANIC_RS02705	GO:0046872	metal ion binding
TPANIC_RS02705	GO:0006400	tRNA modification
TPANIC_RS02705	GO:0005737	cytoplasm
TPANIC_RS02705	GO:0005525	GTP binding
TPANIC_RS02725	GO:0016021	integral component of membrane
TPANIC_RS02725	GO:0005886	plasma membrane
TPANIC_RS02730	GO:0008967	phosphoglycolate phosphatase activity
TPANIC_RS02730	GO:0005975	carbohydrate metabolic process
TPANIC_RS02730	GO:0046295	glycolate biosynthetic process
TPANIC_RS02730	GO:0046872	metal ion binding
TPANIC_RS02740	GO:0005737	cytoplasm
TPANIC_RS02740	GO:0004071	aspartate-ammonia ligase activity
TPANIC_RS02740	GO:0005524	ATP binding
TPANIC_RS02740	GO:0070981	L-asparagine biosynthetic process
TPANIC_RS02755	GO:0009229	thiamine diphosphate biosynthetic process
TPANIC_RS02755	GO:0034227	tRNA thio-modification
TPANIC_RS02755	GO:0005737	cytoplasm
TPANIC_RS02755	GO:0005524	ATP binding
TPANIC_RS02755	GO:0009228	thiamine biosynthetic process
TPANIC_RS02755	GO:0004810	tRNA adenylyltransferase activity
TPANIC_RS02755	GO:0000049	tRNA binding
TPANIC_RS02755	GO:0016783	sulfurtransferase activity
TPANIC_RS02760	GO:0046872	metal ion binding
TPANIC_RS02760	GO:0004802	transketolase activity
TPANIC_RS02765	GO:0005886	plasma membrane
TPANIC_RS02765	GO:0016021	integral component of membrane
TPANIC_RS02770	GO:0047444	N-acylneuraminate-9-phosphate synthase activity
TPANIC_RS02770	GO:0016051	carbohydrate biosynthetic process
TPANIC_RS02770	GO:0070085	glycosylation
TPANIC_RS02795	GO:0042121	alginic acid biosynthetic process
TPANIC_RS02795	GO:0016021	integral component of membrane
TPANIC_RS02795	GO:0005886	plasma membrane
TPANIC_RS02795	GO:0051979	alginic acid acetylation
TPANIC_RS02795	GO:0016746	transferase activity, transferring acyl groups
TPANIC_RS02805	GO:0008700	4-hydroxy-2-oxoglutarate aldolase activity
TPANIC_RS02805	GO:0008675	2-dehydro-3-deoxy-phosphogluconate aldolase activity
TPANIC_RS02805	GO:0005737	cytoplasm
TPANIC_RS02805	GO:0008152	metabolic process
TPANIC_RS02810	GO:0004177	aminopeptidase activity
TPANIC_RS02810	GO:0046872	metal ion binding
TPANIC_RS02810	GO:0008237	metallopeptidase activity
TPANIC_RS02810	GO:0008233	peptidase activity
TPANIC_RS02810	GO:0005829	cytosol
TPANIC_RS02825	GO:0016021	integral component of membrane
TPANIC_RS02825	GO:0010181	FMN binding
TPANIC_RS02825	GO:0005886	plasma membrane
TPANIC_RS02830	GO:0005886	plasma membrane
TPANIC_RS02830	GO:0008233	peptidase activity
TPANIC_RS02835	GO:0005737	cytoplasm
TPANIC_RS02835	GO:0046872	metal ion binding
TPANIC_RS02835	GO:0008965	phosphoenolpyruvate-protein phosphotransferase activity
TPANIC_RS02835	GO:0009401	phosphoenolpyruvate-dependent sugar phosphotransferase system
TPANIC_RS02835	GO:0016301	kinase activity
TPANIC_RS02840	GO:0005737	cytoplasm
TPANIC_RS02840	GO:0016149	translation release factor activity, codon specific
TPANIC_RS02845	GO:0016021	integral component of membrane
TPANIC_RS02845	GO:0005886	plasma membrane
TPANIC_RS02850	GO:0005737	cytoplasm
TPANIC_RS02850	GO:0031226	intrinsic component of plasma membrane
TPANIC_RS02850	GO:0005525	GTP binding
TPANIC_RS02850	GO:0003924	GTPase activity
TPANIC_RS02850	GO:0006614	SRP-dependent cotranslational protein targeting to membrane
TPANIC_RS02860	GO:0016021	integral component of membrane
TPANIC_RS02860	GO:0098797	plasma membrane protein complex
TPANIC_RS02860	GO:0044874	lipoprotein localization to outer membrane
TPANIC_RS02860	GO:0042953	lipoprotein transport
TPANIC_RS02865	GO:0005886	plasma membrane
TPANIC_RS02865	GO:0005524	ATP binding
TPANIC_RS02865	GO:0140306	lipoprotein releasing activity
TPANIC_RS02865	GO:0042953	lipoprotein transport
TPANIC_RS02870	GO:0016021	integral component of membrane
TPANIC_RS02870	GO:0005886	plasma membrane
TPANIC_RS02870	GO:0042953	lipoprotein transport
TPANIC_RS02880	GO:0030435	sporulation resulting in formation of a cellular spore
TPANIC_RS02880	GO:0015031	protein transport
TPANIC_RS02880	GO:0015833	peptide transport
TPANIC_RS02880	GO:1904680	peptide transmembrane transporter activity
TPANIC_RS02880	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS02880	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS02885	GO:0005524	ATP binding
TPANIC_RS02885	GO:0005737	cytoplasm
TPANIC_RS02885	GO:0006429	leucyl-tRNA aminoacylation
TPANIC_RS02885	GO:0002161	aminoacyl-tRNA editing activity
TPANIC_RS02885	GO:0004823	leucine-tRNA ligase activity
TPANIC_RS02895	GO:0005737	cytoplasm
TPANIC_RS02895	GO:0009401	phosphoenolpyruvate-dependent sugar phosphotransferase system
TPANIC_RS02900	GO:0000287	magnesium ion binding
TPANIC_RS02900	GO:0005524	ATP binding
TPANIC_RS02900	GO:0000155	phosphorelay sensor kinase activity
TPANIC_RS02900	GO:0004674	protein serine/threonine kinase activity
TPANIC_RS02900	GO:0004712	protein serine/threonine/tyrosine kinase activity
TPANIC_RS02900	GO:0006109	regulation of carbohydrate metabolic process
TPANIC_RS02930	GO:0016021	integral component of membrane
TPANIC_RS02930	GO:0005886	plasma membrane
TPANIC_RS02940	GO:0005737	cytoplasm
TPANIC_RS02940	GO:0004017	adenylate kinase activity
TPANIC_RS02940	GO:0005524	ATP binding
TPANIC_RS02940	GO:0008270	zinc ion binding
TPANIC_RS02940	GO:0044209	AMP salvage
TPANIC_RS02945	GO:0005737	cytoplasm
TPANIC_RS02945	GO:0005829	cytosol
TPANIC_RS02945	GO:0005524	ATP binding
TPANIC_RS02945	GO:0004652	polynucleotide adenylyltransferase activity
TPANIC_RS02945	GO:0003723	RNA binding
TPANIC_RS02945	GO:0006378	mRNA polyadenylation
TPANIC_RS02945	GO:0006397	mRNA processing
TPANIC_RS02945	GO:0006276	plasmid maintenance
TPANIC_RS02945	GO:0009451	RNA modification
TPANIC_RS02945	GO:0005886	plasma membrane
TPANIC_RS02960	GO:0016021	integral component of membrane
TPANIC_RS02960	GO:0005886	plasma membrane
TPANIC_RS02960	GO:0046872	metal ion binding
TPANIC_RS02960	GO:0004222	metalloendopeptidase activity
TPANIC_RS02965	GO:0070402	NADPH binding
TPANIC_RS02965	GO:0030604	1-deoxy-D-xylulose-5-phosphate reductoisomerase activity
TPANIC_RS02965	GO:0046872	metal ion binding
TPANIC_RS02965	GO:0016114	terpenoid biosynthetic process
TPANIC_RS02965	GO:0019288	isopentenyl diphosphate biosynthetic process, methylerythritol 4-phosphate pathway
TPANIC_RS02970	GO:0016021	integral component of membrane
TPANIC_RS02970	GO:0005886	plasma membrane
TPANIC_RS02970	GO:0004605	phosphatidate cytidylyltransferase activity
TPANIC_RS02970	GO:0016024	CDP-diacylglycerol biosynthetic process
TPANIC_RS02975	GO:0004659	prenyltransferase activity
TPANIC_RS02975	GO:0000287	magnesium ion binding
TPANIC_RS02980	GO:0005737	cytoplasm
TPANIC_RS02980	GO:0006415	translational termination
TPANIC_RS02985	GO:0003746	translation elongation factor activity
TPANIC_RS02985	GO:0005737	cytoplasm
TPANIC_RS02990	GO:0003735	structural constituent of ribosome
TPANIC_RS02990	GO:0006412	translation
TPANIC_RS02990	GO:0015935	small ribosomal subunit
TPANIC_RS03000	GO:0016021	integral component of membrane
TPANIC_RS03010	GO:0005737	cytoplasm
TPANIC_RS03010	GO:0004816	asparagine-tRNA ligase activity
TPANIC_RS03010	GO:0005524	ATP binding
TPANIC_RS03010	GO:0006421	asparaginyl-tRNA aminoacylation
TPANIC_RS03010	GO:0003676	nucleic acid binding
TPANIC_RS03020	GO:0005524	ATP binding
TPANIC_RS03020	GO:0016887	ATPase activity
TPANIC_RS03020	GO:0005886	plasma membrane
TPANIC_RS03025	GO:0016226	iron-sulfur cluster assembly
TPANIC_RS03030	GO:0016226	iron-sulfur cluster assembly
TPANIC_RS03035	GO:0031071	cysteine desulfurase activity
TPANIC_RS03035	GO:0030170	pyridoxal phosphate binding
TPANIC_RS03035	GO:0006534	cysteine metabolic process
TPANIC_RS03045	GO:0009052	pentose-phosphate shunt, non-oxidative branch
TPANIC_RS03045	GO:0004751	ribose-5-phosphate isomerase activity
TPANIC_RS03080	GO:0005886	plasma membrane
TPANIC_RS03080	GO:0008932	lytic endotransglycosylase activity
TPANIC_RS03080	GO:0016020	membrane
TPANIC_RS03080	GO:0000270	peptidoglycan metabolic process
TPANIC_RS03080	GO:0016829	lyase activity
TPANIC_RS03080	GO:0071555	cell wall organization
TPANIC_RS03080	GO:0008933	lytic transglycosylase activity
TPANIC_RS03080	GO:0051353	positive regulation of oxidoreductase activity
TPANIC_RS03095	GO:0006260	DNA replication
TPANIC_RS03095	GO:0008408	3'-5' exonuclease activity
TPANIC_RS03095	GO:0006310	DNA recombination
TPANIC_RS03095	GO:0004519	endonuclease activity
TPANIC_RS03100	GO:0005524	ATP binding
TPANIC_RS03100	GO:0004519	endonuclease activity
TPANIC_RS03100	GO:0004527	exonuclease activity
TPANIC_RS03100	GO:0006310	DNA recombination
TPANIC_RS03100	GO:0006260	DNA replication
TPANIC_RS03105	GO:0005829	cytosol
TPANIC_RS03105	GO:0004516	nicotinate phosphoribosyltransferase activity
TPANIC_RS03105	GO:0004514	nicotinate-nucleotide diphosphorylase (carboxylating) activity
TPANIC_RS03105	GO:0009435	NAD biosynthetic process
TPANIC_RS03105	GO:0034355	NAD salvage
TPANIC_RS03115	GO:0006935	chemotaxis
TPANIC_RS03115	GO:0008983	protein-glutamate O-methyltransferase activity
TPANIC_RS03120	GO:0000156	phosphorelay response regulator activity
TPANIC_RS03120	GO:0050568	protein-glutamine glutaminase activity
TPANIC_RS03120	GO:0006935	chemotaxis
TPANIC_RS03120	GO:0018277	protein deamination
TPANIC_RS03120	GO:0006482	protein demethylation
TPANIC_RS03120	GO:0005737	cytoplasm
TPANIC_RS03120	GO:0008984	protein-glutamate methylesterase activity
TPANIC_RS03125	GO:0005737	cytoplasm
TPANIC_RS03125	GO:0005524	ATP binding
TPANIC_RS03125	GO:0004830	tryptophan-tRNA ligase activity
TPANIC_RS03125	GO:0006436	tryptophanyl-tRNA aminoacylation
TPANIC_RS03130	GO:0033743	peptide-methionine (R)-S-oxide reductase activity
TPANIC_RS03130	GO:0006464	cellular protein modification process
TPANIC_RS03130	GO:0030091	protein repair
TPANIC_RS03130	GO:0006979	response to oxidative stress
TPANIC_RS03130	GO:0008113	peptide-methionine (S)-S-oxide reductase activity
TPANIC_RS03135	GO:0003911	DNA ligase (NAD+) activity
TPANIC_RS03135	GO:0006281	DNA repair
TPANIC_RS03135	GO:0006260	DNA replication
TPANIC_RS03135	GO:0046872	metal ion binding
TPANIC_RS03135	GO:0003677	DNA binding
TPANIC_RS03145	GO:0008033	tRNA processing
TPANIC_RS03145	GO:0052381	tRNA dimethylallyltransferase activity
TPANIC_RS03145	GO:0005524	ATP binding
TPANIC_RS03150	GO:0005886	plasma membrane
TPANIC_RS03150	GO:0016021	integral component of membrane
TPANIC_RS03170	GO:0007165	signal transduction
TPANIC_RS03170	GO:0006935	chemotaxis
TPANIC_RS03170	GO:0004888	transmembrane signaling receptor activity
TPANIC_RS03170	GO:0005886	plasma membrane
TPANIC_RS03170	GO:0016021	integral component of membrane
TPANIC_RS03175	GO:0005886	plasma membrane
TPANIC_RS03175	GO:0004888	transmembrane signaling receptor activity
TPANIC_RS03175	GO:0007165	signal transduction
TPANIC_RS03175	GO:0016021	integral component of membrane
TPANIC_RS03175	GO:0006935	chemotaxis
TPANIC_RS03180	GO:0005524	ATP binding
TPANIC_RS03180	GO:0004821	histidine-tRNA ligase activity
TPANIC_RS03180	GO:0006427	histidyl-tRNA aminoacylation
TPANIC_RS03180	GO:0005737	cytoplasm
TPANIC_RS03185	GO:0000287	magnesium ion binding
TPANIC_RS03185	GO:0004614	phosphoglucomutase activity
TPANIC_RS03185	GO:0009246	enterobacterial common antigen biosynthetic process
TPANIC_RS03185	GO:0006006	glucose metabolic process
TPANIC_RS03190	GO:0006260	DNA replication
TPANIC_RS03190	GO:0003677	DNA binding
TPANIC_RS03190	GO:0003887	DNA-directed DNA polymerase activity
TPANIC_RS03190	GO:0004527	exonuclease activity
TPANIC_RS03190	GO:0046872	metal ion binding
TPANIC_RS03195	GO:0005524	ATP binding
TPANIC_RS03195	GO:0004824	lysine-tRNA ligase activity
TPANIC_RS03195	GO:0005737	cytoplasm
TPANIC_RS03195	GO:0006430	lysyl-tRNA aminoacylation
TPANIC_RS03195	GO:0000049	tRNA binding
TPANIC_RS03205	GO:0005737	cytoplasm
TPANIC_RS03205	GO:0005524	ATP binding
TPANIC_RS03205	GO:0004828	serine-tRNA ligase activity
TPANIC_RS03205	GO:0016260	selenocysteine biosynthetic process
TPANIC_RS03205	GO:0097056	selenocysteinyl-tRNA(Sec) biosynthetic process
TPANIC_RS03205	GO:0006434	seryl-tRNA aminoacylation
TPANIC_RS03215	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS03215	GO:0090729	toxin activity
TPANIC_RS03215	GO:0044179	hemolysis in other organism
TPANIC_RS03215	GO:0009405	pathogenesis
TPANIC_RS03220	GO:0004521	endoribonuclease activity
TPANIC_RS03220	GO:0005737	cytoplasm
TPANIC_RS03220	GO:0008270	zinc ion binding
TPANIC_RS03220	GO:0006364	rRNA processing
TPANIC_RS03220	GO:0004222	metalloendopeptidase activity
TPANIC_RS03225	GO:0016021	integral component of membrane
TPANIC_RS03225	GO:0005886	plasma membrane
TPANIC_RS03225	GO:0016787	hydrolase activity
TPANIC_RS03225	GO:0046872	metal ion binding
TPANIC_RS03230	GO:0005524	ATP binding
TPANIC_RS03230	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS03230	GO:0015595	ATPase-coupled spermidine transmembrane transporter activity
TPANIC_RS03230	GO:0016887	ATPase activity
TPANIC_RS03230	GO:0015594	ATPase-coupled putrescine transmembrane transporter activity
TPANIC_RS03235	GO:0016021	integral component of membrane
TPANIC_RS03235	GO:0005886	plasma membrane
TPANIC_RS03235	GO:0055085	transmembrane transport
TPANIC_RS03240	GO:0055085	transmembrane transport
TPANIC_RS03240	GO:0016021	integral component of membrane
TPANIC_RS03240	GO:0005886	plasma membrane
TPANIC_RS03245	GO:0005615	extracellular space
TPANIC_RS03245	GO:0019809	spermidine binding
TPANIC_RS03245	GO:0009405	pathogenesis
TPANIC_RS03245	GO:0015846	polyamine transport
TPANIC_RS03245	GO:0042597	periplasmic space
TPANIC_RS03250	GO:0005737	cytoplasm
TPANIC_RS03250	GO:0048027	mRNA 5'-UTR binding
TPANIC_RS03250	GO:0044781	bacterial-type flagellum organization
TPANIC_RS03250	GO:0006402	mRNA catabolic process
TPANIC_RS03250	GO:0045947	negative regulation of translational initiation
TPANIC_RS03250	GO:1902208	regulation of bacterial-type flagellum assembly
TPANIC_RS03250	GO:0006109	regulation of carbohydrate metabolic process
TPANIC_RS03255	GO:0005737	cytoplasm
TPANIC_RS03255	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS03255	GO:0006417	regulation of translation
TPANIC_RS03265	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS03265	GO:0009424	bacterial-type flagellum hook
TPANIC_RS03265	GO:0005576	extracellular region
TPANIC_RS03265	GO:0005829	cytosol
TPANIC_RS03265	GO:0005198	structural molecule activity
TPANIC_RS03275	GO:0006096	glycolytic process
TPANIC_RS03275	GO:0004332	fructose-bisphosphate aldolase activity
TPANIC_RS03275	GO:0008270	zinc ion binding
TPANIC_RS03275	GO:0030388	fructose 1,6-bisphosphate metabolic process
TPANIC_RS03280	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS03280	GO:0055040	periplasmic flagellum
TPANIC_RS03280	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS03300	GO:0005737	cytoplasm
TPANIC_RS03300	GO:0016773	phosphotransferase activity, alcohol group as acceptor
TPANIC_RS03300	GO:0004849	uridine kinase activity
TPANIC_RS03300	GO:0044211	CTP salvage
TPANIC_RS03300	GO:0044206	UMP salvage
TPANIC_RS03300	GO:0005524	ATP binding
TPANIC_RS03315	GO:0005737	cytoplasm
TPANIC_RS03315	GO:0008408	3'-5' exonuclease activity
TPANIC_RS03315	GO:0003887	DNA-directed DNA polymerase activity
TPANIC_RS03315	GO:0006260	DNA replication
TPANIC_RS03330	GO:0046983	protein dimerization activity
TPANIC_RS03330	GO:0004820	glycine-tRNA ligase activity
TPANIC_RS03330	GO:0006426	glycyl-tRNA aminoacylation
TPANIC_RS03330	GO:0005524	ATP binding
TPANIC_RS03330	GO:0005737	cytoplasm
TPANIC_RS03335	GO:0005737	cytoplasm
TPANIC_RS03335	GO:0005524	ATP binding
TPANIC_RS03335	GO:0004818	glutamate-tRNA ligase activity
TPANIC_RS03335	GO:0000049	tRNA binding
TPANIC_RS03335	GO:0008270	zinc ion binding
TPANIC_RS03335	GO:0006424	glutamyl-tRNA aminoacylation
TPANIC_RS03345	GO:0016021	integral component of membrane
TPANIC_RS03370	GO:0016021	integral component of membrane
TPANIC_RS03370	GO:0005886	plasma membrane
TPANIC_RS03375	GO:0005737	cytoplasm
TPANIC_RS03375	GO:0005506	iron ion binding
TPANIC_RS03375	GO:0061711	N(6)-L-threonylcarbamoyladenine synthase activity
TPANIC_RS03375	GO:0002949	tRNA threonylcarbamoyladenosine modification
TPANIC_RS03380	GO:0008784	alanine racemase activity
TPANIC_RS03380	GO:0030170	pyridoxal phosphate binding
TPANIC_RS03380	GO:0030632	D-alanine biosynthetic process
TPANIC_RS03385	GO:0008650	rRNA (uridine-2'-O-)-methyltransferase activity
TPANIC_RS03385	GO:0005737	cytoplasm
TPANIC_RS03390	GO:0004659	prenyltransferase activity
TPANIC_RS03390	GO:0008299	isoprenoid biosynthetic process
TPANIC_RS03390	GO:0005886	plasma membrane
TPANIC_RS03390	GO:0005618	cell wall
TPANIC_RS03395	GO:0008643	carbohydrate transport
TPANIC_RS03395	GO:0005886	plasma membrane
TPANIC_RS03400	GO:0005886	plasma membrane
TPANIC_RS03400	GO:0005524	ATP binding
TPANIC_RS03400	GO:0016887	ATPase activity
TPANIC_RS03400	GO:0043211	ATPase-coupled carbohydrate transmembrane transporter activity
TPANIC_RS03405	GO:0008643	carbohydrate transport
TPANIC_RS03405	GO:0016021	integral component of membrane
TPANIC_RS03405	GO:0005886	plasma membrane
TPANIC_RS03405	GO:0022857	transmembrane transporter activity
TPANIC_RS03410	GO:0003678	DNA helicase activity
TPANIC_RS03410	GO:0006310	DNA recombination
TPANIC_RS03410	GO:0005524	ATP binding
TPANIC_RS03410	GO:0006281	DNA repair
TPANIC_RS03410	GO:0003677	DNA binding
TPANIC_RS03415	GO:0008236	serine-type peptidase activity
TPANIC_RS03415	GO:0004180	carboxypeptidase activity
TPANIC_RS03420	GO:0005525	GTP binding
TPANIC_RS03420	GO:0042254	ribosome biogenesis
TPANIC_RS03430	GO:0005737	cytoplasm
TPANIC_RS03430	GO:0007059	chromosome segregation
TPANIC_RS03430	GO:0006260	DNA replication
TPANIC_RS03430	GO:0051301	cell division
TPANIC_RS03430	GO:0007049	cell cycle
TPANIC_RS03435	GO:0005737	cytoplasm
TPANIC_RS03435	GO:0005524	ATP binding
TPANIC_RS03435	GO:0003684	damaged DNA binding
TPANIC_RS03435	GO:0008094	DNA-dependent ATPase activity
TPANIC_RS03435	GO:0003697	single-stranded DNA binding
TPANIC_RS03435	GO:0006310	DNA recombination
TPANIC_RS03435	GO:0006281	DNA repair
TPANIC_RS03435	GO:0009432	SOS response
TPANIC_RS03445	GO:0005886	plasma membrane
TPANIC_RS03455	GO:0005524	ATP binding
TPANIC_RS03455	GO:0004637	phosphoribosylamine-glycine ligase activity
TPANIC_RS03455	GO:0006189	'de novo' IMP biosynthetic process
TPANIC_RS03455	GO:0009113	purine nucleobase biosynthetic process
TPANIC_RS03455	GO:0046872	metal ion binding
TPANIC_RS03480	GO:0003677	DNA binding
TPANIC_RS03480	GO:0003899	DNA-directed 5'-3' RNA polymerase activity
TPANIC_RS03480	GO:0006351	transcription, DNA-templated
TPANIC_RS03495	GO:0008409	5'-3' exonuclease activity
TPANIC_RS03495	GO:0003677	DNA binding
TPANIC_RS03495	GO:0006310	DNA recombination
TPANIC_RS03495	GO:0006281	DNA repair
TPANIC_RS03500	GO:0046677	response to antibiotic
TPANIC_RS03500	GO:0016021	integral component of membrane
TPANIC_RS03500	GO:0005886	plasma membrane
TPANIC_RS03500	GO:0008144	drug binding
TPANIC_RS03500	GO:0008658	penicillin binding
TPANIC_RS03500	GO:0009002	serine-type D-Ala-D-Ala carboxypeptidase activity
TPANIC_RS03500	GO:0071555	cell wall organization
TPANIC_RS03500	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS03500	GO:0008360	regulation of cell shape
TPANIC_RS03500	GO:0008955	peptidoglycan glycosyltransferase activity
TPANIC_RS03505	GO:0000270	peptidoglycan metabolic process
TPANIC_RS03505	GO:0004222	metalloendopeptidase activity
TPANIC_RS03505	GO:0008933	lytic transglycosylase activity
TPANIC_RS03505	GO:0016829	lyase activity
TPANIC_RS03505	GO:0016020	membrane
TPANIC_RS03510	GO:0016021	integral component of membrane
TPANIC_RS03510	GO:0005886	plasma membrane
TPANIC_RS03515	GO:0016021	integral component of membrane
TPANIC_RS03515	GO:0005886	plasma membrane
TPANIC_RS03520	GO:0003677	DNA binding
TPANIC_RS03520	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS03520	GO:0003899	DNA-directed 5'-3' RNA polymerase activity
TPANIC_RS03520	GO:0016987	sigma factor activity
TPANIC_RS03520	GO:0006352	DNA-templated transcription, initiation
TPANIC_RS03520	GO:0006355	regulation of transcription, DNA-templated
TPANIC_RS03530	GO:0016021	integral component of membrane
TPANIC_RS03535	GO:0009898	cytoplasmic side of plasma membrane
TPANIC_RS03535	GO:0005829	cytosol
TPANIC_RS03535	GO:0005886	plasma membrane
TPANIC_RS03535	GO:0005524	ATP binding
TPANIC_RS03535	GO:0016887	ATPase activity
TPANIC_RS03535	GO:0051782	negative regulation of cell division
TPANIC_RS03540	GO:0005886	plasma membrane
TPANIC_RS03540	GO:0005525	GTP binding
TPANIC_RS03540	GO:0003924	GTPase activity
TPANIC_RS03540	GO:0044781	bacterial-type flagellum organization
TPANIC_RS03540	GO:0006614	SRP-dependent cotranslational protein targeting to membrane
TPANIC_RS03545	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS03545	GO:0016021	integral component of membrane
TPANIC_RS03545	GO:0009306	protein secretion
TPANIC_RS03545	GO:0005886	plasma membrane
TPANIC_RS03550	GO:0009306	protein secretion
TPANIC_RS03550	GO:0016021	integral component of membrane
TPANIC_RS03550	GO:0005886	plasma membrane
TPANIC_RS03550	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS03555	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS03555	GO:0016021	integral component of membrane
TPANIC_RS03555	GO:0005886	plasma membrane
TPANIC_RS03555	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS03555	GO:0006605	protein targeting
TPANIC_RS03560	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS03560	GO:0016021	integral component of membrane
TPANIC_RS03560	GO:0005886	plasma membrane
TPANIC_RS03560	GO:0009306	protein secretion
TPANIC_RS03560	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS03565	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS03565	GO:0005886	plasma membrane
TPANIC_RS03565	GO:0009306	protein secretion
TPANIC_RS03565	GO:0044781	bacterial-type flagellum organization
TPANIC_RS03565	GO:0016021	integral component of membrane
TPANIC_RS03575	GO:0016311	dephosphorylation
TPANIC_RS03575	GO:1902021	regulation of bacterial-type flagellum-dependent cell motility
TPANIC_RS03575	GO:0071978	bacterial-type flagellum-dependent swarming motility
TPANIC_RS03575	GO:0006935	chemotaxis
TPANIC_RS03575	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS03575	GO:0005886	plasma membrane
TPANIC_RS03575	GO:0004721	phosphoprotein phosphatase activity
TPANIC_RS03575	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS03575	GO:0003774	motor activity
TPANIC_RS03580	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS03580	GO:0005886	plasma membrane
TPANIC_RS03580	GO:0003774	motor activity
TPANIC_RS03580	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS03580	GO:0006935	chemotaxis
TPANIC_RS03585	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS03585	GO:0016021	integral component of membrane
TPANIC_RS03585	GO:0005886	plasma membrane
TPANIC_RS03585	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS03585	GO:0006935	chemotaxis
TPANIC_RS03590	GO:0006935	chemotaxis
TPANIC_RS03590	GO:0097588	archaeal or bacterial-type flagellum-dependent cell motility
TPANIC_RS03590	GO:0016021	integral component of membrane
TPANIC_RS03590	GO:0005886	plasma membrane
TPANIC_RS03595	GO:0097588	archaeal or bacterial-type flagellum-dependent cell motility
TPANIC_RS03595	GO:0005886	plasma membrane
TPANIC_RS03595	GO:0006935	chemotaxis
TPANIC_RS03595	GO:0006811	ion transport
TPANIC_RS03595	GO:0016021	integral component of membrane
TPANIC_RS03605	GO:0009425	bacterial-type flagellum basal body
TPANIC_RS03605	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS03610	GO:0009424	bacterial-type flagellum hook
TPANIC_RS03610	GO:0044781	bacterial-type flagellum organization
TPANIC_RS03610	GO:0071978	bacterial-type flagellum-dependent swarming motility
TPANIC_RS03630	GO:0004477	methenyltetrahydrofolate cyclohydrolase activity
TPANIC_RS03630	GO:0004488	methylenetetrahydrofolate dehydrogenase (NADP+) activity
TPANIC_RS03630	GO:0000105	histidine biosynthetic process
TPANIC_RS03630	GO:0009086	methionine biosynthetic process
TPANIC_RS03630	GO:0006164	purine nucleotide biosynthetic process
TPANIC_RS03630	GO:0035999	tetrahydrofolate interconversion
TPANIC_RS03640	GO:0004731	purine-nucleoside phosphorylase activity
TPANIC_RS03640	GO:0009116	nucleoside metabolic process
TPANIC_RS03645	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS03645	GO:0046872	metal ion binding
TPANIC_RS03645	GO:0006537	glutamate biosynthetic process
TPANIC_RS03645	GO:0097054	L-glutamate biosynthetic process
TPANIC_RS03645	GO:0005829	cytosol
TPANIC_RS03645	GO:0004355	glutamate synthase (NADPH) activity
TPANIC_RS03650	GO:0051537	2 iron, 2 sulfur cluster binding
TPANIC_RS03650	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS03650	GO:0046872	metal ion binding
TPANIC_RS03650	GO:0016491	oxidoreductase activity
TPANIC_RS03650	GO:0006221	pyrimidine nucleotide biosynthetic process
TPANIC_RS03660	GO:0005737	cytoplasm
TPANIC_RS03660	GO:0017148	negative regulation of translation
TPANIC_RS03660	GO:0042256	mature ribosome assembly
TPANIC_RS03660	GO:0090071	negative regulation of ribosome biogenesis
TPANIC_RS03675	GO:0005524	ATP binding
TPANIC_RS03675	GO:0004515	nicotinate-nucleotide adenylyltransferase activity
TPANIC_RS03675	GO:0009435	NAD biosynthetic process
TPANIC_RS03680	GO:0005737	cytoplasm
TPANIC_RS03680	GO:0005525	GTP binding
TPANIC_RS03680	GO:0003924	GTPase activity
TPANIC_RS03680	GO:0000287	magnesium ion binding
TPANIC_RS03680	GO:0042254	ribosome biogenesis
TPANIC_RS03685	GO:0006412	translation
TPANIC_RS03685	GO:0003735	structural constituent of ribosome
TPANIC_RS03685	GO:0005840	ribosome
TPANIC_RS03695	GO:0005840	ribosome
TPANIC_RS03695	GO:0019843	rRNA binding
TPANIC_RS03695	GO:0003735	structural constituent of ribosome
TPANIC_RS03695	GO:0006412	translation
TPANIC_RS03700	GO:0005524	ATP binding
TPANIC_RS03700	GO:0016301	kinase activity
TPANIC_RS03700	GO:0046872	metal ion binding
TPANIC_RS03700	GO:0050242	pyruvate, phosphate dikinase activity
TPANIC_RS03700	GO:0006090	pyruvate metabolic process
TPANIC_RS03710	GO:0005737	cytoplasm
TPANIC_RS03725	GO:0042834	peptidoglycan binding
TPANIC_RS03730	GO:0005886	plasma membrane
TPANIC_RS03730	GO:0016021	integral component of membrane
TPANIC_RS03735	GO:0005737	cytoplasm
TPANIC_RS03735	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS03735	GO:0046872	metal ion binding
TPANIC_RS03735	GO:0035596	methylthiotransferase activity
TPANIC_RS03735	GO:0006400	tRNA modification
TPANIC_RS03740	GO:0005737	cytoplasm
TPANIC_RS03740	GO:0016301	kinase activity
TPANIC_RS03740	GO:0016021	integral component of membrane
TPANIC_RS03740	GO:0008965	phosphoenolpyruvate-protein phosphotransferase activity
TPANIC_RS03740	GO:0009401	phosphoenolpyruvate-dependent sugar phosphotransferase system
TPANIC_RS03740	GO:0046872	metal ion binding
TPANIC_RS03740	GO:0008982	protein-N(PI)-phosphohistidine-sugar phosphotransferase activity
TPANIC_RS03745	GO:0004479	methionyl-tRNA formyltransferase activity
TPANIC_RS03750	GO:0046872	metal ion binding
TPANIC_RS03750	GO:0042586	peptide deformylase activity
TPANIC_RS03750	GO:0006412	translation
TPANIC_RS03755	GO:0006412	translation
TPANIC_RS03755	GO:0005840	ribosome
TPANIC_RS03755	GO:0003735	structural constituent of ribosome
TPANIC_RS03760	GO:0005887	integral component of plasma membrane
TPANIC_RS03760	GO:0030435	sporulation resulting in formation of a cellular spore
TPANIC_RS03760	GO:0008360	regulation of cell shape
TPANIC_RS03760	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS03760	GO:0071555	cell wall organization
TPANIC_RS03760	GO:0008658	penicillin binding
TPANIC_RS03760	GO:0009002	serine-type D-Ala-D-Ala carboxypeptidase activity
TPANIC_RS03775	GO:0016021	integral component of membrane
TPANIC_RS03775	GO:0005886	plasma membrane
TPANIC_RS03785	GO:0005886	plasma membrane
TPANIC_RS03785	GO:0005524	ATP binding
TPANIC_RS03785	GO:0004176	ATP-dependent peptidase activity
TPANIC_RS03785	GO:0004222	metalloendopeptidase activity
TPANIC_RS03785	GO:0008270	zinc ion binding
TPANIC_RS03785	GO:0030163	protein catabolic process
TPANIC_RS03785	GO:0016021	integral component of membrane
TPANIC_RS03795	GO:0005737	cytoplasm
TPANIC_RS03795	GO:0005525	GTP binding
TPANIC_RS03795	GO:0003924	GTPase activity
TPANIC_RS03795	GO:0003746	translation elongation factor activity
TPANIC_RS03800	GO:0005886	plasma membrane
TPANIC_RS03810	GO:0006401	RNA catabolic process
TPANIC_RS03810	GO:0005737	cytoplasm
TPANIC_RS03810	GO:0005886	plasma membrane
TPANIC_RS03810	GO:0005524	ATP binding
TPANIC_RS03810	GO:0003723	RNA binding
TPANIC_RS03810	GO:0003724	RNA helicase activity
TPANIC_RS03810	GO:0010501	RNA secondary structure unwinding
TPANIC_RS03815	GO:0016021	integral component of membrane
TPANIC_RS03815	GO:0005886	plasma membrane
TPANIC_RS03815	GO:0005436	sodium:phosphate symporter activity
TPANIC_RS03815	GO:0044341	sodium-dependent phosphate transport
TPANIC_RS03840	GO:0016021	integral component of membrane
TPANIC_RS03840	GO:0005886	plasma membrane
TPANIC_RS03845	GO:0006284	base-excision repair
TPANIC_RS03845	GO:0046872	metal ion binding
TPANIC_RS03845	GO:0003677	DNA binding
TPANIC_RS03845	GO:0019104	DNA N-glycosylase activity
TPANIC_RS03845	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS03845	GO:0140078	class I DNA-(apurinic or apyrimidinic site) endonuclease activity
TPANIC_RS03860	GO:0046081	dUTP catabolic process
TPANIC_RS03860	GO:0046052	UTP catabolic process
TPANIC_RS03860	GO:0046872	metal ion binding
TPANIC_RS03860	GO:0005524	ATP binding
TPANIC_RS03860	GO:0047429	nucleoside-triphosphate diphosphatase activity
TPANIC_RS03860	GO:0009267	cellular response to starvation
TPANIC_RS03860	GO:0046061	dATP catabolic process
TPANIC_RS03860	GO:0006203	dGTP catabolic process
TPANIC_RS03860	GO:0046076	dTTP catabolic process
TPANIC_RS03860	GO:0047693	ATP diphosphatase activity
TPANIC_RS03860	GO:0046047	TTP catabolic process
TPANIC_RS03865	GO:0016021	integral component of membrane
TPANIC_RS03865	GO:0005886	plasma membrane
TPANIC_RS03870	GO:0005524	ATP binding
TPANIC_RS03870	GO:0004359	glutaminase activity
TPANIC_RS03870	GO:0003952	NAD+ synthase (glutamine-hydrolyzing) activity
TPANIC_RS03870	GO:0009435	NAD biosynthetic process
TPANIC_RS03870	GO:0005737	cytoplasm
TPANIC_RS03880	GO:0016021	integral component of membrane
TPANIC_RS03895	GO:0055085	transmembrane transport
TPANIC_RS03895	GO:0015437	lipopolysaccharide floppase activity
TPANIC_RS03895	GO:0016887	ATPase activity
TPANIC_RS03895	GO:0015920	lipopolysaccharide transport
TPANIC_RS03895	GO:1990351	transporter complex
TPANIC_RS03895	GO:0005886	plasma membrane
TPANIC_RS03895	GO:0005524	ATP binding
TPANIC_RS03895	GO:0043190	ATP-binding cassette (ABC) transporter complex
TPANIC_RS03895	GO:0005737	cytoplasm
TPANIC_RS03900	GO:0016021	integral component of membrane
TPANIC_RS03900	GO:0005886	plasma membrane
TPANIC_RS03905	GO:0016021	integral component of membrane
TPANIC_RS03925	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS03925	GO:0055040	periplasmic flagellum
TPANIC_RS03925	GO:0005198	structural molecule activity
TPANIC_RS03925	GO:0009420	bacterial-type flagellum filament
TPANIC_RS03935	GO:0005737	cytoplasm
TPANIC_RS03935	GO:0006556	S-adenosylmethionine biosynthetic process
TPANIC_RS03935	GO:0006730	one-carbon metabolic process
TPANIC_RS03935	GO:0000287	magnesium ion binding
TPANIC_RS03935	GO:0005524	ATP binding
TPANIC_RS03935	GO:0004478	methionine adenosyltransferase activity
TPANIC_RS03940	GO:0005886	plasma membrane
TPANIC_RS03940	GO:0046872	metal ion binding
TPANIC_RS03940	GO:0016740	transferase activity
TPANIC_RS03940	GO:0017013	protein flavinylation
TPANIC_RS03945	GO:0005737	cytoplasm
TPANIC_RS03945	GO:0004735	pyrroline-5-carboxylate reductase activity
TPANIC_RS03945	GO:0055129	L-proline biosynthetic process
TPANIC_RS03950	GO:0005737	cytoplasm
TPANIC_RS03950	GO:0046872	metal ion binding
TPANIC_RS03950	GO:0004825	methionine-tRNA ligase activity
TPANIC_RS03950	GO:0000049	tRNA binding
TPANIC_RS03950	GO:0006431	methionyl-tRNA aminoacylation
TPANIC_RS03950	GO:0005524	ATP binding
TPANIC_RS03960	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS03960	GO:0005886	plasma membrane
TPANIC_RS03960	GO:0004180	carboxypeptidase activity
TPANIC_RS03960	GO:0004175	endopeptidase activity
TPANIC_RS03960	GO:0008658	penicillin binding
TPANIC_RS03960	GO:0009002	serine-type D-Ala-D-Ala carboxypeptidase activity
TPANIC_RS03960	GO:0071555	cell wall organization
TPANIC_RS03960	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS03960	GO:0008360	regulation of cell shape
TPANIC_RS03960	GO:0042493	response to drug
TPANIC_RS03960	GO:0005887	integral component of plasma membrane
TPANIC_RS03965	GO:0016887	ATPase activity
TPANIC_RS03965	GO:0005737	cytoplasm
TPANIC_RS03965	GO:0005829	cytosol
TPANIC_RS03965	GO:0005524	ATP binding
TPANIC_RS03965	GO:0034605	cellular response to heat
TPANIC_RS03965	GO:0043335	protein unfolding
TPANIC_RS03965	GO:0006979	response to oxidative stress
TPANIC_RS03965	GO:0006986	response to unfolded protein
TPANIC_RS03965	GO:0004176	ATP-dependent peptidase activity
TPANIC_RS03980	GO:0055052	ATP-binding cassette (ABC) transporter complex, substrate-binding subunit-containing
TPANIC_RS03980	GO:0005524	ATP binding
TPANIC_RS03980	GO:0016887	ATPase activity
TPANIC_RS03980	GO:0015774	polysaccharide transport
TPANIC_RS03985	GO:0000178	exosome (RNase complex)
TPANIC_RS03985	GO:0000175	3'-5'-exoribonuclease activity
TPANIC_RS03985	GO:0003723	RNA binding
TPANIC_RS03995	GO:0006412	translation
TPANIC_RS03995	GO:0015934	large ribosomal subunit
TPANIC_RS03995	GO:0003735	structural constituent of ribosome
TPANIC_RS04000	GO:0005737	cytoplasm
TPANIC_RS04000	GO:0000036	acyl carrier activity
TPANIC_RS04005	GO:0016075	rRNA catabolic process
TPANIC_RS04005	GO:0008033	tRNA processing
TPANIC_RS04005	GO:0006364	rRNA processing
TPANIC_RS04005	GO:0005737	cytoplasm
TPANIC_RS04005	GO:0006397	mRNA processing
TPANIC_RS04005	GO:0019843	rRNA binding
TPANIC_RS04005	GO:0004525	ribonuclease III activity
TPANIC_RS04005	GO:0046872	metal ion binding
TPANIC_RS04010	GO:0006260	DNA replication
TPANIC_RS04010	GO:0003676	nucleic acid binding
TPANIC_RS04010	GO:0009007	site-specific DNA-methyltransferase (adenine-specific) activity
TPANIC_RS04030	GO:0019430	removal of superoxide radicals
TPANIC_RS04030	GO:0005737	cytoplasm
TPANIC_RS04030	GO:0004791	thioredoxin-disulfide reductase activity
TPANIC_RS04045	GO:0009986	cell surface
TPANIC_RS04045	GO:0005576	extracellular region
TPANIC_RS04045	GO:0000015	phosphopyruvate hydratase complex
TPANIC_RS04045	GO:0000287	magnesium ion binding
TPANIC_RS04045	GO:0004634	phosphopyruvate hydratase activity
TPANIC_RS04045	GO:0006096	glycolytic process
TPANIC_RS04050	GO:0042781	3'-tRNA processing endoribonuclease activity
TPANIC_RS04050	GO:0008270	zinc ion binding
TPANIC_RS04060	GO:0005886	plasma membrane
TPANIC_RS04065	GO:0016021	integral component of membrane
TPANIC_RS04065	GO:0005886	plasma membrane
TPANIC_RS04065	GO:0055085	transmembrane transport
TPANIC_RS04070	GO:0019430	removal of superoxide radicals
TPANIC_RS04070	GO:0034599	cellular response to oxidative stress
TPANIC_RS04070	GO:0009055	electron transfer activity
TPANIC_RS04070	GO:0016721	oxidoreductase activity, acting on superoxide radicals as acceptor
TPANIC_RS04070	GO:0005506	iron ion binding
TPANIC_RS04070	GO:0050605	superoxide reductase activity
TPANIC_RS04075	GO:0000287	magnesium ion binding
TPANIC_RS04075	GO:0030976	thiamine pyrophosphate binding
TPANIC_RS04075	GO:0052865	1-deoxy-D-xylulose 5-phosphate biosynthetic process
TPANIC_RS04075	GO:0016114	terpenoid biosynthetic process
TPANIC_RS04075	GO:0009228	thiamine biosynthetic process
TPANIC_RS04075	GO:0008661	1-deoxy-D-xylulose-5-phosphate synthase activity
TPANIC_RS04085	GO:0016021	integral component of membrane
TPANIC_RS04085	GO:0005886	plasma membrane
TPANIC_RS04085	GO:0019932	second-messenger-mediated signaling
TPANIC_RS04085	GO:0005524	ATP binding
TPANIC_RS04085	GO:0004016	adenylate cyclase activity
TPANIC_RS04085	GO:0016779	nucleotidyltransferase activity
TPANIC_RS04085	GO:0006171	cAMP biosynthetic process
TPANIC_RS04095	GO:0008897	holo-[acyl-carrier-protein] synthase activity
TPANIC_RS04095	GO:0006633	fatty acid biosynthetic process
TPANIC_RS04095	GO:0005737	cytoplasm
TPANIC_RS04095	GO:0000287	magnesium ion binding
TPANIC_RS04105	GO:0003723	RNA binding
TPANIC_RS04105	GO:0106029	tRNA pseudouridine synthase activity
TPANIC_RS04105	GO:0031119	tRNA pseudouridine synthesis
TPANIC_RS04110	GO:0006420	arginyl-tRNA aminoacylation
TPANIC_RS04110	GO:0005737	cytoplasm
TPANIC_RS04110	GO:0005524	ATP binding
TPANIC_RS04110	GO:0004814	arginine-tRNA ligase activity
TPANIC_RS04125	GO:0005737	cytoplasm
TPANIC_RS04125	GO:0005524	ATP binding
TPANIC_RS04125	GO:0003723	RNA binding
TPANIC_RS04125	GO:0004831	tyrosine-tRNA ligase activity
TPANIC_RS04125	GO:0006437	tyrosyl-tRNA aminoacylation
TPANIC_RS04140	GO:0005524	ATP binding
TPANIC_RS04140	GO:0005737	cytoplasm
TPANIC_RS04140	GO:0004829	threonine-tRNA ligase activity
TPANIC_RS04140	GO:0000049	tRNA binding
TPANIC_RS04140	GO:0006435	threonyl-tRNA aminoacylation
TPANIC_RS04140	GO:0046872	metal ion binding
TPANIC_RS04145	GO:0005524	ATP binding
TPANIC_RS04150	GO:0005886	plasma membrane
TPANIC_RS04160	GO:0009266	response to temperature stimulus
TPANIC_RS04160	GO:0006979	response to oxidative stress
TPANIC_RS04160	GO:0009408	response to heat
TPANIC_RS04160	GO:0006508	proteolysis
TPANIC_RS04160	GO:0006515	protein quality control for misfolded or incompletely synthesized proteins
TPANIC_RS04160	GO:0006457	protein folding
TPANIC_RS04160	GO:0061077	chaperone-mediated protein folding
TPANIC_RS04160	GO:0004252	serine-type endopeptidase activity
TPANIC_RS04160	GO:0008233	peptidase activity
TPANIC_RS04160	GO:0042802	identical protein binding
TPANIC_RS04160	GO:0005886	plasma membrane
TPANIC_RS04160	GO:0030288	outer membrane-bounded periplasmic space
TPANIC_RS04160	GO:0008236	serine-type peptidase activity
TPANIC_RS04165	GO:0046872	metal ion binding
TPANIC_RS04165	GO:0070006	metalloaminopeptidase activity
TPANIC_RS04165	GO:0070084	protein initiator methionine removal
TPANIC_RS04170	GO:0005524	ATP binding
TPANIC_RS04170	GO:0031072	heat shock protein binding
TPANIC_RS04170	GO:0051082	unfolded protein binding
TPANIC_RS04170	GO:0008270	zinc ion binding
TPANIC_RS04170	GO:0006260	DNA replication
TPANIC_RS04170	GO:0006457	protein folding
TPANIC_RS04170	GO:0009408	response to heat
TPANIC_RS04170	GO:0005737	cytoplasm
TPANIC_RS04175	GO:0005737	cytoplasm
TPANIC_RS04175	GO:0004365	glyceraldehyde-3-phosphate dehydrogenase (NAD+) (phosphorylating) activity
TPANIC_RS04175	GO:0051287	NAD binding
TPANIC_RS04175	GO:0050661	NADP binding
TPANIC_RS04175	GO:0006006	glucose metabolic process
TPANIC_RS04175	GO:0006096	glycolytic process
TPANIC_RS04195	GO:0006412	translation
TPANIC_RS04195	GO:0000027	ribosomal large subunit assembly
TPANIC_RS04195	GO:0019843	rRNA binding
TPANIC_RS04195	GO:0005840	ribosome
TPANIC_RS04195	GO:0003735	structural constituent of ribosome
TPANIC_RS04200	GO:0005840	ribosome
TPANIC_RS04200	GO:0003735	structural constituent of ribosome
TPANIC_RS04200	GO:0006412	translation
TPANIC_RS04205	GO:0005737	cytoplasm
TPANIC_RS04205	GO:0003743	translation initiation factor activity
TPANIC_RS04215	GO:0005887	integral component of plasma membrane
TPANIC_RS04215	GO:0042158	lipoprotein biosynthetic process
TPANIC_RS04215	GO:0008961	phosphatidylglycerol-prolipoprotein diacylglyceryl transferase activity
TPANIC_RS04220	GO:0009898	cytoplasmic side of plasma membrane
TPANIC_RS04220	GO:0051782	negative regulation of cell division
TPANIC_RS04220	GO:0044781	bacterial-type flagellum organization
TPANIC_RS04220	GO:0005524	ATP binding
TPANIC_RS04220	GO:0005886	plasma membrane
TPANIC_RS04220	GO:0005829	cytosol
TPANIC_RS04220	GO:0016887	ATPase activity
TPANIC_RS04250	GO:0005737	cytoplasm
TPANIC_RS04250	GO:0097367	carbohydrate derivative binding
TPANIC_RS04250	GO:1901137	carbohydrate derivative biosynthetic process
TPANIC_RS04250	GO:0005975	carbohydrate metabolic process
TPANIC_RS04250	GO:0006541	glutamine metabolic process
TPANIC_RS04250	GO:0004360	glutamine-fructose-6-phosphate transaminase (isomerizing) activity
TPANIC_RS04255	GO:0042597	periplasmic space
TPANIC_RS04255	GO:0005528	FK506 binding
TPANIC_RS04255	GO:0042802	identical protein binding
TPANIC_RS04255	GO:0003755	peptidyl-prolyl cis-trans isomerase activity
TPANIC_RS04255	GO:0006457	protein folding
TPANIC_RS04255	GO:0005829	cytosol
TPANIC_RS04260	GO:0006520	cellular amino acid metabolic process
TPANIC_RS04260	GO:0044571	[2Fe-2S] cluster assembly
TPANIC_RS04260	GO:0030170	pyridoxal phosphate binding
TPANIC_RS04260	GO:0046872	metal ion binding
TPANIC_RS04260	GO:0031071	cysteine desulfurase activity
TPANIC_RS04260	GO:0051537	2 iron, 2 sulfur cluster binding
TPANIC_RS04260	GO:0005737	cytoplasm
TPANIC_RS04265	GO:0005576	extracellular region
TPANIC_RS04265	GO:0009986	cell surface
TPANIC_RS04265	GO:0019835	cytolysis
TPANIC_RS04265	GO:0042742	defense response to bacterium
TPANIC_RS04265	GO:0000917	division septum assembly
TPANIC_RS04265	GO:0008152	metabolic process
TPANIC_RS04265	GO:0009405	pathogenesis
TPANIC_RS04265	GO:0008745	N-acetylmuramoyl-L-alanine amidase activity
TPANIC_RS04265	GO:0071555	cell wall organization
TPANIC_RS04285	GO:0009420	bacterial-type flagellum filament
TPANIC_RS04285	GO:0055040	periplasmic flagellum
TPANIC_RS04285	GO:0005198	structural molecule activity
TPANIC_RS04285	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS04295	GO:0009420	bacterial-type flagellum filament
TPANIC_RS04295	GO:0055040	periplasmic flagellum
TPANIC_RS04295	GO:0005198	structural molecule activity
TPANIC_RS04295	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS04300	GO:0009421	bacterial-type flagellum filament cap
TPANIC_RS04300	GO:0009424	bacterial-type flagellum hook
TPANIC_RS04300	GO:0055040	periplasmic flagellum
TPANIC_RS04300	GO:0007155	cell adhesion
TPANIC_RS04300	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS04315	GO:0005737	cytoplasm
TPANIC_RS04315	GO:0005524	ATP binding
TPANIC_RS04315	GO:0046872	metal ion binding
TPANIC_RS04315	GO:0002949	tRNA threonylcarbamoyladenosine modification
TPANIC_RS04320	GO:0005737	cytoplasm
TPANIC_RS04320	GO:0002949	tRNA threonylcarbamoyladenosine modification
TPANIC_RS04325	GO:0007165	signal transduction
TPANIC_RS04325	GO:0016021	integral component of membrane
TPANIC_RS04325	GO:0005886	plasma membrane
TPANIC_RS04325	GO:0016787	hydrolase activity
TPANIC_RS04330	GO:0016021	integral component of membrane
TPANIC_RS04345	GO:0005524	ATP binding
TPANIC_RS04345	GO:0016887	ATPase activity
TPANIC_RS04345	GO:0006814	sodium ion transport
TPANIC_RS04365	GO:0004170	dUTP diphosphatase activity
TPANIC_RS04365	GO:0000287	magnesium ion binding
TPANIC_RS04365	GO:0006226	dUMP biosynthetic process
TPANIC_RS04365	GO:0046081	dUTP catabolic process
TPANIC_RS04370	GO:0005737	cytoplasm
TPANIC_RS04370	GO:0000287	magnesium ion binding
TPANIC_RS04370	GO:0004654	polyribonucleotide nucleotidyltransferase activity
TPANIC_RS04370	GO:0003723	RNA binding
TPANIC_RS04370	GO:0006402	mRNA catabolic process
TPANIC_RS04370	GO:0006396	RNA processing
TPANIC_RS04375	GO:0005840	ribosome
TPANIC_RS04375	GO:0003735	structural constituent of ribosome
TPANIC_RS04375	GO:0006412	translation
TPANIC_RS04375	GO:0019843	rRNA binding
TPANIC_RS04385	GO:0003723	RNA binding
TPANIC_RS04385	GO:0106029	tRNA pseudouridine synthase activity
TPANIC_RS04385	GO:0031119	tRNA pseudouridine synthesis
TPANIC_RS04390	GO:0005737	cytoplasm
TPANIC_RS04390	GO:0030490	maturation of SSU-rRNA
TPANIC_RS04395	GO:0005737	cytoplasm
TPANIC_RS04395	GO:0005525	GTP binding
TPANIC_RS04395	GO:0003924	GTPase activity
TPANIC_RS04395	GO:0003743	translation initiation factor activity
TPANIC_RS04400	GO:0005829	cytosol
TPANIC_RS04400	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS04400	GO:0003723	RNA binding
TPANIC_RS04400	GO:0006353	DNA-templated transcription, termination
TPANIC_RS04400	GO:0031564	transcription antitermination
TPANIC_RS04405	GO:0042274	ribosomal small subunit biogenesis
TPANIC_RS04405	GO:0005737	cytoplasm
TPANIC_RS04425	GO:0005524	ATP binding
TPANIC_RS04425	GO:0003678	DNA helicase activity
TPANIC_RS04425	GO:0003690	double-stranded DNA binding
TPANIC_RS04425	GO:0000724	double-strand break repair via homologous recombination
TPANIC_RS04425	GO:0008408	3'-5' exonuclease activity
TPANIC_RS04435	GO:0006811	ion transport
TPANIC_RS04435	GO:0016021	integral component of membrane
TPANIC_RS04435	GO:0015297	antiporter activity
TPANIC_RS04435	GO:0042910	xenobiotic transmembrane transporter activity
TPANIC_RS04435	GO:0005886	plasma membrane
TPANIC_RS04445	GO:0008360	regulation of cell shape
TPANIC_RS04445	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS04445	GO:0071555	cell wall organization
TPANIC_RS04445	GO:0051301	cell division
TPANIC_RS04445	GO:0008764	UDP-N-acetylmuramoylalanine-D-glutamate ligase activity
TPANIC_RS04445	GO:0005524	ATP binding
TPANIC_RS04445	GO:0005737	cytoplasm
TPANIC_RS04445	GO:0007049	cell cycle
TPANIC_RS04450	GO:0003735	structural constituent of ribosome
TPANIC_RS04450	GO:0006412	translation
TPANIC_RS04450	GO:0005840	ribosome
TPANIC_RS04455	GO:0003723	RNA binding
TPANIC_RS04460	GO:0005840	ribosome
TPANIC_RS04460	GO:0043022	ribosome binding
TPANIC_RS04460	GO:0042274	ribosomal small subunit biogenesis
TPANIC_RS04460	GO:0006364	rRNA processing
TPANIC_RS04460	GO:0005737	cytoplasm
TPANIC_RS04465	GO:0052906	tRNA (guanine(37)-N(1))-methyltransferase activity
TPANIC_RS04465	GO:0005737	cytoplasm
TPANIC_RS04470	GO:0003735	structural constituent of ribosome
TPANIC_RS04470	GO:0006412	translation
TPANIC_RS04470	GO:0005840	ribosome
TPANIC_RS04480	GO:0005886	plasma membrane
TPANIC_RS04480	GO:0009306	protein secretion
TPANIC_RS04485	GO:0071111	cyclic-guanylate-specific phosphodiesterase activity
TPANIC_RS04485	GO:0046872	metal ion binding
TPANIC_RS04485	GO:2000147	positive regulation of cell motility
TPANIC_RS04485	GO:1900231	regulation of single-species biofilm formation on inanimate substrate
TPANIC_RS04490	GO:0004518	nuclease activity
TPANIC_RS04490	GO:0003676	nucleic acid binding
TPANIC_RS04510	GO:0016021	integral component of membrane
TPANIC_RS04510	GO:0005886	plasma membrane
TPANIC_RS04510	GO:0042802	identical protein binding
TPANIC_RS04510	GO:0000287	magnesium ion binding
TPANIC_RS04510	GO:0015095	magnesium ion transmembrane transporter activity
TPANIC_RS04510	GO:0042803	protein homodimerization activity
TPANIC_RS04510	GO:0015693	magnesium ion transport
TPANIC_RS04520	GO:0045454	cell redox homeostasis
TPANIC_RS04520	GO:0015035	protein disulfide oxidoreductase activity
TPANIC_RS04520	GO:0006662	glycerol ether metabolic process
TPANIC_RS04530	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS04530	GO:0008137	NADH dehydrogenase (ubiquinone) activity
TPANIC_RS04530	GO:0045454	cell redox homeostasis
TPANIC_RS04550	GO:0006139	nucleobase-containing compound metabolic process
TPANIC_RS04550	GO:0003735	structural constituent of ribosome
TPANIC_RS04550	GO:0003729	mRNA binding
TPANIC_RS04550	GO:0006412	translation
TPANIC_RS04560	GO:0009055	electron transfer activity
TPANIC_RS04560	GO:0010181	FMN binding
TPANIC_RS04565	GO:0004252	serine-type endopeptidase activity
TPANIC_RS04565	GO:0005886	plasma membrane
TPANIC_RS04565	GO:0016021	integral component of membrane
TPANIC_RS04585	GO:0005991	trehalose metabolic process
TPANIC_RS04585	GO:0004555	alpha,alpha-trehalase activity
TPANIC_RS04585	GO:0016021	integral component of membrane
TPANIC_RS04590	GO:0051301	cell division
TPANIC_RS04590	GO:0008360	regulation of cell shape
TPANIC_RS04590	GO:0071555	cell wall organization
TPANIC_RS04590	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS04590	GO:0005737	cytoplasm
TPANIC_RS04590	GO:0016881	acid-amino acid ligase activity
TPANIC_RS04590	GO:0005524	ATP binding
TPANIC_RS04590	GO:0000287	magnesium ion binding
TPANIC_RS04590	GO:0007049	cell cycle
TPANIC_RS04600	GO:0052689	carboxylic ester hydrolase activity
TPANIC_RS04600	GO:0005576	extracellular region
TPANIC_RS04610	GO:0016021	integral component of membrane
TPANIC_RS04610	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS04610	GO:0005886	plasma membrane
TPANIC_RS04620	GO:0005886	plasma membrane
TPANIC_RS04625	GO:0016903	oxidoreductase activity, acting on the aldehyde or oxo group of donors
TPANIC_RS04625	GO:0030976	thiamine pyrophosphate binding
TPANIC_RS04625	GO:0022900	electron transport chain
TPANIC_RS04625	GO:0009399	nitrogen fixation
TPANIC_RS04625	GO:0005506	iron ion binding
TPANIC_RS04625	GO:0051539	4 iron, 4 sulfur cluster binding
TPANIC_RS04635	GO:0044780	bacterial-type flagellum assembly
TPANIC_RS04650	GO:0019323	pentose catabolic process
TPANIC_RS04650	GO:0046872	metal ion binding
TPANIC_RS04650	GO:0006098	pentose-phosphate shunt
TPANIC_RS04650	GO:0004750	ribulose-phosphate 3-epimerase activity
TPANIC_RS04655	GO:0005737	cytoplasm
TPANIC_RS04655	GO:0070043	rRNA (guanine-N7-)-methyltransferase activity
TPANIC_RS04660	GO:0003755	peptidyl-prolyl cis-trans isomerase activity
TPANIC_RS04660	GO:0006457	protein folding
TPANIC_RS04665	GO:0003723	RNA binding
TPANIC_RS04670	GO:0016021	integral component of membrane
TPANIC_RS04670	GO:0015031	protein transport
TPANIC_RS04670	GO:0032977	membrane insertase activity
TPANIC_RS04670	GO:0005886	plasma membrane
TPANIC_RS04675	GO:0005886	plasma membrane
TPANIC_RS04680	GO:0004526	ribonuclease P activity
TPANIC_RS04680	GO:0000049	tRNA binding
TPANIC_RS04680	GO:0001682	tRNA 5'-leader removal
TPANIC_RS04720	GO:0016021	integral component of membrane
TPANIC_RS04720	GO:0046306	alkanesulfonate catabolic process
TPANIC_RS04720	GO:0005886	plasma membrane
TPANIC_RS04730	GO:0071973	bacterial-type flagellum-dependent cell motility
TPANIC_RS04730	GO:0009426	bacterial-type flagellum basal body, distal rod
TPANIC_RS04735	GO:0071978	bacterial-type flagellum-dependent swarming motility
TPANIC_RS04735	GO:0009424	bacterial-type flagellum hook
TPANIC_RS04735	GO:0009426	bacterial-type flagellum basal body, distal rod
TPANIC_RS04740	GO:0015562	efflux transmembrane transporter activity
TPANIC_RS04740	GO:0005887	integral component of plasma membrane
TPANIC_RS04740	GO:0046677	response to antibiotic
TPANIC_RS04740	GO:0008559	ATPase-coupled xenobiotic transmembrane transporter activity
TPANIC_RS04740	GO:0016887	ATPase activity
TPANIC_RS04740	GO:0005524	ATP binding
TPANIC_RS04740	GO:1990961	xenobiotic detoxification by transmembrane export across the plasma membrane
TPANIC_RS04745	GO:0005524	ATP binding
TPANIC_RS04745	GO:0008559	ATPase-coupled xenobiotic transmembrane transporter activity
TPANIC_RS04745	GO:0015562	efflux transmembrane transporter activity
TPANIC_RS04745	GO:0046677	response to antibiotic
TPANIC_RS04745	GO:1990961	xenobiotic detoxification by transmembrane export across the plasma membrane
TPANIC_RS04745	GO:0016887	ATPase activity
TPANIC_RS04745	GO:0005887	integral component of plasma membrane
TPANIC_RS04750	GO:0005886	plasma membrane
TPANIC_RS04750	GO:0005524	ATP binding
TPANIC_RS04750	GO:0016887	ATPase activity
TPANIC_RS04750	GO:0022857	transmembrane transporter activity
TPANIC_RS04750	GO:0055085	transmembrane transport
TPANIC_RS04755	GO:1990281	efflux pump complex
TPANIC_RS04755	GO:0015562	efflux transmembrane transporter activity
TPANIC_RS04755	GO:0042910	xenobiotic transmembrane transporter activity
TPANIC_RS04780	GO:0005886	plasma membrane
TPANIC_RS04785	GO:0005886	plasma membrane
TPANIC_RS04785	GO:0033573	high-affinity iron permease complex
TPANIC_RS04785	GO:0015093	ferrous iron transmembrane transporter activity
TPANIC_RS04785	GO:0034755	iron ion transmembrane transport
TPANIC_RS04785	GO:0055072	iron ion homeostasis
TPANIC_RS04790	GO:0005737	cytoplasm
TPANIC_RS04790	GO:0005524	ATP binding
TPANIC_RS04790	GO:0000287	magnesium ion binding
TPANIC_RS04790	GO:0004826	phenylalanine-tRNA ligase activity
TPANIC_RS04790	GO:0000049	tRNA binding
TPANIC_RS04790	GO:0006432	phenylalanyl-tRNA aminoacylation
TPANIC_RS04800	GO:0000453	enzyme-directed rRNA 2'-O-methylation
TPANIC_RS04800	GO:0005737	cytoplasm
TPANIC_RS04800	GO:0070677	rRNA (cytosine-2'-O-)-methyltransferase activity
TPANIC_RS04805	GO:0016021	integral component of membrane
TPANIC_RS04805	GO:0005886	plasma membrane
TPANIC_RS04810	GO:0046872	metal ion binding
TPANIC_RS04815	GO:0005886	plasma membrane
TPANIC_RS04815	GO:0004190	aspartic-type endopeptidase activity
TPANIC_RS04815	GO:0016021	integral component of membrane
TPANIC_RS04820	GO:0005829	cytosol
TPANIC_RS04820	GO:0016888	endodeoxyribonuclease activity, producing 5'-phosphomonoesters
TPANIC_RS04820	GO:0046872	metal ion binding
TPANIC_RS04825	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS04825	GO:0017150	tRNA dihydrouridine synthase activity
TPANIC_RS04825	GO:0000049	tRNA binding
TPANIC_RS04830	GO:0052621	diguanylate cyclase activity
TPANIC_RS04830	GO:0000160	phosphorelay signal transduction system
TPANIC_RS04830	GO:0005737	cytoplasm
TPANIC_RS04830	GO:0030154	cell differentiation
TPANIC_RS04830	GO:0005525	GTP binding
TPANIC_RS04830	GO:0046872	metal ion binding
TPANIC_RS04830	GO:0007049	cell cycle
TPANIC_RS04845	GO:0005737	cytoplasm
TPANIC_RS04845	GO:0005524	ATP binding
TPANIC_RS04845	GO:0051082	unfolded protein binding
TPANIC_RS04845	GO:0006457	protein folding
TPANIC_RS04850	GO:0005524	ATP binding
TPANIC_RS04850	GO:0006422	aspartyl-tRNA aminoacylation
TPANIC_RS04850	GO:0003676	nucleic acid binding
TPANIC_RS04850	GO:0050560	aspartate-tRNA(Asn) ligase activity
TPANIC_RS04850	GO:0004815	aspartate-tRNA ligase activity
TPANIC_RS04850	GO:0005737	cytoplasm
TPANIC_RS04855	GO:0016021	integral component of membrane
TPANIC_RS04855	GO:0005886	plasma membrane
TPANIC_RS04865	GO:0016021	integral component of membrane
TPANIC_RS04865	GO:0005886	plasma membrane
TPANIC_RS04880	GO:0005506	iron ion binding
TPANIC_RS04880	GO:0009055	electron transfer activity
TPANIC_RS04890	GO:0016829	lyase activity
TPANIC_RS04890	GO:0071555	cell wall organization
TPANIC_RS04890	GO:0008932	lytic endotransglycosylase activity
TPANIC_RS04890	GO:0000270	peptidoglycan metabolic process
TPANIC_RS04900	GO:0005829	cytosol
TPANIC_RS04900	GO:0016888	endodeoxyribonuclease activity, producing 5'-phosphomonoesters
TPANIC_RS04900	GO:0046872	metal ion binding
TPANIC_RS04920	GO:0016021	integral component of membrane
TPANIC_RS04920	GO:0005886	plasma membrane
TPANIC_RS04920	GO:0008236	serine-type peptidase activity
TPANIC_RS04920	GO:0006465	signal peptide processing
TPANIC_RS04925	GO:0015655	alanine:sodium symporter activity
TPANIC_RS04925	GO:0016021	integral component of membrane
TPANIC_RS04925	GO:0005886	plasma membrane
TPANIC_RS04930	GO:0051301	cell division
TPANIC_RS04930	GO:0016021	integral component of membrane
TPANIC_RS04930	GO:0007059	chromosome segregation
TPANIC_RS04930	GO:0005886	plasma membrane
TPANIC_RS04930	GO:0005524	ATP binding
TPANIC_RS04930	GO:0003677	DNA binding
TPANIC_RS04930	GO:0007049	cell cycle
TPANIC_RS04950	GO:0016021	integral component of membrane
TPANIC_RS04950	GO:0005886	plasma membrane
TPANIC_RS04955	GO:0003677	DNA binding
TPANIC_RS04955	GO:0046872	metal ion binding
TPANIC_RS04955	GO:0006310	DNA recombination
TPANIC_RS04955	GO:0006281	DNA repair
TPANIC_RS04960	GO:0006261	DNA-dependent DNA replication
TPANIC_RS04960	GO:0003887	DNA-directed DNA polymerase activity
TPANIC_RS04960	GO:0003677	DNA binding
TPANIC_RS04960	GO:0009360	DNA polymerase III complex
TPANIC_RS04960	GO:0005524	ATP binding
TPANIC_RS04965	GO:0006265	DNA topological change
TPANIC_RS04965	GO:0046872	metal ion binding
TPANIC_RS04965	GO:0003918	DNA topoisomerase type II (double strand cut, ATP-hydrolyzing) activity
TPANIC_RS04965	GO:0006261	DNA-dependent DNA replication
TPANIC_RS04965	GO:0005524	ATP binding
TPANIC_RS04965	GO:0005737	cytoplasm
TPANIC_RS04965	GO:0005694	chromosome
TPANIC_RS04965	GO:0003677	DNA binding
TPANIC_RS04970	GO:0050660	flavin adenine dinucleotide binding
TPANIC_RS04970	GO:0050797	thymidylate synthase (FAD) activity
TPANIC_RS04970	GO:0006231	dTMP biosynthetic process
TPANIC_RS04970	GO:0006235	dTTP biosynthetic process
TPANIC_RS04970	GO:0032259	methylation
TPANIC_RS04975	GO:0004748	ribonucleoside-diphosphate reductase activity, thioredoxin disulfide as acceptor
TPANIC_RS04975	GO:0005524	ATP binding
TPANIC_RS04975	GO:0006260	DNA replication
TPANIC_RS04980	GO:0005975	carbohydrate metabolic process
TPANIC_RS04980	GO:0004367	glycerol-3-phosphate dehydrogenase [NAD+] activity
TPANIC_RS04980	GO:0051287	NAD binding
TPANIC_RS04980	GO:0046167	glycerol-3-phosphate biosynthetic process
TPANIC_RS04980	GO:0046168	glycerol-3-phosphate catabolic process
TPANIC_RS04980	GO:0006650	glycerophospholipid metabolic process
TPANIC_RS04980	GO:0008654	phospholipid biosynthetic process
TPANIC_RS04980	GO:0009331	glycerol-3-phosphate dehydrogenase complex
TPANIC_RS04985	GO:0006228	UTP biosynthetic process
TPANIC_RS04985	GO:0006183	GTP biosynthetic process
TPANIC_RS04985	GO:0006241	CTP biosynthetic process
TPANIC_RS04985	GO:0046872	metal ion binding
TPANIC_RS04985	GO:0005524	ATP binding
TPANIC_RS04985	GO:0005737	cytoplasm
TPANIC_RS04985	GO:0004550	nucleoside diphosphate kinase activity
TPANIC_RS04990	GO:0005737	cytoplasm
TPANIC_RS04990	GO:0004045	aminoacyl-tRNA hydrolase activity
TPANIC_RS04990	GO:0006412	translation
TPANIC_RS04995	GO:0016987	sigma factor activity
TPANIC_RS04995	GO:0005737	cytoplasm
TPANIC_RS04995	GO:0003700	DNA-binding transcription factor activity
TPANIC_RS04995	GO:0001123	transcription initiation from bacterial-type RNA polymerase promoter
TPANIC_RS04995	GO:0003677	DNA binding
TPANIC_RS05000	GO:0005737	cytoplasm
TPANIC_RS05000	GO:0005524	ATP binding
TPANIC_RS05000	GO:0006457	protein folding
TPANIC_RS05005	GO:0016021	integral component of membrane
TPANIC_RS05010	GO:0006353	DNA-templated transcription, termination
TPANIC_RS05010	GO:0031564	transcription antitermination
TPANIC_RS05010	GO:0003723	RNA binding
TPANIC_RS05015	GO:0003755	peptidyl-prolyl cis-trans isomerase activity
TPANIC_RS05015	GO:0005886	plasma membrane
TPANIC_RS05020	GO:0005737	cytoplasm
TPANIC_RS05020	GO:0004813	alanine-tRNA ligase activity
TPANIC_RS05020	GO:0005524	ATP binding
TPANIC_RS05020	GO:0008270	zinc ion binding
TPANIC_RS05020	GO:0006419	alanyl-tRNA aminoacylation
TPANIC_RS05020	GO:0000049	tRNA binding
TPANIC_RS05030	GO:0006402	mRNA catabolic process
TPANIC_RS05030	GO:0016021	integral component of membrane
TPANIC_RS05030	GO:0003723	RNA binding
TPANIC_RS05030	GO:0005886	plasma membrane
TPANIC_RS05030	GO:0004521	endoribonuclease activity
TPANIC_RS05035	GO:0005524	ATP binding
TPANIC_RS05035	GO:0016874	ligase activity
TPANIC_RS05035	GO:0006412	translation
TPANIC_RS05040	GO:0030956	glutamyl-tRNA(Gln) amidotransferase complex
TPANIC_RS05040	GO:0050567	glutaminyl-tRNA synthase (glutamine-hydrolyzing) activity
TPANIC_RS05040	GO:0016787	hydrolase activity
TPANIC_RS05040	GO:0006412	translation
TPANIC_RS05040	GO:0005524	ATP binding
TPANIC_RS05045	GO:0005524	ATP binding
TPANIC_RS05045	GO:0050567	glutaminyl-tRNA synthase (glutamine-hydrolyzing) activity
TPANIC_RS05045	GO:0006412	translation
TPANIC_RS05050	GO:0000725	recombinational repair
TPANIC_RS05050	GO:0005524	ATP binding
TPANIC_RS05050	GO:0003684	damaged DNA binding
TPANIC_RS05050	GO:0008094	DNA-dependent ATPase activity
TPANIC_RS05050	GO:0046872	metal ion binding
TPANIC_RS05055	GO:0006282	regulation of DNA repair
TPANIC_RS05055	GO:0005737	cytoplasm
TPANIC_RS05060	GO:0005840	ribosome
TPANIC_RS05060	GO:0003735	structural constituent of ribosome
TPANIC_RS05060	GO:0006412	translation
TPANIC_RS05065	GO:0006412	translation
TPANIC_RS05065	GO:0003735	structural constituent of ribosome
TPANIC_RS05065	GO:0005840	ribosome
TPANIC_RS05080	GO:0004850	uridine phosphorylase activity
TPANIC_RS05080	GO:0009116	nucleoside metabolic process
TPANIC_RS05080	GO:0009166	nucleotide catabolic process
TPANIC_RS05080	GO:0044206	UMP salvage
TPANIC_RS05080	GO:0005737	cytoplasm
TPANIC_RS05085	GO:0003677	DNA binding
TPANIC_RS05085	GO:0005524	ATP binding
TPANIC_RS05085	GO:0006268	DNA unwinding involved in DNA replication
TPANIC_RS05085	GO:0005737	cytoplasm
TPANIC_RS05085	GO:0003678	DNA helicase activity
TPANIC_RS05100	GO:0016021	integral component of membrane
TPANIC_RS05105	GO:0004622	lysophospholipase activity
TPANIC_RS05105	GO:0016042	lipid catabolic process
TPANIC_RS05105	GO:0046470	phosphatidylcholine metabolic process
TPANIC_RS05110	GO:0008273	calcium, potassium:sodium antiporter activity
TPANIC_RS05110	GO:0005262	calcium channel activity
TPANIC_RS05110	GO:0005886	plasma membrane
TPANIC_RS05110	GO:0005887	integral component of plasma membrane
TPANIC_RS05110	GO:0070588	calcium ion transmembrane transport
TPANIC_RS05110	GO:0006874	cellular calcium ion homeostasis
TPANIC_RS05115	GO:0002161	aminoacyl-tRNA editing activity
TPANIC_RS05115	GO:0004832	valine-tRNA ligase activity
TPANIC_RS05115	GO:0005737	cytoplasm
TPANIC_RS05115	GO:0006438	valyl-tRNA aminoacylation
TPANIC_RS05115	GO:0005524	ATP binding
TPANIC_RS05120	GO:0016021	integral component of membrane
TPANIC_RS05120	GO:0005886	plasma membrane
TPANIC_RS05120	GO:0005524	ATP binding
TPANIC_RS05120	GO:0005507	copper ion binding
TPANIC_RS05120	GO:0043682	copper transmembrane transporter activity, phosphorylative mechanism
TPANIC_RS05125	GO:0016021	integral component of membrane
TPANIC_RS05125	GO:0019835	cytolysis
TPANIC_RS05125	GO:0005886	plasma membrane
TPANIC_RS05130	GO:0016722	oxidoreductase activity, oxidizing metal ions
TPANIC_RS05130	GO:0008199	ferric iron binding
TPANIC_RS05135	GO:0006166	purine ribonucleoside salvage
TPANIC_RS05135	GO:0005737	cytoplasm
TPANIC_RS05135	GO:0003999	adenine phosphoribosyltransferase activity
TPANIC_RS05135	GO:0006168	adenine salvage
TPANIC_RS05135	GO:0044209	AMP salvage
TPANIC_RS05140	GO:0016880	acid-ammonia (or amide) ligase activity
TPANIC_RS05140	GO:0071915	protein-lysine lysylation
TPANIC_RS05140	GO:0006430	lysyl-tRNA aminoacylation
TPANIC_RS05140	GO:0004824	lysine-tRNA ligase activity
TPANIC_RS05140	GO:0005524	ATP binding
TPANIC_RS05140	GO:0005737	cytoplasm
TPANIC_RS05145	GO:0005737	cytoplasm
TPANIC_RS05145	GO:0004252	serine-type endopeptidase activity
TPANIC_RS05145	GO:0004176	ATP-dependent peptidase activity
TPANIC_RS05225	GO:0019843	rRNA binding
TPANIC_RS05225	GO:0005840	ribosome
TPANIC_RS05225	GO:0003735	structural constituent of ribosome
TPANIC_RS05225	GO:0008270	zinc ion binding
TPANIC_RS05225	GO:0006412	translation
TPANIC_RS05230	GO:0005840	ribosome
TPANIC_RS05230	GO:0006412	translation
TPANIC_RS05230	GO:0003735	structural constituent of ribosome
TPANIC_RS05230	GO:0019843	rRNA binding
TPANIC_RS05245	GO:0035999	tetrahydrofolate interconversion
TPANIC_RS05245	GO:0019264	glycine biosynthetic process from serine
TPANIC_RS05245	GO:0030170	pyridoxal phosphate binding
TPANIC_RS05245	GO:0004372	glycine hydroxymethyltransferase activity
TPANIC_RS05245	GO:0005737	cytoplasm
TPANIC_RS05265	GO:0006412	translation
TPANIC_RS05265	GO:0005840	ribosome
TPANIC_RS05265	GO:0003735	structural constituent of ribosome
TPANIC_RS05335	GO:0005524	ATP binding
TPANIC_RS05335	GO:0008360	regulation of cell shape
TPANIC_RS05335	GO:0009252	peptidoglycan biosynthetic process
TPANIC_RS05335	GO:0071555	cell wall organization
TPANIC_RS05335	GO:0046872	metal ion binding
TPANIC_RS05335	GO:0005737	cytoplasm
TPANIC_RS05335	GO:0008716	D-alanine-D-alanine ligase activity
TPANIC_RS05350	GO:0004252	serine-type endopeptidase activity
TPANIC_RS05350	GO:0042597	periplasmic space
TPANIC_RS05380	GO:0005840	ribosome
TPANIC_RS05380	GO:0003735	structural constituent of ribosome
TPANIC_RS05380	GO:0006412	translation
TPANIC_RS05430	GO:0005886	plasma membrane
TPANIC_RS05430	GO:0016021	integral component of membrane
TPANIC_RS05460	GO:0016021	integral component of membrane
TPANIC_RS05460	GO:0005886	plasma membrane
TPANIC_RS05485	GO:0071586	CAAX-box protein processing
TPANIC_RS05485	GO:0004222	metalloendopeptidase activity
TPANIC_RS05485	GO:0016021	integral component of membrane
TPANIC_RS05485	GO:0005886	plasma membrane
TPANIC_RS05500	GO:0009279	cell outer membrane
TPANIC_RS05505	GO:0016021	integral component of membrane
