ML0001	GO:0003677	DNA binding
ML0001	GO:0003688	DNA replication origin binding
ML0001	GO:0005524	ATP binding
ML0001	GO:0006270	DNA replication initiation
ML0001	GO:0006275	regulation of DNA replication
ML0001	GO:0043565	sequence-specific DNA binding
ML0002	GO:0003677	DNA binding
ML0002	GO:0003887	DNA-directed DNA polymerase activity
ML0002	GO:0006260	DNA replication
ML0002	GO:0008408	3'-5' exonuclease activity
ML0002	GO:0009360	DNA polymerase III complex
ML0003	GO:0003697	single-stranded DNA binding
ML0003	GO:0005524	ATP binding
ML0003	GO:0006281	DNA repair
ML0005	GO:0003677	DNA binding
ML0005	GO:0003918	DNA topoisomerase type II (ATP-hydrolyzing) activity
ML0005	GO:0005524	ATP binding
ML0005	GO:0005694	chromosome
ML0005	GO:0006265	DNA topological change
ML0006	GO:0003677	DNA binding
ML0006	GO:0003916	DNA topoisomerase activity
ML0006	GO:0003918	DNA topoisomerase type II (ATP-hydrolyzing) activity
ML0006	GO:0004519	endonuclease activity
ML0006	GO:0005524	ATP binding
ML0006	GO:0005694	chromosome
ML0006	GO:0006259	DNA metabolic process
ML0006	GO:0006265	DNA topological change
ML0006	GO:0016539	intein-mediated protein splicing
ML0011	GO:0000413	protein peptidyl-prolyl isomerization
ML0011	GO:0003755	peptidyl-prolyl cis-trans isomerase activity
ML0011	GO:0006457	protein folding
ML0015	GO:0008152	metabolic process
ML0016	GO:0004672	protein kinase activity
ML0016	GO:0005524	ATP binding
ML0016	GO:0006468	protein phosphorylation
ML0017	GO:0004672	protein kinase activity
ML0017	GO:0005524	ATP binding
ML0017	GO:0006468	protein phosphorylation
ML0018	GO:0008658	penicillin binding
ML0019	GO:0007049	cell cycle
ML0019	GO:0016021	integral component of membrane
ML0019	GO:0051301	cell division
ML0020	GO:0003824	catalytic activity
ML0021	GO:0005515	protein binding
ML0022	GO:0005515	protein binding
ML0032	GO:0000166	nucleotide binding
ML0032	GO:0002161	aminoacyl-tRNA editing activity
ML0032	GO:0004812	aminoacyl-tRNA ligase activity
ML0032	GO:0004823	leucine-tRNA ligase activity
ML0032	GO:0005524	ATP binding
ML0032	GO:0006418	tRNA aminoacylation for protein translation
ML0032	GO:0006429	leucyl-tRNA aminoacylation
ML0041	GO:0004252	serine-type endopeptidase activity
ML0041	GO:0006508	proteolysis
ML0052	GO:0000166	nucleotide binding
ML0052	GO:0003677	DNA binding
ML0052	GO:0005524	ATP binding
ML0053	GO:0000166	nucleotide binding
ML0053	GO:0003677	DNA binding
ML0053	GO:0005524	ATP binding
ML0055	GO:0005524	ATP binding
ML0061	GO:0003824	catalytic activity
ML0061	GO:0006537	glutamate biosynthetic process
ML0061	GO:0006807	nitrogen compound metabolic process
ML0061	GO:0008152	metabolic process
ML0061	GO:0015930	glutamate synthase activity
ML0061	GO:0016491	oxidoreductase activity
ML0061	GO:0016638	oxidoreductase activity, acting on the CH-NH2 group of donors
ML0061	GO:0055114	oxidation-reduction process
ML0062	GO:0006537	glutamate biosynthetic process
ML0062	GO:0016491	oxidoreductase activity
ML0062	GO:0016639	oxidoreductase activity, acting on the CH-NH2 group of donors, NAD or NADP as acceptor
ML0062	GO:0051536	iron-sulfur cluster binding
ML0062	GO:0055114	oxidation-reduction process
ML0064	GO:0003677	DNA binding
ML0065	GO:0004499	N,N-dimethylaniline monooxygenase activity
ML0065	GO:0016491	oxidoreductase activity
ML0065	GO:0050660	flavin adenine dinucleotide binding
ML0065	GO:0050661	NADP binding
ML0065	GO:0055114	oxidation-reduction process
ML0066	GO:0008428	ribonuclease inhibitor activity
ML0066	GO:0051252	regulation of RNA metabolic process
ML0069	GO:0003677	DNA binding
ML0072	GO:0004784	superoxide dismutase activity
ML0072	GO:0006801	superoxide metabolic process
ML0072	GO:0046872	metal ion binding
ML0072	GO:0055114	oxidation-reduction process
ML0074	GO:0006629	lipid metabolic process
ML0074	GO:0008081	phosphoric diester hydrolase activity
ML0078	GO:0004106	chorismate mutase activity
ML0078	GO:0004664	prephenate dehydratase activity
ML0078	GO:0005737	cytoplasm
ML0078	GO:0008152	metabolic process
ML0078	GO:0009094	L-phenylalanine biosynthetic process
ML0078	GO:0016597	amino acid binding
ML0082	GO:0000166	nucleotide binding
ML0082	GO:0004812	aminoacyl-tRNA ligase activity
ML0082	GO:0004828	serine-tRNA ligase activity
ML0082	GO:0005524	ATP binding
ML0082	GO:0005737	cytoplasm
ML0082	GO:0006418	tRNA aminoacylation for protein translation
ML0082	GO:0006434	seryl-tRNA aminoacylation
ML0087	GO:0008152	metabolic process
ML0087	GO:0016746	transferase activity, transferring acyl groups
ML0088	GO:0008152	metabolic process
ML0088	GO:0016746	transferase activity, transferring acyl groups
ML0089	GO:0016787	hydrolase activity
ML0092	GO:0008767	UDP-galactopyranose mutase activity
ML0095	GO:0004659	prenyltransferase activity
ML0095	GO:0016021	integral component of membrane
ML0099	GO:0008152	metabolic process
ML0099	GO:0016787	hydrolase activity
ML0100	GO:0003824	catalytic activity
ML0100	GO:0008152	metabolic process
ML0101	GO:0003824	catalytic activity
ML0101	GO:0008152	metabolic process
ML0101	GO:0009058	biosynthetic process
ML0101	GO:0016740	transferase activity
ML0101	GO:0016788	hydrolase activity, acting on ester bonds
ML0101	GO:0031177	phosphopantetheine binding
ML0104	GO:0052636	arabinosyltransferase activity
ML0104	GO:0071766	Actinobacterium-type cell wall biogenesis
ML0105	GO:0052636	arabinosyltransferase activity
ML0105	GO:0071766	Actinobacterium-type cell wall biogenesis
ML0106	GO:0052636	arabinosyltransferase activity
ML0106	GO:0071766	Actinobacterium-type cell wall biogenesis
ML0107	GO:0005886	plasma membrane
ML0107	GO:0016021	integral component of membrane
ML0107	GO:0016757	transferase activity, transferring glycosyl groups
ML0107	GO:0044038	cell wall macromolecule biosynthetic process
ML0108	GO:0016491	oxidoreductase activity
ML0109	GO:0003824	catalytic activity
ML0109	GO:0003885	D-arabinono-1,4-lactone oxidase activity
ML0109	GO:0016020	membrane
ML0109	GO:0016491	oxidoreductase activity
ML0109	GO:0016614	oxidoreductase activity, acting on CH-OH group of donors
ML0109	GO:0050660	flavin adenine dinucleotide binding
ML0109	GO:0055114	oxidation-reduction process
ML0110	GO:0000271	polysaccharide biosynthetic process
ML0110	GO:0006810	transport
ML0110	GO:0016021	integral component of membrane
ML0112	GO:0016020	membrane
ML0114	GO:0005524	ATP binding
ML0114	GO:0016887	ATPase activity
ML0115	GO:0061136	regulation of proteasomal protein catabolic process
ML0117	GO:0003824	catalytic activity
ML0118	GO:0016491	oxidoreductase activity
ML0118	GO:0055114	oxidation-reduction process
ML0120	GO:0003824	catalytic activity
ML0120	GO:0008152	metabolic process
ML0125	GO:0008152	metabolic process
ML0125	GO:0016758	transferase activity, transferring hexosyl groups
ML0127	GO:0008168	methyltransferase activity
ML0127	GO:0008610	lipid biosynthetic process
ML0128	GO:0008152	metabolic process
ML0128	GO:0016758	transferase activity, transferring hexosyl groups
ML0129	GO:0016491	oxidoreductase activity
ML0129	GO:0055114	oxidation-reduction process
ML0130	GO:0008152	metabolic process
ML0130	GO:0008168	methyltransferase activity
ML0131	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML0131	GO:0055114	oxidation-reduction process
ML0132	GO:0003824	catalytic activity
ML0132	GO:0008152	metabolic process
ML0134	GO:0003824	catalytic activity
ML0134	GO:0008152	metabolic process
ML0134	GO:0031177	phosphopantetheine binding
ML0135	GO:0003824	catalytic activity
ML0135	GO:0008152	metabolic process
ML0135	GO:0016491	oxidoreductase activity
ML0135	GO:0016740	transferase activity
ML0135	GO:0031177	phosphopantetheine binding
ML0135	GO:0048037	cofactor binding
ML0135	GO:0055114	oxidation-reduction process
ML0137	GO:0016020	membrane
ML0138	GO:0003824	catalytic activity
ML0138	GO:0008152	metabolic process
ML0139	GO:0003824	catalytic activity
ML0139	GO:0008152	metabolic process
ML0139	GO:0016491	oxidoreductase activity
ML0139	GO:0016740	transferase activity
ML0139	GO:0031177	phosphopantetheine binding
ML0139	GO:0055114	oxidation-reduction process
ML0150	GO:0004347	glucose-6-phosphate isomerase activity
ML0150	GO:0006094	gluconeogenesis
ML0150	GO:0006096	glycolytic process
ML0151	GO:0046417	chorismate metabolic process
ML0153	GO:0005524	ATP binding
ML0153	GO:0016787	hydrolase activity
ML0155	GO:0003824	catalytic activity
ML0155	GO:0005524	ATP binding
ML0155	GO:0008152	metabolic process
ML0156	GO:0003824	catalytic activity
ML0156	GO:0008152	metabolic process
ML0156	GO:0048037	cofactor binding
ML0160	GO:0004644	phosphoribosylglycinamide formyltransferase activity
ML0160	GO:0006189	'de novo' IMP biosynthetic process
ML0160	GO:0009058	biosynthetic process
ML0160	GO:0016742	hydroxymethyl-, formyl- and related transferase activity
ML0161	GO:0003824	catalytic activity
ML0161	GO:0003937	IMP cyclohydrolase activity
ML0161	GO:0004643	phosphoribosylaminoimidazolecarboxamide formyltransferase activity
ML0161	GO:0006164	purine nucleotide biosynthetic process
ML0173	GO:0003735	structural constituent of ribosome
ML0173	GO:0006412	translation
ML0173	GO:0015934	large ribosomal subunit
ML0174	GO:0000160	phosphorelay signal transduction system
ML0174	GO:0003677	DNA binding
ML0174	GO:0006355	regulation of transcription, DNA-templated
ML0175	GO:0000155	phosphorelay sensor kinase activity
ML0175	GO:0004871	signal transducer activity
ML0175	GO:0007165	signal transduction
ML0175	GO:0016021	integral component of membrane
ML0175	GO:0016310	phosphorylation
ML0175	GO:0016772	transferase activity, transferring phosphorus-containing groups
ML0176	GO:0004252	serine-type endopeptidase activity
ML0176	GO:0005515	protein binding
ML0176	GO:0006508	proteolysis
ML0178	GO:0005216	ion channel activity
ML0178	GO:0006810	transport
ML0178	GO:0016021	integral component of membrane
ML0182	GO:0009058	biosynthetic process
ML0182	GO:0016779	nucleotidyltransferase activity
ML0183	GO:0032324	molybdopterin cofactor biosynthetic process
ML0184	GO:0008080	N-acetyltransferase activity
ML0187	GO:0008080	N-acetyltransferase activity
ML0192	GO:0000030	mannosyltransferase activity
ML0192	GO:0006493	protein O-linked glycosylation
ML0192	GO:0016020	membrane
ML0193	GO:0008152	metabolic process
ML0193	GO:0008168	methyltransferase activity
ML0198	GO:0003676	nucleic acid binding
ML0198	GO:0003677	DNA binding
ML0198	GO:0006355	regulation of transcription, DNA-templated
ML0200	GO:0003677	DNA binding
ML0200	GO:0003916	DNA topoisomerase activity
ML0200	GO:0003917	DNA topoisomerase type I activity
ML0200	GO:0006265	DNA topological change
ML0201	GO:0004871	signal transducer activity
ML0201	GO:0007165	signal transduction
ML0201	GO:0009190	cyclic nucleotide biosynthetic process
ML0201	GO:0016021	integral component of membrane
ML0201	GO:0016849	phosphorus-oxygen lyase activity
ML0201	GO:0035556	intracellular signal transduction
ML0202	GO:0003677	DNA binding
ML0202	GO:0003887	DNA-directed DNA polymerase activity
ML0202	GO:0006260	DNA replication
ML0202	GO:0008408	3'-5' exonuclease activity
ML0204	GO:0003824	catalytic activity
ML0204	GO:0050662	coenzyme binding
ML0210	GO:0000287	magnesium ion binding
ML0210	GO:0004427	inorganic diphosphatase activity
ML0210	GO:0005737	cytoplasm
ML0210	GO:0006796	phosphate-containing compound metabolic process
ML0211	GO:0004185	serine-type carboxypeptidase activity
ML0211	GO:0006508	proteolysis
ML0213	GO:0000166	nucleotide binding
ML0213	GO:0005524	ATP binding
ML0213	GO:0005737	cytoplasm
ML0213	GO:0008033	tRNA processing
ML0213	GO:0016879	ligase activity, forming carbon-nitrogen bonds
ML0214	GO:0004422	hypoxanthine phosphoribosyltransferase activity
ML0214	GO:0005737	cytoplasm
ML0214	GO:0006166	purine ribonucleoside salvage
ML0214	GO:0009116	nucleoside metabolic process
ML0222	GO:0004222	metalloendopeptidase activity
ML0222	GO:0005524	ATP binding
ML0222	GO:0006508	proteolysis
ML0222	GO:0016020	membrane
ML0223	GO:0003934	GTP cyclohydrolase I activity
ML0223	GO:0005737	cytoplasm
ML0223	GO:0046654	tetrahydrofolate biosynthetic process
ML0224	GO:0004156	dihydropteroate synthase activity
ML0224	GO:0009396	folic acid-containing compound biosynthetic process
ML0224	GO:0042558	pteridine-containing compound metabolic process
ML0224	GO:0044237	cellular metabolic process
ML0225	GO:0004150	dihydroneopterin aldolase activity
ML0225	GO:0006760	folic acid-containing compound metabolic process
ML0226	GO:0003848	2-amino-4-hydroxy-6-hydroxymethyldihydropteridine diphosphokinase activity
ML0226	GO:0009396	folic acid-containing compound biosynthetic process
ML0229	GO:0055114	oxidation-reduction process
ML0230	GO:0004592	pantoate-beta-alanine ligase activity
ML0230	GO:0015940	pantothenate biosynthetic process
ML0231	GO:0004068	aspartate 1-decarboxylase activity
ML0231	GO:0006523	alanine biosynthetic process
ML0232	GO:0004594	pantothenate kinase activity
ML0233	GO:0000166	nucleotide binding
ML0233	GO:0003676	nucleic acid binding
ML0233	GO:0004812	aminoacyl-tRNA ligase activity
ML0233	GO:0004824	lysine-tRNA ligase activity
ML0233	GO:0005524	ATP binding
ML0233	GO:0005737	cytoplasm
ML0233	GO:0006418	tRNA aminoacylation for protein translation
ML0233	GO:0006430	lysyl-tRNA aminoacylation
ML0235	GO:0005515	protein binding
ML0235	GO:0005524	ATP binding
ML0235	GO:0019538	protein metabolic process
ML0236	GO:0009058	biosynthetic process
ML0236	GO:0009396	folic acid-containing compound biosynthetic process
ML0238	GO:0000166	nucleotide binding
ML0238	GO:0004812	aminoacyl-tRNA ligase activity
ML0238	GO:0004825	methionine-tRNA ligase activity
ML0238	GO:0005524	ATP binding
ML0238	GO:0005737	cytoplasm
ML0238	GO:0006418	tRNA aminoacylation for protein translation
ML0238	GO:0006431	methionyl-tRNA aminoacylation
ML0239	GO:0004536	deoxyribonuclease activity
ML0239	GO:0016788	hydrolase activity, acting on ester bonds
ML0239	GO:0016888	endodeoxyribonuclease activity, producing 5'-phosphomonoesters
ML0241	GO:0000154	rRNA modification
ML0241	GO:0000179	rRNA (adenine-N6,N6-)-dimethyltransferase activity
ML0241	GO:0006364	rRNA processing
ML0241	GO:0008649	rRNA methyltransferase activity
ML0242	GO:0005524	ATP binding
ML0242	GO:0016114	terpenoid biosynthetic process
ML0242	GO:0050515	4-(cytidine 5'-diphospho)-2-C-methyl-D-erythritol kinase activity
ML0243	GO:0003824	catalytic activity
ML0243	GO:0008152	metabolic process
ML0244	GO:0004045	aminoacyl-tRNA hydrolase activity
ML0245	GO:0003735	structural constituent of ribosome
ML0245	GO:0005840	ribosome
ML0245	GO:0006412	translation
ML0245	GO:0008097	5S rRNA binding
ML0248	GO:0000287	magnesium ion binding
ML0248	GO:0004749	ribose phosphate diphosphokinase activity
ML0248	GO:0009156	ribonucleoside monophosphate biosynthetic process
ML0248	GO:0009165	nucleotide biosynthetic process
ML0248	GO:0044249	cellular biosynthetic process
ML0249	GO:0000287	magnesium ion binding
ML0249	GO:0000902	cell morphogenesis
ML0249	GO:0003977	UDP-N-acetylglucosamine diphosphorylase activity
ML0249	GO:0005737	cytoplasm
ML0249	GO:0009103	lipopolysaccharide biosynthetic process
ML0249	GO:0009252	peptidoglycan biosynthetic process
ML0249	GO:0019134	glucosamine-1-phosphate N-acetyltransferase activity
ML0252	GO:0003676	nucleic acid binding
ML0252	GO:0003684	damaged DNA binding
ML0252	GO:0005524	ATP binding
ML0252	GO:0006281	DNA repair
ML0255	GO:0000015	phosphopyruvate hydratase complex
ML0255	GO:0000287	magnesium ion binding
ML0255	GO:0004634	phosphopyruvate hydratase activity
ML0255	GO:0006096	glycolytic process
ML0256	GO:0007049	cell cycle
ML0269	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML0269	GO:0055114	oxidation-reduction process
ML0275	GO:0003824	catalytic activity
ML0275	GO:0030170	pyridoxal phosphate binding
ML0275	GO:0071268	homocysteine biosynthetic process
ML0280	GO:0004019	adenylosuccinate synthase activity
ML0280	GO:0005525	GTP binding
ML0280	GO:0006164	purine nucleotide biosynthetic process
ML0283	GO:0006812	cation transport
ML0283	GO:0008324	cation transmembrane transporter activity
ML0283	GO:0016021	integral component of membrane
ML0283	GO:0055085	transmembrane transport
ML0286	GO:0003824	catalytic activity
ML0286	GO:0004332	fructose-bisphosphate aldolase activity
ML0286	GO:0005975	carbohydrate metabolic process
ML0286	GO:0006096	glycolytic process
ML0286	GO:0008270	zinc ion binding
ML0286	GO:0016832	aldehyde-lyase activity
ML0294	GO:0009228	thiamine biosynthetic process
ML0294	GO:0051536	iron-sulfur cluster binding
ML0295	GO:0008972	phosphomethylpyrimidine kinase activity
ML0295	GO:0009228	thiamine biosynthetic process
ML0297	GO:0003824	catalytic activity
ML0297	GO:0009228	thiamine biosynthetic process
ML0299	GO:0016491	oxidoreductase activity
ML0299	GO:0050660	flavin adenine dinucleotide binding
ML0299	GO:0055114	oxidation-reduction process
ML0300	GO:0003824	catalytic activity
ML0300	GO:0004789	thiamine-phosphate diphosphorylase activity
ML0300	GO:0009228	thiamine biosynthetic process
ML0304	GO:0004672	protein kinase activity
ML0304	GO:0005524	ATP binding
ML0304	GO:0006468	protein phosphorylation
ML0310	GO:0008654	phospholipid biosynthetic process
ML0310	GO:0016020	membrane
ML0310	GO:0016780	phosphotransferase activity, for other substituted phosphate groups
ML0311	GO:0004609	phosphatidylserine decarboxylase activity
ML0311	GO:0008654	phospholipid biosynthetic process
ML0314	GO:0008152	metabolic process
ML0314	GO:0016787	hydrolase activity
ML0316	GO:0003677	DNA binding
ML0317	GO:0005524	ATP binding
ML0317	GO:0005737	cytoplasm
ML0317	GO:0006457	protein folding
ML0317	GO:0042026	protein refolding
ML0321	GO:0003824	catalytic activity
ML0321	GO:0008299	isoprenoid biosynthetic process
ML0321	GO:0050518	2-C-methyl-D-erythritol 4-phosphate cytidylyltransferase activity
ML0322	GO:0008685	2-C-methyl-D-erythritol 2,4-cyclodiphosphate synthase activity
ML0322	GO:0016114	terpenoid biosynthetic process
ML0323	GO:0000166	nucleotide binding
ML0323	GO:0004812	aminoacyl-tRNA ligase activity
ML0323	GO:0004817	cysteine-tRNA ligase activity
ML0323	GO:0005524	ATP binding
ML0323	GO:0005737	cytoplasm
ML0323	GO:0006418	tRNA aminoacylation for protein translation
ML0323	GO:0006423	cysteinyl-tRNA aminoacylation
ML0324	GO:0003723	RNA binding
ML0324	GO:0006396	RNA processing
ML0324	GO:0008168	methyltransferase activity
ML0324	GO:0008173	RNA methyltransferase activity
ML0325	GO:0006629	lipid metabolic process
ML0325	GO:0008081	phosphoric diester hydrolase activity
ML0333	GO:0003824	catalytic activity
ML0333	GO:0005975	carbohydrate metabolic process
ML0335	GO:0005887	integral component of plasma membrane
ML0335	GO:0042626	ATPase activity, coupled to transmembrane movement of substances
ML0335	GO:0043190	ATP-binding cassette (ABC) transporter complex
ML0335	GO:0055085	transmembrane transport
ML0336	GO:0005524	ATP binding
ML0336	GO:0016887	ATPase activity
ML0337	GO:0030001	metal ion transport
ML0337	GO:0046872	metal ion binding
ML0348	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML0348	GO:0055114	oxidation-reduction process
ML0354	GO:0003824	catalytic activity
ML0354	GO:0030976	thiamine pyrophosphate binding
ML0364	GO:0003735	structural constituent of ribosome
ML0364	GO:0005840	ribosome
ML0364	GO:0006412	translation
ML0365	GO:0003735	structural constituent of ribosome
ML0365	GO:0005840	ribosome
ML0365	GO:0006412	translation
ML0366	GO:0000287	magnesium ion binding
ML0366	GO:0005975	carbohydrate metabolic process
ML0366	GO:0008966	phosphoglucosamine mutase activity
ML0366	GO:0016868	intramolecular transferase activity, phosphotransferases
ML0366	GO:0071704	organic substance metabolic process
ML0371	GO:0004360	glutamine-fructose-6-phosphate transaminase (isomerizing) activity
ML0371	GO:0005975	carbohydrate metabolic process
ML0371	GO:0030246	carbohydrate binding
ML0371	GO:1901137	carbohydrate derivative biosynthetic process
ML0373	GO:0052855	ADP-dependent NAD(P)H-hydrate dehydratase activity
ML0375	GO:0003824	catalytic activity
ML0375	GO:0006522	alanine metabolic process
ML0375	GO:0008784	alanine racemase activity
ML0377	GO:0002949	tRNA threonylcarbamoyladenosine modification
ML0378	GO:0002949	tRNA threonylcarbamoyladenosine modification
ML0378	GO:0006474	N-terminal protein amino acid acetylation
ML0378	GO:0008080	N-acetyltransferase activity
ML0378	GO:0016407	acetyltransferase activity
ML0379	GO:0002949	tRNA threonylcarbamoyladenosine modification
ML0379	GO:0004222	metalloendopeptidase activity
ML0380	GO:0005524	ATP binding
ML0380	GO:0005737	cytoplasm
ML0380	GO:0006457	protein folding
ML0381	GO:0005524	ATP binding
ML0381	GO:0005737	cytoplasm
ML0381	GO:0006457	protein folding
ML0381	GO:0042026	protein refolding
ML0387	GO:0003824	catalytic activity
ML0387	GO:0003938	IMP dehydrogenase activity
ML0387	GO:0006164	purine nucleotide biosynthetic process
ML0387	GO:0016491	oxidoreductase activity
ML0387	GO:0055114	oxidation-reduction process
ML0388	GO:0003824	catalytic activity
ML0388	GO:0016491	oxidoreductase activity
ML0388	GO:0055114	oxidation-reduction process
ML0389	GO:0016491	oxidoreductase activity
ML0389	GO:0016614	oxidoreductase activity, acting on CH-OH group of donors
ML0389	GO:0055114	oxidation-reduction process
ML0390	GO:0016491	oxidoreductase activity
ML0390	GO:0055114	oxidation-reduction process
ML0392	GO:0003824	catalytic activity
ML0392	GO:0005975	carbohydrate metabolic process
ML0392	GO:0030246	carbohydrate binding
ML0395	GO:0003922	GMP synthase (glutamine-hydrolyzing) activity
ML0395	GO:0005524	ATP binding
ML0395	GO:0006164	purine nucleotide biosynthetic process
ML0395	GO:0006177	GMP biosynthetic process
ML0396	GO:0004512	inositol-3-phosphate synthase activity
ML0396	GO:0006021	inositol biosynthetic process
ML0396	GO:0008654	phospholipid biosynthetic process
ML0397	GO:0005215	transporter activity
ML0397	GO:0006810	transport
ML0397	GO:0016020	membrane
ML0414	GO:0003824	catalytic activity
ML0414	GO:0005992	trehalose biosynthetic process
ML0418	GO:0016491	oxidoreductase activity
ML0419	GO:0001510	RNA methylation
ML0419	GO:0003723	RNA binding
ML0419	GO:0006396	RNA processing
ML0419	GO:0008168	methyltransferase activity
ML0419	GO:0008173	RNA methyltransferase activity
ML0424	GO:0016209	antioxidant activity
ML0424	GO:0016491	oxidoreductase activity
ML0424	GO:0055114	oxidation-reduction process
ML0426	GO:0016740	transferase activity
ML0427	GO:0003676	nucleic acid binding
ML0427	GO:0016788	hydrolase activity, acting on ester bonds
ML0429	GO:0016491	oxidoreductase activity
ML0447	GO:0005506	iron ion binding
ML0447	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML0447	GO:0020037	heme binding
ML0447	GO:0055114	oxidation-reduction process
ML0450	GO:0003824	catalytic activity
ML0450	GO:0008152	metabolic process
ML0450	GO:0042819	vitamin B6 biosynthetic process
ML0450	GO:0042823	pyridoxal phosphate biosynthetic process
ML0451	GO:0016787	hydrolase activity
ML0453	GO:0016021	integral component of membrane
ML0453	GO:0016740	transferase activity
ML0454	GO:0008654	phospholipid biosynthetic process
ML0454	GO:0016020	membrane
ML0454	GO:0016780	phosphotransferase activity, for other substituted phosphate groups
ML0455	GO:0003824	catalytic activity
ML0456	GO:0000166	nucleotide binding
ML0456	GO:0004812	aminoacyl-tRNA ligase activity
ML0456	GO:0004829	threonine-tRNA ligase activity
ML0456	GO:0005524	ATP binding
ML0456	GO:0005737	cytoplasm
ML0456	GO:0006418	tRNA aminoacylation for protein translation
ML0456	GO:0006435	threonyl-tRNA aminoacylation
ML0456	GO:0016876	ligase activity, forming aminoacyl-tRNA and related compounds
ML0456	GO:0043039	tRNA aminoacylation
ML0458	GO:0016491	oxidoreductase activity
ML0458	GO:0055114	oxidation-reduction process
ML0468	GO:0016021	integral component of membrane
ML0474	GO:0004359	glutaminase activity
ML0474	GO:0042819	vitamin B6 biosynthetic process
ML0474	GO:0042823	pyridoxal phosphate biosynthetic process
ML0481	GO:0003676	nucleic acid binding
ML0481	GO:0004520	endodeoxyribonuclease activity
ML0481	GO:0006281	DNA repair
ML0481	GO:0006310	DNA recombination
ML0481	GO:0008821	crossover junction endodeoxyribonuclease activity
ML0482	GO:0003677	DNA binding
ML0482	GO:0003678	DNA helicase activity
ML0482	GO:0005524	ATP binding
ML0482	GO:0006281	DNA repair
ML0482	GO:0006310	DNA recombination
ML0482	GO:0009378	four-way junction helicase activity
ML0482	GO:0009379	Holliday junction helicase complex
ML0483	GO:0003677	DNA binding
ML0483	GO:0005524	ATP binding
ML0483	GO:0006281	DNA repair
ML0483	GO:0006310	DNA recombination
ML0483	GO:0009378	four-way junction helicase activity
ML0484	GO:0003824	catalytic activity
ML0484	GO:0008152	metabolic process
ML0484	GO:0031177	phosphopantetheine binding
ML0485	GO:0003824	catalytic activity
ML0485	GO:0003867	4-aminobutyrate transaminase activity
ML0485	GO:0008483	transaminase activity
ML0485	GO:0009448	gamma-aminobutyric acid metabolic process
ML0485	GO:0030170	pyridoxal phosphate binding
ML0487	GO:0006886	intracellular protein transport
ML0487	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
ML0488	GO:0006886	intracellular protein transport
ML0488	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
ML0491	GO:0008152	metabolic process
ML0491	GO:0015969	guanosine tetraphosphate metabolic process
ML0491	GO:0016597	amino acid binding
ML0492	GO:0000413	protein peptidyl-prolyl isomerization
ML0492	GO:0003755	peptidyl-prolyl cis-trans isomerase activity
ML0492	GO:0006457	protein folding
ML0494	GO:0004821	histidine-tRNA ligase activity
ML0494	GO:0005524	ATP binding
ML0494	GO:0005737	cytoplasm
ML0494	GO:0006427	histidyl-tRNA aminoacylation
ML0501	GO:0000166	nucleotide binding
ML0501	GO:0003676	nucleic acid binding
ML0501	GO:0004812	aminoacyl-tRNA ligase activity
ML0501	GO:0005524	ATP binding
ML0501	GO:0005737	cytoplasm
ML0501	GO:0006418	tRNA aminoacylation for protein translation
ML0501	GO:0016874	ligase activity
ML0510	GO:0003677	DNA binding
ML0510	GO:0005524	ATP binding
ML0510	GO:0006260	DNA replication
ML0512	GO:0000166	nucleotide binding
ML0512	GO:0003676	nucleic acid binding
ML0512	GO:0004813	alanine-tRNA ligase activity
ML0512	GO:0005524	ATP binding
ML0512	GO:0005737	cytoplasm
ML0512	GO:0006419	alanyl-tRNA aminoacylation
ML0512	GO:0016876	ligase activity, forming aminoacyl-tRNA and related compounds
ML0512	GO:0043039	tRNA aminoacylation
ML0513	GO:0003676	nucleic acid binding
ML0513	GO:0006139	nucleobase-containing compound metabolic process
ML0513	GO:0006364	rRNA processing
ML0515	GO:0004764	shikimate 3-dehydrogenase (NADP+) activity
ML0515	GO:0005737	cytoplasm
ML0515	GO:0055114	oxidation-reduction process
ML0516	GO:0004107	chorismate synthase activity
ML0516	GO:0009073	aromatic amino acid family biosynthetic process
ML0518	GO:0003856	3-dehydroquinate synthase activity
ML0518	GO:0005737	cytoplasm
ML0518	GO:0009073	aromatic amino acid family biosynthetic process
ML0518	GO:0016838	carbon-oxygen lyase activity, acting on phosphates
ML0519	GO:0003855	3-dehydroquinate dehydratase activity
ML0521	GO:0016787	hydrolase activity
ML0522	GO:0003746	translation elongation factor activity
ML0522	GO:0005737	cytoplasm
ML0522	GO:0006414	translational elongation
ML0522	GO:0043043	peptide biosynthetic process
ML0523	GO:0003723	RNA binding
ML0523	GO:0006353	DNA-templated transcription, termination
ML0523	GO:0006355	regulation of transcription, DNA-templated
ML0524	GO:0003824	catalytic activity
ML0532	GO:0004070	aspartate carbamoyltransferase activity
ML0532	GO:0006207	'de novo' pyrimidine nucleobase biosynthetic process
ML0532	GO:0006520	cellular amino acid metabolic process
ML0532	GO:0016597	amino acid binding
ML0532	GO:0016743	carboxyl- or carbamoyltransferase activity
ML0533	GO:0004151	dihydroorotase activity
ML0533	GO:0006221	pyrimidine nucleotide biosynthetic process
ML0533	GO:0016787	hydrolase activity
ML0533	GO:0016810	hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds
ML0533	GO:0046872	metal ion binding
ML0535	GO:0004088	carbamoyl-phosphate synthase (glutamine-hydrolyzing) activity
ML0535	GO:0006207	'de novo' pyrimidine nucleobase biosynthetic process
ML0535	GO:0006541	glutamine metabolic process
ML0536	GO:0003824	catalytic activity
ML0536	GO:0005524	ATP binding
ML0536	GO:0006807	nitrogen compound metabolic process
ML0537	GO:0003824	catalytic activity
ML0537	GO:0004590	orotidine-5'-phosphate decarboxylase activity
ML0537	GO:0006207	'de novo' pyrimidine nucleobase biosynthetic process
ML0537	GO:0006221	pyrimidine nucleotide biosynthetic process
ML0537	GO:0008152	metabolic process
ML0540	GO:0003676	nucleic acid binding
ML0541	GO:0004385	guanylate kinase activity
ML0541	GO:0006163	purine nucleotide metabolic process
ML0542	GO:0003677	DNA binding
ML0542	GO:0003899	DNA-directed RNA polymerase activity
ML0542	GO:0006351	transcription, DNA-templated
ML0543	GO:0003824	catalytic activity
ML0543	GO:0004632	phosphopantothenate--cysteine ligase activity
ML0543	GO:0004633	phosphopantothenoylcysteine decarboxylase activity
ML0543	GO:0010181	FMN binding
ML0543	GO:0015937	coenzyme A biosynthetic process
ML0543	GO:0015941	pantothenate catabolic process
ML0544	GO:0004478	methionine adenosyltransferase activity
ML0544	GO:0005524	ATP binding
ML0544	GO:0006556	S-adenosylmethionine biosynthetic process
ML0548	GO:0003677	DNA binding
ML0548	GO:0004003	ATP-dependent DNA helicase activity
ML0548	GO:0006260	DNA replication
ML0548	GO:0032508	DNA duplex unwinding
ML0550	GO:0003700	sequence-specific DNA binding transcription factor activity
ML0550	GO:0006355	regulation of transcription, DNA-templated
ML0551	GO:0008152	metabolic process
ML0551	GO:0008168	methyltransferase activity
ML0552	GO:0003824	catalytic activity
ML0552	GO:0004479	methionyl-tRNA formyltransferase activity
ML0552	GO:0009058	biosynthetic process
ML0552	GO:0016742	hydroxymethyl-, formyl- and related transferase activity
ML0552	GO:0071951	conversion of methionyl-tRNA to N-formyl-methionyl-tRNA
ML0554	GO:0003824	catalytic activity
ML0554	GO:0004750	ribulose-phosphate 3-epimerase activity
ML0554	GO:0005975	carbohydrate metabolic process
ML0554	GO:0006098	pentose-phosphate shunt
ML0554	GO:0008152	metabolic process
ML0554	GO:0016857	racemase and epimerase activity, acting on carbohydrates and derivatives
ML0555	GO:0003824	catalytic activity
ML0555	GO:0008270	zinc ion binding
ML0555	GO:0008703	5-amino-6-(5-phosphoribosylamino)uracil reductase activity
ML0555	GO:0008835	diaminohydroxyphosphoribosylaminopyrimidine deaminase activity
ML0555	GO:0009231	riboflavin biosynthetic process
ML0555	GO:0016787	hydrolase activity
ML0555	GO:0055114	oxidation-reduction process
ML0556	GO:0005215	transporter activity
ML0556	GO:0016021	integral component of membrane
ML0556	GO:0055085	transmembrane transport
ML0558	GO:0016491	oxidoreductase activity
ML0558	GO:0055114	oxidation-reduction process
ML0559	GO:0003935	GTP cyclohydrolase II activity
ML0559	GO:0008686	3,4-dihydroxy-2-butanone-4-phosphate synthase activity
ML0559	GO:0009231	riboflavin biosynthetic process
ML0560	GO:0009231	riboflavin biosynthetic process
ML0560	GO:0009349	riboflavin synthase complex
ML0562	GO:0003677	DNA binding
ML0562	GO:0005515	protein binding
ML0562	GO:0005737	cytoplasm
ML0562	GO:0006281	DNA repair
ML0562	GO:0009380	excinuclease repair complex
ML0562	GO:0009381	excinuclease ABC activity
ML0563	GO:0005524	ATP binding
ML0565	GO:0043937	regulation of sporulation
ML0569	GO:0016740	transferase activity
ML0570	GO:0006006	glucose metabolic process
ML0570	GO:0016620	oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
ML0570	GO:0050661	NADP binding
ML0570	GO:0051287	NAD binding
ML0570	GO:0055114	oxidation-reduction process
ML0571	GO:0004618	phosphoglycerate kinase activity
ML0571	GO:0006096	glycolytic process
ML0572	GO:0003824	catalytic activity
ML0572	GO:0004807	triose-phosphate isomerase activity
ML0572	GO:0006096	glycolytic process
ML0572	GO:0008152	metabolic process
ML0577	GO:0009306	protein secretion
ML0577	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
ML0577	GO:0016021	integral component of membrane
ML0578	GO:0003824	catalytic activity
ML0578	GO:0006099	tricarboxylic acid cycle
ML0578	GO:0008964	phosphoenolpyruvate carboxylase activity
ML0578	GO:0015977	carbon fixation
ML0579	GO:0005975	carbohydrate metabolic process
ML0579	GO:0006098	pentose-phosphate shunt
ML0579	GO:0017057	6-phosphogluconolactonase activity
ML0582	GO:0003824	catalytic activity
ML0582	GO:0004801	sedoheptulose-7-phosphate:D-glyceraldehyde-3-phosphate glyceronetransferase activity
ML0582	GO:0005737	cytoplasm
ML0582	GO:0005975	carbohydrate metabolic process
ML0582	GO:0006098	pentose-phosphate shunt
ML0583	GO:0003824	catalytic activity
ML0583	GO:0004802	transketolase activity
ML0583	GO:0008152	metabolic process
ML0584	GO:0004659	prenyltransferase activity
ML0584	GO:0008495	protoheme IX farnesyltransferase activity
ML0584	GO:0016021	integral component of membrane
ML0584	GO:0048034	heme O biosynthetic process
ML0587	GO:0006784	heme a biosynthetic process
ML0587	GO:0016021	integral component of membrane
ML0587	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0587	GO:0055114	oxidation-reduction process
ML0589	GO:0006810	transport
ML0589	GO:0016020	membrane
ML0589	GO:0042891	antibiotic transport
ML0589	GO:0043215	daunorubicin transport
ML0589	GO:0046677	response to antibiotic
ML0589	GO:1900753	doxorubicin transport
ML0590	GO:0005524	ATP binding
ML0590	GO:0016887	ATPase activity
ML0593	GO:0004519	endonuclease activity
ML0593	GO:0016226	iron-sulfur cluster assembly
ML0593	GO:0016539	intein-mediated protein splicing
ML0594	GO:0016226	iron-sulfur cluster assembly
ML0595	GO:0005524	ATP binding
ML0595	GO:0006810	transport
ML0595	GO:0016887	ATPase activity
ML0596	GO:0003824	catalytic activity
ML0596	GO:0006534	cysteine metabolic process
ML0596	GO:0030170	pyridoxal phosphate binding
ML0596	GO:0031071	cysteine desulfurase activity
ML0597	GO:0005506	iron ion binding
ML0597	GO:0016226	iron-sulfur cluster assembly
ML0597	GO:0051536	iron-sulfur cluster binding
ML0603	GO:0003677	DNA binding
ML0603	GO:0003887	DNA-directed DNA polymerase activity
ML0603	GO:0006260	DNA replication
ML0603	GO:0009360	DNA polymerase III complex
ML0604	GO:0003723	RNA binding
ML0604	GO:0003735	structural constituent of ribosome
ML0604	GO:0005622	intracellular
ML0604	GO:0005840	ribosome
ML0604	GO:0006412	translation
ML0611	GO:0003924	GTPase activity
ML0611	GO:0005525	GTP binding
ML0615	GO:0008272	sulfate transport
ML0615	GO:0015419	sulfate transmembrane-transporting ATPase activity
ML0624	GO:0003677	DNA binding
ML0624	GO:0006355	regulation of transcription, DNA-templated
ML0625	GO:0005524	ATP binding
ML0625	GO:0006457	protein folding
ML0625	GO:0009408	response to heat
ML0625	GO:0031072	heat shock protein binding
ML0625	GO:0051082	unfolded protein binding
ML0626	GO:0006364	rRNA processing
ML0626	GO:0008168	methyltransferase activity
ML0627	GO:0003676	nucleic acid binding
ML0627	GO:0003723	RNA binding
ML0627	GO:0005524	ATP binding
ML0628	GO:0004222	metalloendopeptidase activity
ML0628	GO:0006364	rRNA processing
ML0631	GO:0003723	RNA binding
ML0631	GO:0005525	GTP binding
ML0631	GO:0005622	intracellular
ML0633	GO:0006281	DNA repair
ML0633	GO:0006310	DNA recombination
ML0634	GO:0016765	transferase activity, transferring alkyl or aryl (other than methyl) groups
ML0636A	GO:0009055	electron carrier activity
ML0636A	GO:0015035	protein disulfide oxidoreductase activity
ML0636A	GO:0045454	cell redox homeostasis
ML0637	GO:0000166	nucleotide binding
ML0637	GO:0003676	nucleic acid binding
ML0637	GO:0003824	catalytic activity
ML0637	GO:0005524	ATP binding
ML0637	GO:0005622	intracellular
ML0637	GO:0016787	hydrolase activity
ML0637	GO:0044237	cellular metabolic process
ML0643	GO:0004176	ATP-dependent peptidase activity
ML0643	GO:0004252	serine-type endopeptidase activity
ML0643	GO:0005515	protein binding
ML0643	GO:0006508	proteolysis
ML0644	GO:0016021	integral component of membrane
ML0660	GO:0003995	acyl-CoA dehydrogenase activity
ML0660	GO:0008152	metabolic process
ML0660	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0660	GO:0055114	oxidation-reduction process
ML0661	GO:0003995	acyl-CoA dehydrogenase activity
ML0661	GO:0008152	metabolic process
ML0661	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0661	GO:0050660	flavin adenine dinucleotide binding
ML0661	GO:0055114	oxidation-reduction process
ML0662	GO:0004401	histidinol-phosphatase activity
ML0662	GO:0046854	phosphatidylinositol phosphorylation
ML0666	GO:0016491	oxidoreductase activity
ML0666	GO:0055114	oxidation-reduction process
ML0667	GO:0003747	translation release factor activity
ML0667	GO:0005737	cytoplasm
ML0667	GO:0006415	translational termination
ML0667	GO:0016149	translation release factor activity, codon specific
ML0669	GO:0005524	ATP binding
ML0669	GO:0016887	ATPase activity
ML0669	GO:0051301	cell division
ML0670	GO:0007049	cell cycle
ML0670	GO:0016020	membrane
ML0670	GO:0016021	integral component of membrane
ML0671	GO:0003723	RNA binding
ML0674	GO:0003824	catalytic activity
ML0674	GO:0004488	methylenetetrahydrofolate dehydrogenase (NADP+) activity
ML0674	GO:0009396	folic acid-containing compound biosynthetic process
ML0674	GO:0055114	oxidation-reduction process
ML0678	GO:0003677	DNA binding
ML0678	GO:0004803	transposase activity
ML0678	GO:0006313	transposition, DNA-mediated
ML0682	GO:0004414	homoserine O-acetyltransferase activity
ML0682	GO:0005737	cytoplasm
ML0682	GO:0009086	methionine biosynthetic process
ML0686	GO:0000166	nucleotide binding
ML0686	GO:0004812	aminoacyl-tRNA ligase activity
ML0686	GO:0004830	tryptophan-tRNA ligase activity
ML0686	GO:0005524	ATP binding
ML0686	GO:0005737	cytoplasm
ML0686	GO:0006418	tRNA aminoacylation for protein translation
ML0686	GO:0006436	tryptophanyl-tRNA aminoacylation
ML0691	GO:0006508	proteolysis
ML0691	GO:0009002	serine-type D-Ala-D-Ala carboxypeptidase activity
ML0696	GO:0006099	tricarboxylic acid cycle
ML0696	GO:0009055	electron carrier activity
ML0696	GO:0016491	oxidoreductase activity
ML0696	GO:0051536	iron-sulfur cluster binding
ML0696	GO:0055114	oxidation-reduction process
ML0697	GO:0006099	tricarboxylic acid cycle
ML0697	GO:0016491	oxidoreductase activity
ML0697	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0697	GO:0022900	electron transport chain
ML0697	GO:0050660	flavin adenine dinucleotide binding
ML0697	GO:0055114	oxidation-reduction process
ML0698	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0699	GO:0000104	succinate dehydrogenase activity
ML0699	GO:0006099	tricarboxylic acid cycle
ML0699	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0699	GO:0045281	succinate dehydrogenase complex
ML0700	GO:0004000	adenosine deaminase activity
ML0700	GO:0009168	purine ribonucleoside monophosphate biosynthetic process
ML0700	GO:0019239	deaminase activity
ML0706	GO:0000287	magnesium ion binding
ML0706	GO:0005975	carbohydrate metabolic process
ML0706	GO:0016868	intramolecular transferase activity, phosphotransferases
ML0706	GO:0071704	organic substance metabolic process
ML0707	GO:0003824	catalytic activity
ML0707	GO:0004731	purine-nucleoside phosphorylase activity
ML0707	GO:0006139	nucleobase-containing compound metabolic process
ML0707	GO:0009116	nucleoside metabolic process
ML0707	GO:0016763	transferase activity, transferring pentosyl groups
ML0713	GO:0004368	glycerol-3-phosphate dehydrogenase activity
ML0713	GO:0006072	glycerol-3-phosphate metabolic process
ML0713	GO:0009331	glycerol-3-phosphate dehydrogenase complex
ML0713	GO:0016491	oxidoreductase activity
ML0713	GO:0055114	oxidation-reduction process
ML0715	GO:0005576	extracellular region
ML0715	GO:0016787	hydrolase activity
ML0717	GO:0003677	DNA binding
ML0726	GO:0003824	catalytic activity
ML0726	GO:0005524	ATP binding
ML0728	GO:0004792	thiosulfate sulfurtransferase activity
ML0729	GO:0005737	cytoplasm
ML0732	GO:0004077	biotin-[acetyl-CoA-carboxylase] ligase activity
ML0732	GO:0006464	cellular protein modification process
ML0734	GO:0000271	polysaccharide biosynthetic process
ML0734	GO:0006810	transport
ML0734	GO:0016021	integral component of membrane
ML0735	GO:0004638	phosphoribosylaminoimidazole carboxylase activity
ML0735	GO:0005524	ATP binding
ML0735	GO:0006189	'de novo' IMP biosynthetic process
ML0736	GO:0006189	'de novo' IMP biosynthetic process
ML0737	GO:0003995	acyl-CoA dehydrogenase activity
ML0737	GO:0008152	metabolic process
ML0737	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0737	GO:0050660	flavin adenine dinucleotide binding
ML0737	GO:0055114	oxidation-reduction process
ML0747	GO:0000166	nucleotide binding
ML0747	GO:0006812	cation transport
ML0747	GO:0016021	integral component of membrane
ML0747	GO:0019829	cation-transporting ATPase activity
ML0747	GO:0046872	metal ion binding
ML0753	GO:0009058	biosynthetic process
ML0753	GO:0016779	nucleotidyltransferase activity
ML0755	GO:0016787	hydrolase activity
ML0756	GO:0003676	nucleic acid binding
ML0756	GO:0003677	DNA binding
ML0756	GO:0006306	DNA methylation
ML0756	GO:0008168	methyltransferase activity
ML0756	GO:0008170	N-methyltransferase activity
ML0756	GO:0032259	methylation
ML0758	GO:0016491	oxidoreductase activity
ML0758	GO:0016881	acid-amino acid ligase activity
ML0758	GO:0043773	coenzyme F420-0 gamma-glutamyl ligase activity
ML0758	GO:0046872	metal ion binding
ML0758	GO:0051188	cofactor biosynthetic process
ML0759	GO:0000287	magnesium ion binding
ML0759	GO:0016780	phosphotransferase activity, for other substituted phosphate groups
ML0759	GO:0051188	cofactor biosynthetic process
ML0763	GO:0005975	carbohydrate metabolic process
ML0763	GO:0016868	intramolecular transferase activity, phosphotransferases
ML0763	GO:0071704	organic substance metabolic process
ML0765	GO:0004476	mannose-6-phosphate isomerase activity
ML0765	GO:0005975	carbohydrate metabolic process
ML0765	GO:0008270	zinc ion binding
ML0765	GO:0009298	GDP-mannose biosynthetic process
ML0771	GO:0004013	adenosylhomocysteinase activity
ML0771	GO:0006730	one-carbon metabolic process
ML0772	GO:0004798	thymidylate kinase activity
ML0772	GO:0005524	ATP binding
ML0772	GO:0006233	dTDP biosynthetic process
ML0773	GO:0000160	phosphorelay signal transduction system
ML0773	GO:0003677	DNA binding
ML0773	GO:0006355	regulation of transcription, DNA-templated
ML0774	GO:0000155	phosphorelay sensor kinase activity
ML0774	GO:0004871	signal transducer activity
ML0774	GO:0007165	signal transduction
ML0774	GO:0016021	integral component of membrane
ML0774	GO:0016310	phosphorylation
ML0774	GO:0016772	transferase activity, transferring phosphorus-containing groups
ML0778	GO:0044238	primary metabolic process
ML0779	GO:0005524	ATP binding
ML0779	GO:0006605	protein targeting
ML0779	GO:0006886	intracellular protein transport
ML0779	GO:0016020	membrane
ML0779	GO:0017038	protein import
ML0781	GO:0006813	potassium ion transport
ML0781	GO:0008324	cation transmembrane transporter activity
ML0782	GO:0006812	cation transport
ML0782	GO:0015299	solute:proton antiporter activity
ML0782	GO:0016021	integral component of membrane
ML0782	GO:0055085	transmembrane transport
ML0791	GO:0003924	GTPase activity
ML0791	GO:0005525	GTP binding
ML0792	GO:0003824	catalytic activity
ML0792	GO:0003866	3-phosphoshikimate 1-carboxyvinyltransferase activity
ML0792	GO:0016765	transferase activity, transferring alkyl or aryl (other than methyl) groups
ML0798	GO:0005515	protein binding
ML0799	GO:0002161	aminoacyl-tRNA editing activity
ML0808	GO:0008909	isochorismate synthase activity
ML0808	GO:0009058	biosynthetic process
ML0810	GO:0005515	protein binding
ML0811	GO:0003676	nucleic acid binding
ML0811	GO:0005524	ATP binding
ML0815	GO:0003677	DNA binding
ML0816	GO:0006508	proteolysis
ML0816	GO:0008237	metallopeptidase activity
ML0816	GO:0008270	zinc ion binding
ML0817	GO:0008641	small protein activating enzyme activity
ML0824	GO:0003700	sequence-specific DNA binding transcription factor activity
ML0824	GO:0006355	regulation of transcription, DNA-templated
ML0825	GO:0003700	sequence-specific DNA binding transcription factor activity
ML0825	GO:0006355	regulation of transcription, DNA-templated
ML0826	GO:0000166	nucleotide binding
ML0826	GO:0004812	aminoacyl-tRNA ligase activity
ML0826	GO:0004820	glycine-tRNA ligase activity
ML0826	GO:0005524	ATP binding
ML0826	GO:0005737	cytoplasm
ML0826	GO:0006418	tRNA aminoacylation for protein translation
ML0826	GO:0006426	glycyl-tRNA aminoacylation
ML0831	GO:0000287	magnesium ion binding
ML0831	GO:0008832	dGTPase activity
ML0831	GO:0046039	GTP metabolic process
ML0833	GO:0003677	DNA binding
ML0833	GO:0003896	DNA primase activity
ML0833	GO:0006260	DNA replication
ML0833	GO:0006269	DNA replication, synthesis of RNA primer
ML0833	GO:0008270	zinc ion binding
ML0833	GO:0016779	nucleotidyltransferase activity
ML0836	GO:0044237	cellular metabolic process
ML0838	GO:0005737	cytoplasm
ML0838	GO:0006535	cysteine biosynthetic process from serine
ML0838	GO:0009001	serine O-acetyltransferase activity
ML0838	GO:0016740	transferase activity
ML0839	GO:0004124	cysteine synthase activity
ML0839	GO:0006535	cysteine biosynthetic process from serine
ML0842	GO:0003824	catalytic activity
ML0842	GO:0006534	cysteine metabolic process
ML0842	GO:0030170	pyridoxal phosphate binding
ML0842	GO:0031071	cysteine desulfurase activity
ML0844	GO:0016021	integral component of membrane
ML0844	GO:0055085	transmembrane transport
ML0845	GO:0003997	acyl-CoA oxidase activity
ML0845	GO:0005777	peroxisome
ML0845	GO:0006635	fatty acid beta-oxidation
ML0845	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML0845	GO:0055114	oxidation-reduction process
ML0848	GO:0005524	ATP binding
ML0848	GO:0016887	ATPase activity
ML0852	GO:0003919	FMN adenylyltransferase activity
ML0852	GO:0008531	riboflavin kinase activity
ML0852	GO:0009231	riboflavin biosynthetic process
ML0853	GO:0003735	structural constituent of ribosome
ML0853	GO:0005622	intracellular
ML0853	GO:0005840	ribosome
ML0853	GO:0006412	translation
ML0854	GO:0000175	3'-5'-exoribonuclease activity
ML0854	GO:0003676	nucleic acid binding
ML0854	GO:0003723	RNA binding
ML0854	GO:0004654	polyribonucleotide nucleotidyltransferase activity
ML0854	GO:0005737	cytoplasm
ML0854	GO:0006396	RNA processing
ML0854	GO:0006402	mRNA catabolic process
ML0855	GO:0003824	catalytic activity
ML0855	GO:0004222	metalloendopeptidase activity
ML0855	GO:0006508	proteolysis
ML0855	GO:0046872	metal ion binding
ML0858	GO:0003824	catalytic activity
ML0858	GO:0009107	lipoate biosynthetic process
ML0858	GO:0016992	lipoate synthase activity
ML0858	GO:0051536	iron-sulfur cluster binding
ML0858	GO:0051539	4 iron, 4 sulfur cluster binding
ML0859	GO:0005737	cytoplasm
ML0859	GO:0006464	cellular protein modification process
ML0859	GO:0009107	lipoate biosynthetic process
ML0859	GO:0016415	octanoyltransferase activity
ML0860	GO:0003824	catalytic activity
ML0860	GO:0050662	coenzyme binding
ML0861	GO:0008152	metabolic process
ML0861	GO:0016746	transferase activity, transferring acyl groups
ML0862	GO:0016491	oxidoreductase activity
ML0864	GO:0004177	aminopeptidase activity
ML0864	GO:0005622	intracellular
ML0864	GO:0005737	cytoplasm
ML0864	GO:0006508	proteolysis
ML0864	GO:0008235	metalloexopeptidase activity
ML0864	GO:0019538	protein metabolic process
ML0864	GO:0030145	manganese ion binding
ML0865	GO:0004047	aminomethyltransferase activity
ML0865	GO:0005515	protein binding
ML0865	GO:0006546	glycine catabolic process
ML0866	GO:0003824	catalytic activity
ML0866	GO:0004084	branched-chain-amino-acid transaminase activity
ML0866	GO:0008152	metabolic process
ML0866	GO:0009081	branched-chain amino acid metabolic process
ML0868	GO:0008939	nicotinate-nucleotide-dimethylbenzimidazole phosphoribosyltransferase activity
ML0868	GO:0009163	nucleoside biosynthetic process
ML0868	GO:0009236	cobalamin biosynthetic process
ML0871	GO:0005198	structural molecule activity
ML0871	GO:0016226	iron-sulfur cluster assembly
ML0871	GO:0051536	iron-sulfur cluster binding
ML0873	GO:0016773	phosphotransferase activity, alcohol group as acceptor
ML0874	GO:0004066	asparagine synthase (glutamine-hydrolyzing) activity
ML0874	GO:0006529	asparagine biosynthetic process
ML0875	GO:0004129	cytochrome-c oxidase activity
ML0875	GO:0005507	copper ion binding
ML0875	GO:0016020	membrane
ML0875	GO:0016021	integral component of membrane
ML0875	GO:0022900	electron transport chain
ML0876	GO:0004129	cytochrome-c oxidase activity
ML0876	GO:0016021	integral component of membrane
ML0876	GO:0055114	oxidation-reduction process
ML0879	GO:0009055	electron carrier activity
ML0879	GO:0016020	membrane
ML0879	GO:0016491	oxidoreductase activity
ML0879	GO:0022904	respiratory electron transport chain
ML0880	GO:0016491	oxidoreductase activity
ML0880	GO:0051537	2 iron, 2 sulfur cluster binding
ML0880	GO:0055114	oxidation-reduction process
ML0881	GO:0005506	iron ion binding
ML0881	GO:0009055	electron carrier activity
ML0881	GO:0016021	integral component of membrane
ML0881	GO:0020037	heme binding
ML0882	GO:0004129	cytochrome-c oxidase activity
ML0882	GO:0015002	heme-copper terminal oxidase activity
ML0882	GO:0016020	membrane
ML0882	GO:0022904	respiratory electron transport chain
ML0883	GO:0000162	tryptophan biosynthetic process
ML0883	GO:0004048	anthranilate phosphoribosyltransferase activity
ML0883	GO:0008152	metabolic process
ML0883	GO:0016757	transferase activity, transferring glycosyl groups
ML0887	GO:0003824	catalytic activity
ML0887	GO:0008152	metabolic process
ML0890	GO:0005524	ATP binding
ML0890	GO:0016887	ATPase activity
ML0892	GO:0008152	metabolic process
ML0892	GO:0016746	transferase activity, transferring acyl groups
ML0893	GO:0016758	transferase activity, transferring hexosyl groups
ML0895	GO:0000287	magnesium ion binding
ML0895	GO:0008408	3'-5' exonuclease activity
ML0896	GO:0003849	3-deoxy-7-phosphoheptulonate synthase activity
ML0896	GO:0009073	aromatic amino acid family biosynthetic process
ML0897	GO:0004672	protein kinase activity
ML0897	GO:0005524	ATP binding
ML0897	GO:0006468	protein phosphorylation
ML0903	GO:0008080	N-acetyltransferase activity
ML0905	GO:0003700	sequence-specific DNA binding transcription factor activity
ML0905	GO:0006355	regulation of transcription, DNA-templated
ML0906	GO:0008168	methyltransferase activity
ML0908	GO:0008658	penicillin binding
ML0909	GO:0005524	ATP binding
ML0909	GO:0005737	cytoplasm
ML0909	GO:0008360	regulation of cell shape
ML0909	GO:0009058	biosynthetic process
ML0909	GO:0016874	ligase activity
ML0909	GO:0016881	acid-amino acid ligase activity
ML0909	GO:0051301	cell division
ML0910	GO:0005524	ATP binding
ML0910	GO:0005737	cytoplasm
ML0910	GO:0009058	biosynthetic process
ML0910	GO:0016874	ligase activity
ML0910	GO:0047480	UDP-N-acetylmuramoyl-tripeptide-D-alanyl-D-alanine ligase activity
ML0910	GO:0071555	cell wall organization
ML0911	GO:0008963	phospho-N-acetylmuramoyl-pentapeptide-transferase activity
ML0911	GO:0016020	membrane
ML0911	GO:0016021	integral component of membrane
ML0912	GO:0005524	ATP binding
ML0912	GO:0005737	cytoplasm
ML0912	GO:0008360	regulation of cell shape
ML0912	GO:0008764	UDP-N-acetylmuramoylalanine-D-glutamate ligase activity
ML0912	GO:0009058	biosynthetic process
ML0912	GO:0016874	ligase activity
ML0912	GO:0051301	cell division
ML0913	GO:0007049	cell cycle
ML0913	GO:0009252	peptidoglycan biosynthetic process
ML0913	GO:0016021	integral component of membrane
ML0913	GO:0051301	cell division
ML0914	GO:0005975	carbohydrate metabolic process
ML0914	GO:0009252	peptidoglycan biosynthetic process
ML0914	GO:0016758	transferase activity, transferring hexosyl groups
ML0914	GO:0030259	lipid glycosylation
ML0914	GO:0050511	undecaprenyldiphospho-muramoylpentapeptide beta-N-acetylglucosaminyltransferase activity
ML0915	GO:0005524	ATP binding
ML0915	GO:0008763	UDP-N-acetylmuramate-L-alanine ligase activity
ML0915	GO:0009058	biosynthetic process
ML0915	GO:0009252	peptidoglycan biosynthetic process
ML0915	GO:0016874	ligase activity
ML0916	GO:0090529	cell septum assembly
ML0917	GO:0003924	GTPase activity
ML0917	GO:0005525	GTP binding
ML0917	GO:0005737	cytoplasm
ML0920	GO:0090529	cell septum assembly
ML0921	GO:0016020	membrane
ML0925	GO:0003824	catalytic activity
ML0925	GO:0004356	glutamate-ammonia ligase activity
ML0925	GO:0005737	cytoplasm
ML0925	GO:0006542	glutamine biosynthetic process
ML0925	GO:0006807	nitrogen compound metabolic process
ML0925	GO:0009399	nitrogen fixation
ML0949	GO:0003677	DNA binding
ML0955	GO:0003824	catalytic activity
ML0955	GO:0005524	ATP binding
ML0955	GO:0016301	kinase activity
ML0955	GO:0016310	phosphorylation
ML0955	GO:0016772	transferase activity, transferring phosphorus-containing groups
ML0961	GO:0003871	5-methyltetrahydropteroyltriglutamate-homocysteine S-methyltransferase activity
ML0961	GO:0008270	zinc ion binding
ML0961	GO:0008652	cellular amino acid biosynthetic process
ML0961	GO:0009086	methionine biosynthetic process
ML0977	GO:0000166	nucleotide binding
ML0977	GO:0003677	DNA binding
ML0977	GO:0005524	ATP binding
ML0978	GO:0008080	N-acetyltransferase activity
ML0979	GO:0008444	CDP-diacylglycerol-glycerol-3-phosphate 3-phosphatidyltransferase activity
ML0979	GO:0008654	phospholipid biosynthetic process
ML0979	GO:0016020	membrane
ML0979	GO:0016021	integral component of membrane
ML0979	GO:0016780	phosphotransferase activity, for other substituted phosphate groups
ML0985	GO:0016758	transferase activity, transferring hexosyl groups
ML0987	GO:0003677	DNA binding
ML0987	GO:0003697	single-stranded DNA binding
ML0987	GO:0004519	endonuclease activity
ML0987	GO:0005524	ATP binding
ML0987	GO:0006259	DNA metabolic process
ML0987	GO:0006281	DNA repair
ML0987	GO:0008094	DNA-dependent ATPase activity
ML0987	GO:0016539	intein-mediated protein splicing
ML0988	GO:0006282	regulation of DNA repair
ML0989	GO:0003824	catalytic activity
ML0989	GO:0005737	cytoplasm
ML0989	GO:0006400	tRNA modification
ML0989	GO:0009451	RNA modification
ML0989	GO:0016740	transferase activity
ML0989	GO:0043412	macromolecule modification
ML0989	GO:0051536	iron-sulfur cluster binding
ML0989	GO:0051539	4 iron, 4 sulfur cluster binding
ML0995	GO:0008033	tRNA processing
ML0996	GO:0005737	cytoplasm
ML0996	GO:0008837	diaminopimelate epimerase activity
ML0996	GO:0009089	lysine biosynthetic process via diaminopimelate
ML0997	GO:0005525	GTP binding
ML1003	GO:0003677	DNA binding
ML1003	GO:0004252	serine-type endopeptidase activity
ML1003	GO:0006355	regulation of transcription, DNA-templated
ML1003	GO:0006508	proteolysis
ML1003	GO:0009432	SOS response
ML1003	GO:0045892	negative regulation of transcription, DNA-templated
ML1005	GO:0008270	zinc ion binding
ML1005	GO:0045892	negative regulation of transcription, DNA-templated
ML1009	GO:0006367	transcription initiation from RNA polymerase II promoter
ML1013	GO:0003677	DNA binding
ML1013	GO:0003700	sequence-specific DNA binding transcription factor activity
ML1013	GO:0006355	regulation of transcription, DNA-templated
ML1013	GO:0046914	transition metal ion binding
ML1013	GO:0046983	protein dimerization activity
ML1014	GO:0003677	DNA binding
ML1014	GO:0003700	sequence-specific DNA binding transcription factor activity
ML1014	GO:0006352	DNA-templated transcription, initiation
ML1014	GO:0006355	regulation of transcription, DNA-templated
ML1014	GO:0016987	sigma factor activity
ML1022	GO:0003677	DNA binding
ML1022	GO:0003700	sequence-specific DNA binding transcription factor activity
ML1022	GO:0006352	DNA-templated transcription, initiation
ML1022	GO:0006355	regulation of transcription, DNA-templated
ML1022	GO:0016987	sigma factor activity
ML1024	GO:0046854	phosphatidylinositol phosphorylation
ML1028	GO:0004170	dUTP diphosphatase activity
ML1028	GO:0016787	hydrolase activity
ML1028	GO:0046080	dUTP metabolic process
ML1036	GO:0015105	arsenite transmembrane transporter activity
ML1036	GO:0015700	arsenite transport
ML1036	GO:0016021	integral component of membrane
ML1036	GO:0055085	transmembrane transport
ML1038	GO:0003824	catalytic activity
ML1038	GO:0008152	metabolic process
ML1038	GO:0008661	1-deoxy-D-xylulose-5-phosphate synthase activity
ML1038	GO:0016114	terpenoid biosynthetic process
ML1040	GO:0000166	nucleotide binding
ML1040	GO:0003676	nucleic acid binding
ML1040	GO:0003824	catalytic activity
ML1040	GO:0005622	intracellular
ML1040	GO:0006139	nucleobase-containing compound metabolic process
ML1040	GO:0008408	3'-5' exonuclease activity
ML1040	GO:0044237	cellular metabolic process
ML1043	GO:0004853	uroporphyrinogen decarboxylase activity
ML1043	GO:0006779	porphyrin-containing compound biosynthetic process
ML1044	GO:0004729	oxygen-dependent protoporphyrinogen oxidase activity
ML1044	GO:0006779	porphyrin-containing compound biosynthetic process
ML1044	GO:0016491	oxidoreductase activity
ML1044	GO:0055114	oxidation-reduction process
ML1051	GO:0003824	catalytic activity
ML1051	GO:0008152	metabolic process
ML1052	GO:0003677	DNA binding
ML1058	GO:0008666	2,3,4,5-tetrahydropyridine-2,6-dicarboxylate N-succinyltransferase activity
ML1059	GO:0006508	proteolysis
ML1059	GO:0008152	metabolic process
ML1059	GO:0008237	metallopeptidase activity
ML1059	GO:0009014	succinyl-diaminopimelate desuccinylase activity
ML1059	GO:0009089	lysine biosynthetic process via diaminopimelate
ML1059	GO:0016787	hydrolase activity
ML1063	GO:0004156	dihydropteroate synthase activity
ML1063	GO:0009396	folic acid-containing compound biosynthetic process
ML1063	GO:0042558	pteridine-containing compound metabolic process
ML1063	GO:0044237	cellular metabolic process
ML1066	GO:0003824	catalytic activity
ML1066	GO:0006281	DNA repair
ML1066	GO:0006284	base-excision repair
ML1066	GO:0008725	DNA-3-methyladenine glycosylase activity
ML1069	GO:0005978	glycogen biosynthetic process
ML1069	GO:0008878	glucose-1-phosphate adenylyltransferase activity
ML1069	GO:0009058	biosynthetic process
ML1069	GO:0016779	nucleotidyltransferase activity
ML1070	GO:0003677	DNA binding
ML1075	GO:0008171	O-methyltransferase activity
ML1076	GO:0003677	DNA binding
ML1076	GO:0003700	sequence-specific DNA binding transcription factor activity
ML1076	GO:0006352	DNA-templated transcription, initiation
ML1076	GO:0006355	regulation of transcription, DNA-templated
ML1076	GO:0016987	sigma factor activity
ML1078	GO:0004252	serine-type endopeptidase activity
ML1078	GO:0005515	protein binding
ML1078	GO:0006508	proteolysis
ML1079	GO:0009306	protein secretion
ML1079	GO:0016020	membrane
ML1079	GO:0043953	protein transport by the Tat complex
ML1080	GO:0005524	ATP binding
ML1086	GO:0005215	transporter activity
ML1086	GO:0006810	transport
ML1087	GO:0006810	transport
ML1087	GO:0016020	membrane
ML1088	GO:0006810	transport
ML1088	GO:0016020	membrane
ML1089	GO:0005524	ATP binding
ML1089	GO:0016887	ATPase activity
ML1090	GO:0006824	cobalt ion transport
ML1090	GO:0015087	cobalt ion transmembrane transporter activity
ML1090	GO:0015095	magnesium ion transmembrane transporter activity
ML1090	GO:0015693	magnesium ion transport
ML1090	GO:0016020	membrane
ML1090	GO:0030001	metal ion transport
ML1090	GO:0046873	metal ion transmembrane transporter activity
ML1090	GO:0055085	transmembrane transport
ML1091	GO:0003824	catalytic activity
ML1091	GO:0005975	carbohydrate metabolic process
ML1091	GO:0006108	malate metabolic process
ML1091	GO:0016491	oxidoreductase activity
ML1091	GO:0016615	malate dehydrogenase activity
ML1091	GO:0016616	oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
ML1091	GO:0019752	carboxylic acid metabolic process
ML1091	GO:0055114	oxidation-reduction process
ML1093	GO:0005215	transporter activity
ML1093	GO:0006810	transport
ML1094	GO:0016491	oxidoreductase activity
ML1095	GO:0004591	oxoglutarate dehydrogenase (succinyl-transferring) activity
ML1095	GO:0006099	tricarboxylic acid cycle
ML1095	GO:0008152	metabolic process
ML1095	GO:0016624	oxidoreductase activity, acting on the aldehyde or oxo group of donors, disulfide as acceptor
ML1095	GO:0016746	transferase activity, transferring acyl groups
ML1095	GO:0030976	thiamine pyrophosphate binding
ML1095	GO:0055114	oxidation-reduction process
ML1098	GO:0003676	nucleic acid binding
ML1101	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML1103	GO:0003824	catalytic activity
ML1103	GO:0016491	oxidoreductase activity
ML1103	GO:0016614	oxidoreductase activity, acting on CH-OH group of donors
ML1103	GO:0050660	flavin adenine dinucleotide binding
ML1103	GO:0055114	oxidation-reduction process
ML1106	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML1106	GO:0055114	oxidation-reduction process
ML1113	GO:0005524	ATP binding
ML1113	GO:0006810	transport
ML1113	GO:0016021	integral component of membrane
ML1113	GO:0016887	ATPase activity
ML1113	GO:0042626	ATPase activity, coupled to transmembrane movement of substances
ML1113	GO:0055085	transmembrane transport
ML1114	GO:0005524	ATP binding
ML1114	GO:0006810	transport
ML1114	GO:0016021	integral component of membrane
ML1114	GO:0016887	ATPase activity
ML1114	GO:0042626	ATPase activity, coupled to transmembrane movement of substances
ML1114	GO:0055085	transmembrane transport
ML1119	GO:0016787	hydrolase activity
ML1121	GO:0043190	ATP-binding cassette (ABC) transporter complex
ML1121	GO:0055085	transmembrane transport
ML1122	GO:0000166	nucleotide binding
ML1122	GO:0005524	ATP binding
ML1122	GO:0015833	peptide transport
ML1122	GO:0016887	ATPase activity
ML1123	GO:0006810	transport
ML1123	GO:0016020	membrane
ML1124	GO:0006810	transport
ML1124	GO:0016020	membrane
ML1125	GO:0004089	carbonate dehydratase activity
ML1125	GO:0008270	zinc ion binding
ML1127	GO:0000166	nucleotide binding
ML1127	GO:0004812	aminoacyl-tRNA ligase activity
ML1127	GO:0004814	arginine-tRNA ligase activity
ML1127	GO:0005524	ATP binding
ML1127	GO:0005737	cytoplasm
ML1127	GO:0006418	tRNA aminoacylation for protein translation
ML1127	GO:0006420	arginyl-tRNA aminoacylation
ML1128	GO:0003824	catalytic activity
ML1128	GO:0008836	diaminopimelate decarboxylase activity
ML1128	GO:0009089	lysine biosynthetic process via diaminopimelate
ML1129	GO:0004412	homoserine dehydrogenase activity
ML1129	GO:0006520	cellular amino acid metabolic process
ML1129	GO:0008152	metabolic process
ML1129	GO:0016491	oxidoreductase activity
ML1129	GO:0016597	amino acid binding
ML1129	GO:0050661	NADP binding
ML1129	GO:0055114	oxidation-reduction process
ML1130	GO:0004795	threonine synthase activity
ML1130	GO:0006520	cellular amino acid metabolic process
ML1130	GO:0009088	threonine biosynthetic process
ML1130	GO:0030170	pyridoxal phosphate binding
ML1131	GO:0004413	homoserine kinase activity
ML1131	GO:0005524	ATP binding
ML1131	GO:0006566	threonine metabolic process
ML1132	GO:0003676	nucleic acid binding
ML1132	GO:0003723	RNA binding
ML1132	GO:0005524	ATP binding
ML1132	GO:0006353	DNA-templated transcription, termination
ML1132	GO:0008186	RNA-dependent ATPase activity
ML1133	GO:0003735	structural constituent of ribosome
ML1133	GO:0005622	intracellular
ML1133	GO:0005840	ribosome
ML1133	GO:0006412	translation
ML1134	GO:0003747	translation release factor activity
ML1134	GO:0005737	cytoplasm
ML1134	GO:0006415	translational termination
ML1134	GO:0016149	translation release factor activity, codon specific
ML1135	GO:0006479	protein methylation
ML1135	GO:0008168	methyltransferase activity
ML1135	GO:0008276	protein methyltransferase activity
ML1136	GO:0003725	double-stranded RNA binding
ML1137	GO:0008963	phospho-N-acetylmuramoyl-pentapeptide-transferase activity
ML1137	GO:0016021	integral component of membrane
ML1139	GO:0015078	hydrogen ion transmembrane transporter activity
ML1139	GO:0015986	ATP synthesis coupled proton transport
ML1140	GO:0015078	hydrogen ion transmembrane transporter activity
ML1140	GO:0015986	ATP synthesis coupled proton transport
ML1140	GO:0015991	ATP hydrolysis coupled proton transport
ML1140	GO:0033177	proton-transporting two-sector ATPase complex, proton-transporting domain
ML1140	GO:0045263	proton-transporting ATP synthase complex, coupling factor F(o)
ML1141	GO:0015078	hydrogen ion transmembrane transporter activity
ML1141	GO:0015986	ATP synthesis coupled proton transport
ML1141	GO:0045263	proton-transporting ATP synthase complex, coupling factor F(o)
ML1142	GO:0015078	hydrogen ion transmembrane transporter activity
ML1142	GO:0015986	ATP synthesis coupled proton transport
ML1142	GO:0045263	proton-transporting ATP synthase complex, coupling factor F(o)
ML1142	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
ML1143	GO:0005524	ATP binding
ML1143	GO:0015986	ATP synthesis coupled proton transport
ML1143	GO:0015991	ATP hydrolysis coupled proton transport
ML1143	GO:0015992	proton transport
ML1143	GO:0016820	hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances
ML1143	GO:0033178	proton-transporting two-sector ATPase complex, catalytic domain
ML1143	GO:0045261	proton-transporting ATP synthase complex, catalytic core F(1)
ML1143	GO:0046034	ATP metabolic process
ML1143	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
ML1143	GO:0046961	proton-transporting ATPase activity, rotational mechanism
ML1144	GO:0015986	ATP synthesis coupled proton transport
ML1144	GO:0045261	proton-transporting ATP synthase complex, catalytic core F(1)
ML1144	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
ML1144	GO:0046961	proton-transporting ATPase activity, rotational mechanism
ML1145	GO:0005524	ATP binding
ML1145	GO:0015986	ATP synthesis coupled proton transport
ML1145	GO:0015991	ATP hydrolysis coupled proton transport
ML1145	GO:0015992	proton transport
ML1145	GO:0016820	hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances
ML1145	GO:0033178	proton-transporting two-sector ATPase complex, catalytic domain
ML1145	GO:0046034	ATP metabolic process
ML1145	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
ML1146	GO:0015986	ATP synthesis coupled proton transport
ML1146	GO:0045261	proton-transporting ATP synthase complex, catalytic core F(1)
ML1146	GO:0046933	proton-transporting ATP synthase activity, rotational mechanism
ML1146	GO:0046961	proton-transporting ATPase activity, rotational mechanism
ML1150	GO:0003824	catalytic activity
ML1150	GO:0008760	UDP-N-acetylglucosamine 1-carboxyvinyltransferase activity
ML1150	GO:0016765	transferase activity, transferring alkyl or aryl (other than methyl) groups
ML1150	GO:0019277	UDP-N-acetylgalactosamine biosynthetic process
ML1151	GO:0003824	catalytic activity
ML1151	GO:0003908	methylated-DNA-[protein]-cysteine S-methyltransferase activity
ML1151	GO:0006281	DNA repair
ML1158	GO:0003824	catalytic activity
ML1158	GO:0008152	metabolic process
ML1158	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML1159	GO:0005515	protein binding
ML1159	GO:0045454	cell redox homeostasis
ML1165	GO:0030163	protein catabolic process
ML1171	GO:0004252	serine-type endopeptidase activity
ML1171	GO:0016021	integral component of membrane
ML1172	GO:0006807	nitrogen compound metabolic process
ML1172	GO:0008152	metabolic process
ML1172	GO:0008881	glutamate racemase activity
ML1172	GO:0009252	peptidoglycan biosynthetic process
ML1172	GO:0016855	racemase and epimerase activity, acting on amino acids and derivatives
ML1172	GO:0036361	racemase activity, acting on amino acids and derivatives
ML1174	GO:0000049	tRNA binding
ML1174	GO:0004549	tRNA-specific ribonuclease activity
ML1174	GO:0008033	tRNA processing
ML1175	GO:0009143	nucleoside triphosphate catabolic process
ML1175	GO:0016787	hydrolase activity
ML1175	GO:0017111	nucleoside-triphosphatase activity
ML1189	GO:0005506	iron ion binding
ML1189	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML1189	GO:0020037	heme binding
ML1189	GO:0055114	oxidation-reduction process
ML1190	GO:0005975	carbohydrate metabolic process
ML1191	GO:0003824	catalytic activity
ML1191	GO:0004312	fatty acid synthase activity
ML1191	GO:0004318	enoyl-[acyl-carrier-protein] reductase (NADH) activity
ML1191	GO:0005835	fatty acid synthase complex
ML1191	GO:0006633	fatty acid biosynthetic process
ML1191	GO:0008152	metabolic process
ML1191	GO:0016740	transferase activity
ML1191	GO:0055114	oxidation-reduction process
ML1192	GO:0000287	magnesium ion binding
ML1192	GO:0006633	fatty acid biosynthetic process
ML1192	GO:0008897	holo-[acyl-carrier-protein] synthase activity
ML1193	GO:0008152	metabolic process
ML1193	GO:0016787	hydrolase activity
ML1195	GO:0000166	nucleotide binding
ML1195	GO:0002161	aminoacyl-tRNA editing activity
ML1195	GO:0004812	aminoacyl-tRNA ligase activity
ML1195	GO:0004822	isoleucine-tRNA ligase activity
ML1195	GO:0005524	ATP binding
ML1195	GO:0005737	cytoplasm
ML1195	GO:0006418	tRNA aminoacylation for protein translation
ML1195	GO:0006428	isoleucyl-tRNA aminoacylation
ML1198	GO:0006520	cellular amino acid metabolic process
ML1199	GO:0004190	aspartic-type endopeptidase activity
ML1199	GO:0006508	proteolysis
ML1199	GO:0016020	membrane
ML1200	GO:0001522	pseudouridine synthesis
ML1200	GO:0003723	RNA binding
ML1200	GO:0009451	RNA modification
ML1200	GO:0009982	pseudouridine synthase activity
ML1207	GO:0003677	DNA binding
ML1207	GO:0003824	catalytic activity
ML1207	GO:0003887	DNA-directed DNA polymerase activity
ML1207	GO:0006260	DNA replication
ML1207	GO:0008408	3'-5' exonuclease activity
ML1209	GO:0004794	L-threonine ammonia-lyase activity
ML1209	GO:0006520	cellular amino acid metabolic process
ML1209	GO:0030170	pyridoxal phosphate binding
ML1213	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML1216	GO:0003824	catalytic activity
ML1216	GO:0004015	adenosylmethionine-8-amino-7-oxononanoate transaminase activity
ML1216	GO:0008483	transaminase activity
ML1216	GO:0009102	biotin biosynthetic process
ML1216	GO:0030170	pyridoxal phosphate binding
ML1217	GO:0003824	catalytic activity
ML1217	GO:0008152	metabolic process
ML1217	GO:0009058	biosynthetic process
ML1217	GO:0016740	transferase activity
ML1217	GO:0030170	pyridoxal phosphate binding
ML1218	GO:0000287	magnesium ion binding
ML1218	GO:0004141	dethiobiotin synthase activity
ML1218	GO:0005524	ATP binding
ML1218	GO:0009102	biotin biosynthetic process
ML1220	GO:0003824	catalytic activity
ML1220	GO:0004076	biotin synthase activity
ML1220	GO:0009102	biotin biosynthetic process
ML1220	GO:0051536	iron-sulfur cluster binding
ML1224	GO:0016787	hydrolase activity
ML1225	GO:0008987	quinolinate synthetase A activity
ML1225	GO:0009435	NAD biosynthetic process
ML1225	GO:0016765	transferase activity, transferring alkyl or aryl (other than methyl) groups
ML1225	GO:0051539	4 iron, 4 sulfur cluster binding
ML1226	GO:0005737	cytoplasm
ML1226	GO:0008734	L-aspartate oxidase activity
ML1226	GO:0009435	NAD biosynthetic process
ML1226	GO:0016491	oxidoreductase activity
ML1226	GO:0055114	oxidation-reduction process
ML1227	GO:0003824	catalytic activity
ML1227	GO:0004514	nicotinate-nucleotide diphosphorylase (carboxylating) activity
ML1227	GO:0009435	NAD biosynthetic process
ML1227	GO:0016763	transferase activity, transferring pentosyl groups
ML1227	GO:0019363	pyridine nucleotide biosynthetic process
ML1229	GO:0003824	catalytic activity
ML1229	GO:0008152	metabolic process
ML1229	GO:0016491	oxidoreductase activity
ML1229	GO:0016740	transferase activity
ML1229	GO:0031177	phosphopantetheine binding
ML1229	GO:0055114	oxidation-reduction process
ML1231	GO:0016020	membrane
ML1234	GO:0003824	catalytic activity
ML1234	GO:0008152	metabolic process
ML1241	GO:0003824	catalytic activity
ML1241	GO:0008152	metabolic process
ML1244	GO:0004144	diacylglycerol O-acyltransferase activity
ML1244	GO:0016746	transferase activity, transferring acyl groups
ML1244	GO:0045017	glycerolipid biosynthetic process
ML1245	GO:0008152	metabolic process
ML1245	GO:0016746	transferase activity, transferring acyl groups
ML1245	GO:0016791	phosphatase activity
ML1246	GO:0004366	glycerol-3-phosphate O-acyltransferase activity
ML1246	GO:0005886	plasma membrane
ML1246	GO:0008152	metabolic process
ML1246	GO:0008374	O-acyltransferase activity
ML1246	GO:0008654	phospholipid biosynthetic process
ML1246	GO:0016746	transferase activity, transferring acyl groups
ML1246	GO:0044255	cellular lipid metabolic process
ML1248	GO:0005524	ATP binding
ML1248	GO:0016887	ATPase activity
ML1249	GO:0004352	glutamate dehydrogenase (NAD+) activity
ML1249	GO:0019551	glutamate catabolic process to 2-oxoglutarate
ML1253	GO:0015671	oxygen transport
ML1253	GO:0019825	oxygen binding
ML1253	GO:0020037	heme binding
ML1257	GO:0000105	histidine biosynthetic process
ML1257	GO:0004399	histidinol dehydrogenase activity
ML1257	GO:0008152	metabolic process
ML1257	GO:0008270	zinc ion binding
ML1257	GO:0016491	oxidoreductase activity
ML1257	GO:0051287	NAD binding
ML1257	GO:0055114	oxidation-reduction process
ML1258	GO:0000105	histidine biosynthetic process
ML1258	GO:0003824	catalytic activity
ML1258	GO:0004400	histidinol-phosphate transaminase activity
ML1258	GO:0009058	biosynthetic process
ML1258	GO:0030170	pyridoxal phosphate binding
ML1259	GO:0000105	histidine biosynthetic process
ML1259	GO:0004424	imidazoleglycerol-phosphate dehydratase activity
ML1260	GO:0000105	histidine biosynthetic process
ML1260	GO:0005737	cytoplasm
ML1260	GO:0016763	transferase activity, transferring pentosyl groups
ML1261	GO:0000105	histidine biosynthetic process
ML1261	GO:0000162	tryptophan biosynthetic process
ML1261	GO:0003824	catalytic activity
ML1261	GO:0003949	1-(5-phosphoribosyl)-5-[(5-phosphoribosylamino)methylideneamino]imidazole-4-carboxamide isomerase activity
ML1261	GO:0004640	phosphoribosylanthranilate isomerase activity
ML1261	GO:0005737	cytoplasm
ML1261	GO:0008152	metabolic process
ML1263	GO:0000105	histidine biosynthetic process
ML1263	GO:0000107	imidazoleglycerol-phosphate synthase activity
ML1263	GO:0003824	catalytic activity
ML1263	GO:0005737	cytoplasm
ML1263	GO:0008152	metabolic process
ML1264	GO:0000105	histidine biosynthetic process
ML1264	GO:0004635	phosphoribosyl-AMP cyclohydrolase activity
ML1267	GO:0016021	integral component of membrane
ML1267	GO:0055085	transmembrane transport
ML1269	GO:0000162	tryptophan biosynthetic process
ML1269	GO:0004049	anthranilate synthase activity
ML1269	GO:0009058	biosynthetic process
ML1269	GO:0016833	oxo-acid-lyase activity
ML1271	GO:0003824	catalytic activity
ML1271	GO:0004425	indole-3-glycerol-phosphate synthase activity
ML1271	GO:0006568	tryptophan metabolic process
ML1271	GO:0008152	metabolic process
ML1272	GO:0000162	tryptophan biosynthetic process
ML1272	GO:0004834	tryptophan synthase activity
ML1272	GO:0006568	tryptophan metabolic process
ML1273	GO:0003824	catalytic activity
ML1273	GO:0004834	tryptophan synthase activity
ML1273	GO:0006568	tryptophan metabolic process
ML1273	GO:0008152	metabolic process
ML1274	GO:0009249	protein lipoylation
ML1274	GO:0016020	membrane
ML1274	GO:0016757	transferase activity, transferring glycosyl groups
ML1274	GO:0042158	lipoprotein biosynthetic process
ML1277	GO:0000287	magnesium ion binding
ML1277	GO:0003824	catalytic activity
ML1277	GO:0004743	pyruvate kinase activity
ML1277	GO:0006096	glycolytic process
ML1277	GO:0030955	potassium ion binding
ML1286	GO:0000160	phosphorelay signal transduction system
ML1286	GO:0003723	RNA binding
ML1288	GO:0006508	proteolysis
ML1288	GO:0008152	metabolic process
ML1288	GO:0008237	metallopeptidase activity
ML1288	GO:0016787	hydrolase activity
ML1293	GO:0003824	catalytic activity
ML1293	GO:0004152	dihydroorotate dehydrogenase activity
ML1293	GO:0005737	cytoplasm
ML1293	GO:0006207	'de novo' pyrimidine nucleobase biosynthetic process
ML1293	GO:0016020	membrane
ML1293	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML1293	GO:0055114	oxidation-reduction process
ML1297	GO:0016020	membrane
ML1297	GO:0016311	dephosphorylation
ML1297	GO:0050380	undecaprenyl-diphosphatase activity
ML1301	GO:0046854	phosphatidylinositol phosphorylation
ML1302	GO:0010125	mycothiol biosynthetic process
ML1302	GO:0035446	cysteine-glucosaminylinositol ligase activity
ML1304	GO:0003333	amino acid transmembrane transport
ML1304	GO:0006810	transport
ML1304	GO:0006865	amino acid transport
ML1304	GO:0015171	amino acid transmembrane transporter activity
ML1304	GO:0016020	membrane
ML1304	GO:0016021	integral component of membrane
ML1304	GO:0055085	transmembrane transport
ML1305	GO:0003333	amino acid transmembrane transport
ML1305	GO:0006810	transport
ML1305	GO:0006865	amino acid transport
ML1305	GO:0015171	amino acid transmembrane transporter activity
ML1305	GO:0016020	membrane
ML1305	GO:0016021	integral component of membrane
ML1305	GO:0055085	transmembrane transport
ML1307	GO:0005622	intracellular
ML1307	GO:0008270	zinc ion binding
ML1307	GO:0008705	methionine synthase activity
ML1307	GO:0008898	S-adenosylmethionine-homocysteine S-methyltransferase activity
ML1307	GO:0009086	methionine biosynthetic process
ML1307	GO:0031419	cobalamin binding
ML1307	GO:0042558	pteridine-containing compound metabolic process
ML1307	GO:0044237	cellular metabolic process
ML1307	GO:0046872	metal ion binding
ML1309	GO:0000105	histidine biosynthetic process
ML1309	GO:0004636	phosphoribosyl-ATP diphosphatase activity
ML1310	GO:0000105	histidine biosynthetic process
ML1310	GO:0000287	magnesium ion binding
ML1310	GO:0003879	ATP phosphoribosyltransferase activity
ML1310	GO:0005737	cytoplasm
ML1313	GO:0016429	tRNA (adenine-N1-)-methyltransferase activity
ML1313	GO:0030488	tRNA methylation
ML1313	GO:0031515	tRNA (m1A) methyltransferase complex
ML1316	GO:0000502	proteasome complex
ML1316	GO:0005524	ATP binding
ML1316	GO:0010498	proteasomal protein catabolic process
ML1316	GO:0016887	ATPase activity
ML1316	GO:0019941	modification-dependent protein catabolic process
ML1320	GO:0008233	peptidase activity
ML1320	GO:0010498	proteasomal protein catabolic process
ML1320	GO:0016811	hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides
ML1320	GO:0019941	modification-dependent protein catabolic process
ML1322	GO:0004298	threonine-type endopeptidase activity
ML1322	GO:0005839	proteasome core complex
ML1322	GO:0010498	proteasomal protein catabolic process
ML1322	GO:0051603	proteolysis involved in cellular protein catabolic process
ML1323	GO:0004298	threonine-type endopeptidase activity
ML1323	GO:0005839	proteasome core complex
ML1323	GO:0019773	proteasome core complex, alpha-subunit complex
ML1323	GO:0051603	proteolysis involved in cellular protein catabolic process
ML1328	GO:0010498	proteasomal protein catabolic process
ML1328	GO:0016879	ligase activity, forming carbon-nitrogen bonds
ML1328	GO:0019941	modification-dependent protein catabolic process
ML1331	GO:0005886	plasma membrane
ML1331	GO:0008565	protein transporter activity
ML1331	GO:0009306	protein secretion
ML1331	GO:0015031	protein transport
ML1331	GO:0016021	integral component of membrane
ML1332	GO:0016021	integral component of membrane
ML1333	GO:0003676	nucleic acid binding
ML1333	GO:0005524	ATP binding
ML1338	GO:0016758	transferase activity, transferring hexosyl groups
ML1340	GO:0008703	5-amino-6-(5-phosphoribosylamino)uracil reductase activity
ML1340	GO:0009231	riboflavin biosynthetic process
ML1340	GO:0055114	oxidation-reduction process
ML1344	GO:0003677	DNA binding
ML1346	GO:0003824	catalytic activity
ML1346	GO:0008152	metabolic process
ML1351	GO:0003677	DNA binding
ML1351	GO:0003824	catalytic activity
ML1351	GO:0003905	alkylbase DNA N-glycosylase activity
ML1351	GO:0006284	base-excision repair
ML1352	GO:0000166	nucleotide binding
ML1352	GO:0003723	RNA binding
ML1352	GO:0004812	aminoacyl-tRNA ligase activity
ML1352	GO:0004831	tyrosine-tRNA ligase activity
ML1352	GO:0005524	ATP binding
ML1352	GO:0005737	cytoplasm
ML1352	GO:0006418	tRNA aminoacylation for protein translation
ML1352	GO:0006437	tyrosyl-tRNA aminoacylation
ML1358	GO:0003723	RNA binding
ML1358	GO:0008168	methyltransferase activity
ML1358	GO:0032259	methylation
ML1359	GO:0003951	NAD+ kinase activity
ML1359	GO:0006741	NADP biosynthetic process
ML1359	GO:0008152	metabolic process
ML1359	GO:0019674	NAD metabolic process
ML1360	GO:0005524	ATP binding
ML1360	GO:0006281	DNA repair
ML1360	GO:0006310	DNA recombination
ML1361	GO:0004788	thiamine diphosphokinase activity
ML1361	GO:0005524	ATP binding
ML1361	GO:0009229	thiamine diphosphate biosynthetic process
ML1362	GO:0006810	transport
ML1363	GO:0003883	CTP synthase activity
ML1363	GO:0006221	pyrimidine nucleotide biosynthetic process
ML1365	GO:0003677	DNA binding
ML1365	GO:0006310	DNA recombination
ML1365	GO:0009009	site-specific recombinase activity
ML1365	GO:0015074	DNA integration
ML1369	GO:0051304	chromosome separation
ML1370	GO:0001522	pseudouridine synthesis
ML1370	GO:0003723	RNA binding
ML1370	GO:0009451	RNA modification
ML1370	GO:0009982	pseudouridine synthase activity
ML1370	GO:0016866	intramolecular transferase activity
ML1371	GO:0004127	cytidylate kinase activity
ML1371	GO:0005524	ATP binding
ML1371	GO:0006139	nucleobase-containing compound metabolic process
ML1372	GO:0005525	GTP binding
ML1381	GO:0003676	nucleic acid binding
ML1381	GO:0003677	DNA binding
ML1381	GO:0003824	catalytic activity
ML1381	GO:0003887	DNA-directed DNA polymerase activity
ML1381	GO:0006139	nucleobase-containing compound metabolic process
ML1381	GO:0006260	DNA replication
ML1381	GO:0006261	DNA-dependent DNA replication
ML1381	GO:0008408	3'-5' exonuclease activity
ML1382	GO:0003676	nucleic acid binding
ML1382	GO:0003723	RNA binding
ML1382	GO:0003735	structural constituent of ribosome
ML1382	GO:0005840	ribosome
ML1382	GO:0006412	translation
ML1383	GO:0004140	dephospho-CoA kinase activity
ML1383	GO:0005524	ATP binding
ML1383	GO:0015937	coenzyme A biosynthetic process
ML1387	GO:0003677	DNA binding
ML1387	GO:0005515	protein binding
ML1387	GO:0005524	ATP binding
ML1387	GO:0006281	DNA repair
ML1387	GO:0006289	nucleotide-excision repair
ML1387	GO:0009381	excinuclease ABC activity
ML1387	GO:0009432	SOS response
ML1387	GO:0016787	hydrolase activity
ML1390	GO:0006950	response to stress
ML1392	GO:0003824	catalytic activity
ML1392	GO:0005524	ATP binding
ML1392	GO:0006289	nucleotide-excision repair
ML1392	GO:0009380	excinuclease repair complex
ML1392	GO:0009381	excinuclease ABC activity
ML1392	GO:0016887	ATPase activity
ML1393	GO:0000166	nucleotide binding
ML1393	GO:0003676	nucleic acid binding
ML1393	GO:0004812	aminoacyl-tRNA ligase activity
ML1393	GO:0004824	lysine-tRNA ligase activity
ML1393	GO:0005524	ATP binding
ML1393	GO:0005737	cytoplasm
ML1393	GO:0006418	tRNA aminoacylation for protein translation
ML1393	GO:0006430	lysyl-tRNA aminoacylation
ML1394	GO:0003743	translation initiation factor activity
ML1394	GO:0006413	translational initiation
ML1395	GO:0003735	structural constituent of ribosome
ML1395	GO:0005622	intracellular
ML1395	GO:0005840	ribosome
ML1395	GO:0006412	translation
ML1396	GO:0003735	structural constituent of ribosome
ML1396	GO:0005622	intracellular
ML1396	GO:0005840	ribosome
ML1396	GO:0006412	translation
ML1396	GO:0019843	rRNA binding
ML1397	GO:0003723	RNA binding
ML1397	GO:0006396	RNA processing
ML1397	GO:0008168	methyltransferase activity
ML1397	GO:0008173	RNA methyltransferase activity
ML1399	GO:0009190	cyclic nucleotide biosynthetic process
ML1399	GO:0016849	phosphorus-oxygen lyase activity
ML1399	GO:0035556	intracellular signal transduction
ML1401	GO:0000049	tRNA binding
ML1401	GO:0000166	nucleotide binding
ML1401	GO:0004812	aminoacyl-tRNA ligase activity
ML1401	GO:0004826	phenylalanine-tRNA ligase activity
ML1401	GO:0005524	ATP binding
ML1401	GO:0005737	cytoplasm
ML1401	GO:0006432	phenylalanyl-tRNA aminoacylation
ML1401	GO:0043039	tRNA aminoacylation
ML1402	GO:0000049	tRNA binding
ML1402	GO:0000287	magnesium ion binding
ML1402	GO:0003723	RNA binding
ML1402	GO:0004826	phenylalanine-tRNA ligase activity
ML1402	GO:0005524	ATP binding
ML1402	GO:0005737	cytoplasm
ML1402	GO:0006432	phenylalanyl-tRNA aminoacylation
ML1402	GO:0008033	tRNA processing
ML1406	GO:0003942	N-acetyl-gamma-glutamyl-phosphate reductase activity
ML1406	GO:0005737	cytoplasm
ML1406	GO:0006526	arginine biosynthetic process
ML1406	GO:0008652	cellular amino acid biosynthetic process
ML1406	GO:0016620	oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
ML1406	GO:0046983	protein dimerization activity
ML1406	GO:0051287	NAD binding
ML1406	GO:0055114	oxidation-reduction process
ML1407	GO:0004358	glutamate N-acetyltransferase activity
ML1407	GO:0006526	arginine biosynthetic process
ML1408	GO:0003991	acetylglutamate kinase activity
ML1408	GO:0005737	cytoplasm
ML1408	GO:0006526	arginine biosynthetic process
ML1409	GO:0003824	catalytic activity
ML1409	GO:0006525	arginine metabolic process
ML1409	GO:0008483	transaminase activity
ML1409	GO:0030170	pyridoxal phosphate binding
ML1410	GO:0004585	ornithine carbamoyltransferase activity
ML1410	GO:0006520	cellular amino acid metabolic process
ML1410	GO:0006591	ornithine metabolic process
ML1410	GO:0016597	amino acid binding
ML1410	GO:0016743	carboxyl- or carbamoyltransferase activity
ML1411	GO:0003700	sequence-specific DNA binding transcription factor activity
ML1411	GO:0006355	regulation of transcription, DNA-templated
ML1411	GO:0006525	arginine metabolic process
ML1411	GO:0034618	arginine binding
ML1411	GO:0051259	protein oligomerization
ML1412	GO:0004055	argininosuccinate synthase activity
ML1412	GO:0005524	ATP binding
ML1412	GO:0006526	arginine biosynthetic process
ML1413	GO:0003824	catalytic activity
ML1413	GO:0004056	argininosuccinate lyase activity
ML1413	GO:0042450	arginine biosynthetic process via ornithine
ML1417	GO:0003824	catalytic activity
ML1417	GO:0008654	phospholipid biosynthetic process
ML1417	GO:0008715	CDP-diacylglycerol diphosphatase activity
ML1417	GO:0016020	membrane
ML1418	GO:0016209	antioxidant activity
ML1418	GO:0016491	oxidoreductase activity
ML1418	GO:0055114	oxidation-reduction process
ML1419	GO:0006355	regulation of transcription, DNA-templated
ML1423	GO:0006629	lipid metabolic process
ML1423	GO:0008152	metabolic process
ML1424	GO:0005215	transporter activity
ML1424	GO:0005524	ATP binding
ML1424	GO:0006810	transport
ML1424	GO:0016820	hydrolase activity, acting on acid anhydrides, catalyzing transmembrane movement of substances
ML1424	GO:0016887	ATPase activity
ML1424	GO:0043190	ATP-binding cassette (ABC) transporter complex
ML1425	GO:0006810	transport
ML1425	GO:0016020	membrane
ML1426	GO:0006810	transport
ML1426	GO:0016020	membrane
ML1427	GO:0005215	transporter activity
ML1427	GO:0006810	transport
ML1439	GO:0001000	bacterial-type RNA polymerase core enzyme binding
ML1439	GO:0045893	positive regulation of transcription, DNA-templated
ML1441	GO:0006807	nitrogen compound metabolic process
ML1441	GO:0016021	integral component of membrane
ML1441	GO:0016410	N-acyltransferase activity
ML1441	GO:0016810	hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds
ML1441	GO:0042158	lipoprotein biosynthetic process
ML1444	GO:0016787	hydrolase activity
ML1446	GO:0004733	pyridoxamine-phosphate oxidase activity
ML1446	GO:0010181	FMN binding
ML1446	GO:0016491	oxidoreductase activity
ML1446	GO:0055114	oxidation-reduction process
ML1448	GO:0003677	DNA binding
ML1448	GO:0003700	sequence-specific DNA binding transcription factor activity
ML1448	GO:0006352	DNA-templated transcription, initiation
ML1448	GO:0006355	regulation of transcription, DNA-templated
ML1448	GO:0016987	sigma factor activity
ML1452	GO:0003824	catalytic activity
ML1452	GO:0008152	metabolic process
ML1454	GO:0003824	catalytic activity
ML1454	GO:0009058	biosynthetic process
ML1454	GO:0009435	NAD biosynthetic process
ML1454	GO:0016779	nucleotidyltransferase activity
ML1458	GO:0004350	glutamate-5-semialdehyde dehydrogenase activity
ML1458	GO:0006561	proline biosynthetic process
ML1458	GO:0008152	metabolic process
ML1458	GO:0016491	oxidoreductase activity
ML1458	GO:0016620	oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
ML1458	GO:0050661	NADP binding
ML1458	GO:0055114	oxidation-reduction process
ML1463	GO:0003952	NAD+ synthase (glutamine-hydrolyzing) activity
ML1463	GO:0005524	ATP binding
ML1463	GO:0006807	nitrogen compound metabolic process
ML1463	GO:0009435	NAD biosynthetic process
ML1463	GO:0016810	hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds
ML1464	GO:0003723	RNA binding
ML1464	GO:0004349	glutamate 5-kinase activity
ML1464	GO:0005737	cytoplasm
ML1464	GO:0006561	proline biosynthetic process
ML1465	GO:0000166	nucleotide binding
ML1465	GO:0000287	magnesium ion binding
ML1465	GO:0003924	GTPase activity
ML1465	GO:0005525	GTP binding
ML1466	GO:0003735	structural constituent of ribosome
ML1466	GO:0005622	intracellular
ML1466	GO:0005840	ribosome
ML1466	GO:0006412	translation
ML1467	GO:0003723	RNA binding
ML1467	GO:0003735	structural constituent of ribosome
ML1467	GO:0005622	intracellular
ML1467	GO:0005840	ribosome
ML1467	GO:0006412	translation
ML1468	GO:0003723	RNA binding
ML1468	GO:0004540	ribonuclease activity
ML1468	GO:0006396	RNA processing
ML1469	GO:0004550	nucleoside diphosphate kinase activity
ML1469	GO:0006165	nucleoside diphosphate phosphorylation
ML1469	GO:0006183	GTP biosynthetic process
ML1469	GO:0006228	UTP biosynthetic process
ML1469	GO:0006241	CTP biosynthetic process
ML1471	GO:0004326	tetrahydrofolylpolyglutamate synthase activity
ML1471	GO:0005524	ATP binding
ML1471	GO:0009058	biosynthetic process
ML1471	GO:0009396	folic acid-containing compound biosynthetic process
ML1471	GO:0016874	ligase activity
ML1472	GO:0000166	nucleotide binding
ML1472	GO:0002161	aminoacyl-tRNA editing activity
ML1472	GO:0004812	aminoacyl-tRNA ligase activity
ML1472	GO:0004832	valine-tRNA ligase activity
ML1472	GO:0005524	ATP binding
ML1472	GO:0005737	cytoplasm
ML1472	GO:0006418	tRNA aminoacylation for protein translation
ML1472	GO:0006438	valyl-tRNA aminoacylation
ML1477	GO:0005524	ATP binding
ML1477	GO:0006457	protein folding
ML1477	GO:0008270	zinc ion binding
ML1477	GO:0046983	protein dimerization activity
ML1477	GO:0051082	unfolded protein binding
ML1479	GO:0004252	serine-type endopeptidase activity
ML1479	GO:0006508	proteolysis
ML1480	GO:0004252	serine-type endopeptidase activity
ML1480	GO:0006508	proteolysis
ML1481	GO:0006457	protein folding
ML1481	GO:0015031	protein transport
ML1484	GO:0004751	ribose-5-phosphate isomerase activity
ML1484	GO:0005975	carbohydrate metabolic process
ML1484	GO:0016853	isomerase activity
ML1485	GO:0015035	protein disulfide oxidoreductase activity
ML1486	GO:0004177	aminopeptidase activity
ML1486	GO:0006508	proteolysis
ML1486	GO:0008237	metallopeptidase activity
ML1486	GO:0008270	zinc ion binding
ML1488	GO:0003824	catalytic activity
ML1488	GO:0009058	biosynthetic process
ML1488	GO:0030170	pyridoxal phosphate binding
ML1489	GO:0009055	electron carrier activity
ML1492	GO:0003824	catalytic activity
ML1492	GO:0009108	coenzyme biosynthetic process
ML1492	GO:0016765	transferase activity, transferring alkyl or aryl (other than methyl) groups
ML1492	GO:0051536	iron-sulfur cluster binding
ML1492	GO:0051539	4 iron, 4 sulfur cluster binding
ML1495	GO:0035595	N-acetylglucosaminylinositol deacetylase activity
ML1498	GO:0003924	GTPase activity
ML1498	GO:0005525	GTP binding
ML1503A	GO:0006729	tetrahydrobiopterin biosynthetic process
ML1503A	GO:0008124	4-alpha-hydroxytetrahydrobiopterin dehydratase activity
ML1504	GO:0016758	transferase activity, transferring hexosyl groups
ML1508	GO:0004733	pyridoxamine-phosphate oxidase activity
ML1508	GO:0010181	FMN binding
ML1508	GO:0016491	oxidoreductase activity
ML1508	GO:0055114	oxidation-reduction process
ML1511	GO:0036054	protein-malonyllysine demalonylase activity
ML1511	GO:0036055	protein-succinyllysine desuccinylase activity
ML1511	GO:0070403	NAD+ binding
ML1512	GO:0003723	RNA binding
ML1512	GO:0004521	endoribonuclease activity
ML1512	GO:0004534	5'-3' exoribonuclease activity
ML1512	GO:0006396	RNA processing
ML1512	GO:0008270	zinc ion binding
ML1512	GO:0046872	metal ion binding
ML1512	GO:0090501	RNA phosphodiester bond hydrolysis
ML1513	GO:0003824	catalytic activity
ML1513	GO:0008152	metabolic process
ML1513	GO:0008840	4-hydroxy-tetrahydrodipicolinate synthase
ML1513	GO:0009089	lysine biosynthetic process via diaminopimelate
ML1513	GO:0016829	lyase activity
ML1514	GO:0006231	dTMP biosynthetic process
ML1514	GO:0050660	flavin adenine dinucleotide binding
ML1514	GO:0050797	thymidylate synthase (FAD) activity
ML1518	GO:0004146	dihydrofolate reductase activity
ML1518	GO:0006545	glycine biosynthetic process
ML1518	GO:0009165	nucleotide biosynthetic process
ML1518	GO:0050661	NADP binding
ML1518	GO:0055114	oxidation-reduction process
ML1519	GO:0004799	thymidylate synthase activity
ML1519	GO:0006231	dTMP biosynthetic process
ML1526	GO:0005515	protein binding
ML1532	GO:0000286	alanine dehydrogenase activity
ML1532	GO:0016491	oxidoreductase activity
ML1532	GO:0042853	L-alanine catabolic process
ML1532	GO:0055114	oxidation-reduction process
ML1536	GO:0005515	protein binding
ML1536	GO:0005524	ATP binding
ML1538	GO:0004252	serine-type endopeptidase activity
ML1538	GO:0006508	proteolysis
ML1543	GO:0000166	nucleotide binding
ML1543	GO:0003677	DNA binding
ML1543	GO:0005524	ATP binding
ML1546	GO:0001522	pseudouridine synthesis
ML1546	GO:0003723	RNA binding
ML1546	GO:0006396	RNA processing
ML1546	GO:0009451	RNA modification
ML1546	GO:0009982	pseudouridine synthase activity
ML1547	GO:0000287	magnesium ion binding
ML1547	GO:0008897	holo-[acyl-carrier-protein] synthase activity
ML1547	GO:0009239	enterobactin biosynthetic process
ML1547	GO:0009366	enterobactin synthetase complex
ML1547	GO:0016780	phosphotransferase activity, for other substituted phosphate groups
ML1548	GO:0016787	hydrolase activity
ML1553	GO:0000166	nucleotide binding
ML1553	GO:0004812	aminoacyl-tRNA ligase activity
ML1553	GO:0004827	proline-tRNA ligase activity
ML1553	GO:0005524	ATP binding
ML1553	GO:0005737	cytoplasm
ML1553	GO:0006418	tRNA aminoacylation for protein translation
ML1553	GO:0006433	prolyl-tRNA aminoacylation
ML1555	GO:0006364	rRNA processing
ML1556	GO:0003743	translation initiation factor activity
ML1556	GO:0003924	GTPase activity
ML1556	GO:0005525	GTP binding
ML1556	GO:0005622	intracellular
ML1556	GO:0006413	translational initiation
ML1558	GO:0003700	sequence-specific DNA binding transcription factor activity
ML1558	GO:0003723	RNA binding
ML1558	GO:0006353	DNA-templated transcription, termination
ML1558	GO:0031554	regulation of DNA-templated transcription, termination
ML1558	GO:0031564	transcription antitermination
ML1562	GO:0016021	integral component of membrane
ML1562	GO:0055085	transmembrane transport
ML1572	GO:0003824	catalytic activity
ML1572	GO:0008152	metabolic process
ML1573	GO:0006541	glutamine metabolic process
ML1573	GO:0016787	hydrolase activity
ML1576	GO:0004177	aminopeptidase activity
ML1576	GO:0006508	proteolysis
ML1576	GO:0008235	metalloexopeptidase activity
ML1577	GO:0008658	penicillin binding
ML1577	GO:0046677	response to antibiotic
ML1581	GO:0003824	catalytic activity
ML1581	GO:0005506	iron ion binding
ML1581	GO:0008299	isoprenoid biosynthetic process
ML1581	GO:0016114	terpenoid biosynthetic process
ML1581	GO:0044237	cellular metabolic process
ML1581	GO:0046429	4-hydroxy-3-methylbut-2-en-1-yl diphosphate synthase activity
ML1581	GO:0055114	oxidation-reduction process
ML1582	GO:0004222	metalloendopeptidase activity
ML1582	GO:0005515	protein binding
ML1582	GO:0006508	proteolysis
ML1583	GO:0005515	protein binding
ML1583	GO:0008299	isoprenoid biosynthetic process
ML1583	GO:0030604	1-deoxy-D-xylulose-5-phosphate reductoisomerase activity
ML1583	GO:0046872	metal ion binding
ML1583	GO:0055114	oxidation-reduction process
ML1583	GO:0070402	NADPH binding
ML1589	GO:0016020	membrane
ML1589	GO:0016772	transferase activity, transferring phosphorus-containing groups
ML1590	GO:0006412	translation
ML1591	GO:0005737	cytoplasm
ML1591	GO:0006221	pyrimidine nucleotide biosynthetic process
ML1591	GO:0009041	uridylate kinase activity
ML1591	GO:0033862	UMP kinase activity
ML1597	GO:0003746	translation elongation factor activity
ML1597	GO:0005515	protein binding
ML1597	GO:0005622	intracellular
ML1597	GO:0006414	translational elongation
ML1598	GO:0003735	structural constituent of ribosome
ML1598	GO:0005622	intracellular
ML1598	GO:0005840	ribosome
ML1598	GO:0006412	translation
ML1598	GO:0015935	small ribosomal subunit
ML1600	GO:0003677	DNA binding
ML1600	GO:0006310	DNA recombination
ML1600	GO:0015074	DNA integration
ML1601	GO:0003824	catalytic activity
ML1601	GO:0009058	biosynthetic process
ML1607	GO:0003676	nucleic acid binding
ML1607	GO:0004518	nuclease activity
ML1611	GO:0003676	nucleic acid binding
ML1611	GO:0004523	RNA-DNA hybrid ribonuclease activity
ML1612	GO:0006508	proteolysis
ML1612	GO:0008236	serine-type peptidase activity
ML1612	GO:0016020	membrane
ML1612	GO:0016021	integral component of membrane
ML1613	GO:0003735	structural constituent of ribosome
ML1613	GO:0005622	intracellular
ML1613	GO:0005840	ribosome
ML1613	GO:0006412	translation
ML1615	GO:0008033	tRNA processing
ML1615	GO:0052906	tRNA (guanine(37)-N(1))-methyltransferase activity
ML1616	GO:0005840	ribosome
ML1616	GO:0006364	rRNA processing
ML1616	GO:0043022	ribosome binding
ML1617	GO:0003723	RNA binding
ML1618	GO:0003735	structural constituent of ribosome
ML1618	GO:0005622	intracellular
ML1618	GO:0005840	ribosome
ML1618	GO:0006412	translation
ML1622	GO:0003924	GTPase activity
ML1622	GO:0005525	GTP binding
ML1622	GO:0006614	SRP-dependent cotranslational protein targeting to membrane
ML1622	GO:0008312	7S RNA binding
ML1622	GO:0048500	signal recognition particle
ML1623	GO:0005524	ATP binding
ML1623	GO:0006457	protein folding
ML1623	GO:0006950	response to stress
ML1623	GO:0051082	unfolded protein binding
ML1624	GO:0003677	DNA binding
ML1624	GO:0005524	ATP binding
ML1624	GO:0016787	hydrolase activity
ML1628	GO:0005525	GTP binding
ML1628	GO:0006614	SRP-dependent cotranslational protein targeting to membrane
ML1629	GO:0005515	protein binding
ML1629	GO:0005524	ATP binding
ML1629	GO:0005694	chromosome
ML1629	GO:0007062	sister chromatid cohesion
ML1629	GO:0030261	chromosome condensation
ML1629	GO:0051276	chromosome organization
ML1630	GO:0008882	[glutamate-ammonia-ligase] adenylyltransferase activity
ML1630	GO:0016779	nucleotidyltransferase activity
ML1631	GO:0003824	catalytic activity
ML1631	GO:0004356	glutamate-ammonia ligase activity
ML1631	GO:0005737	cytoplasm
ML1631	GO:0006542	glutamine biosynthetic process
ML1631	GO:0006807	nitrogen compound metabolic process
ML1631	GO:0009399	nitrogen fixation
ML1635	GO:0003824	catalytic activity
ML1635	GO:0003864	3-methyl-2-oxobutanoate hydroxymethyltransferase activity
ML1635	GO:0015940	pantothenate biosynthetic process
ML1637	GO:0003676	nucleic acid binding
ML1644	GO:0016020	membrane
ML1651	GO:0003824	catalytic activity
ML1651	GO:0008152	metabolic process
ML1651	GO:0016491	oxidoreductase activity
ML1651	GO:0055114	oxidation-reduction process
ML1652	GO:0003677	DNA binding
ML1653	GO:0003824	catalytic activity
ML1653	GO:0008152	metabolic process
ML1653	GO:0016740	transferase activity
ML1654	GO:0006633	fatty acid biosynthetic process
ML1655	GO:0003824	catalytic activity
ML1655	GO:0008152	metabolic process
ML1656	GO:0003824	catalytic activity
ML1656	GO:0008152	metabolic process
ML1658	GO:0003676	nucleic acid binding
ML1658	GO:0003677	DNA binding
ML1658	GO:0003684	damaged DNA binding
ML1658	GO:0003906	DNA-(apurinic or apyrimidinic site) lyase activity
ML1658	GO:0006281	DNA repair
ML1658	GO:0006284	base-excision repair
ML1658	GO:0006289	nucleotide-excision repair
ML1658	GO:0008270	zinc ion binding
ML1658	GO:0008534	oxidized purine nucleobase lesion DNA N-glycosylase activity
ML1658	GO:0016799	hydrolase activity, hydrolyzing N-glycosyl compounds
ML1659	GO:0003723	RNA binding
ML1659	GO:0004525	ribonuclease III activity
ML1659	GO:0006396	RNA processing
ML1659	GO:0016075	rRNA catabolic process
ML1663	GO:0003824	catalytic activity
ML1663	GO:0004595	pantetheine-phosphate adenylyltransferase activity
ML1663	GO:0009058	biosynthetic process
ML1663	GO:0015937	coenzyme A biosynthetic process
ML1664	GO:0008168	methyltransferase activity
ML1664	GO:0031167	rRNA methylation
ML1669	GO:0016491	oxidoreductase activity
ML1669	GO:0055114	oxidation-reduction process
ML1671	GO:0003676	nucleic acid binding
ML1671	GO:0004003	ATP-dependent DNA helicase activity
ML1671	GO:0005524	ATP binding
ML1671	GO:0006281	DNA repair
ML1671	GO:0006310	DNA recombination
ML1675	GO:0004844	uracil DNA N-glycosylase activity
ML1675	GO:0006281	DNA repair
ML1675	GO:0006284	base-excision repair
ML1675	GO:0016799	hydrolase activity, hydrolyzing N-glycosyl compounds
ML1676	GO:0009030	thiamine-phosphate kinase activity
ML1676	GO:0009228	thiamine biosynthetic process
ML1678	GO:0003824	catalytic activity
ML1678	GO:0005524	ATP binding
ML1678	GO:0005737	cytoplasm
ML1678	GO:0008716	D-alanine-D-alanine ligase activity
ML1679	GO:0004367	glycerol-3-phosphate dehydrogenase [NAD+] activity
ML1679	GO:0005975	carbohydrate metabolic process
ML1679	GO:0006072	glycerol-3-phosphate metabolic process
ML1679	GO:0009331	glycerol-3-phosphate dehydrogenase complex
ML1679	GO:0016491	oxidoreductase activity
ML1679	GO:0016616	oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
ML1679	GO:0046168	glycerol-3-phosphate catabolic process
ML1679	GO:0051287	NAD binding
ML1679	GO:0055114	oxidation-reduction process
ML1680	GO:0016779	nucleotidyltransferase activity
ML1681	GO:0006799	polyphosphate biosynthetic process
ML1681	GO:0008976	polyphosphate kinase activity
ML1681	GO:0009358	polyphosphate kinase complex
ML1682	GO:0016787	hydrolase activity
ML1683	GO:0003677	DNA binding
ML1684	GO:0003861	3-isopropylmalate dehydratase activity
ML1684	GO:0008152	metabolic process
ML1684	GO:0009098	leucine biosynthetic process
ML1684	GO:0009316	3-isopropylmalate dehydratase complex
ML1685	GO:0003861	3-isopropylmalate dehydratase activity
ML1685	GO:0008152	metabolic process
ML1685	GO:0009098	leucine biosynthetic process
ML1685	GO:0051539	4 iron, 4 sulfur cluster binding
ML1687	GO:0010181	FMN binding
ML1687	GO:0016491	oxidoreductase activity
ML1687	GO:0055114	oxidation-reduction process
ML1688	GO:0000049	tRNA binding
ML1688	GO:0000166	nucleotide binding
ML1688	GO:0004812	aminoacyl-tRNA ligase activity
ML1688	GO:0004818	glutamate-tRNA ligase activity
ML1688	GO:0005524	ATP binding
ML1688	GO:0005737	cytoplasm
ML1688	GO:0006418	tRNA aminoacylation for protein translation
ML1688	GO:0006424	glutamyl-tRNA aminoacylation
ML1688	GO:0016876	ligase activity, forming aminoacyl-tRNA and related compounds
ML1688	GO:0043039	tRNA aminoacylation
ML1689	GO:0003824	catalytic activity
ML1689	GO:0008152	metabolic process
ML1691	GO:0000287	magnesium ion binding
ML1691	GO:0003862	3-isopropylmalate dehydrogenase activity
ML1691	GO:0009098	leucine biosynthetic process
ML1691	GO:0016616	oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
ML1691	GO:0051287	NAD binding
ML1691	GO:0055114	oxidation-reduction process
ML1692	GO:0004617	phosphoglycerate dehydrogenase activity
ML1692	GO:0006564	L-serine biosynthetic process
ML1692	GO:0008152	metabolic process
ML1692	GO:0016597	amino acid binding
ML1692	GO:0016616	oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
ML1692	GO:0051287	NAD binding
ML1692	GO:0055114	oxidation-reduction process
ML1694	GO:0004455	ketol-acid reductoisomerase activity
ML1694	GO:0009082	branched-chain amino acid biosynthetic process
ML1694	GO:0016491	oxidoreductase activity
ML1694	GO:0055114	oxidation-reduction process
ML1695	GO:0003984	acetolactate synthase activity
ML1695	GO:0009082	branched-chain amino acid biosynthetic process
ML1696	GO:0000287	magnesium ion binding
ML1696	GO:0003824	catalytic activity
ML1696	GO:0003984	acetolactate synthase activity
ML1696	GO:0009082	branched-chain amino acid biosynthetic process
ML1696	GO:0030976	thiamine pyrophosphate binding
ML1696	GO:0050660	flavin adenine dinucleotide binding
ML1699	GO:0003824	catalytic activity
ML1699	GO:0005975	carbohydrate metabolic process
ML1699	GO:0016901	oxidoreductase activity, acting on the CH-OH group of donors, quinone or similar compound as acceptor
ML1699	GO:0048038	quinone binding
ML1700	GO:0016874	ligase activity
ML1700	GO:0016884	carbon-nitrogen ligase activity, with glutamine as amido-N-donor
ML1701	GO:0003872	6-phosphofructokinase activity
ML1701	GO:0005524	ATP binding
ML1701	GO:0006002	fructose 6-phosphate metabolic process
ML1701	GO:0006096	glycolytic process
ML1701	GO:0008443	phosphofructokinase activity
ML1701	GO:0047334	diphosphate-fructose-6-phosphate 1-phosphotransferase activity
ML1702	GO:0006412	translation
ML1703	GO:0006450	regulation of translational fidelity
ML1705	GO:0003911	DNA ligase (NAD+) activity
ML1705	GO:0006260	DNA replication
ML1705	GO:0006281	DNA repair
ML1706	GO:0003871	5-methyltetrahydropteroyltriglutamate-homocysteine S-methyltransferase activity
ML1706	GO:0008270	zinc ion binding
ML1706	GO:0009086	methionine biosynthetic process
ML1707	GO:0008033	tRNA processing
ML1707	GO:0016740	transferase activity
ML1707	GO:0016783	sulfurtransferase activity
ML1708	GO:0003824	catalytic activity
ML1711	GO:0009055	electron carrier activity
ML1711	GO:0050660	flavin adenine dinucleotide binding
ML1712	GO:0009055	electron carrier activity
ML1713	GO:0008152	metabolic process
ML1713	GO:0008168	methyltransferase activity
ML1714	GO:0003824	catalytic activity
ML1714	GO:0005975	carbohydrate metabolic process
ML1723	GO:0008152	metabolic process
ML1723	GO:0008168	methyltransferase activity
ML1724	GO:0003824	catalytic activity
ML1724	GO:0008152	metabolic process
ML1725	GO:0016787	hydrolase activity
ML1726	GO:0005524	ATP binding
ML1726	GO:0016887	ATPase activity
ML1727	GO:0004647	phosphoserine phosphatase activity
ML1727	GO:0006564	L-serine biosynthetic process
ML1727	GO:0008152	metabolic process
ML1727	GO:0016791	phosphatase activity
ML1728	GO:0004129	cytochrome-c oxidase activity
ML1728	GO:0005506	iron ion binding
ML1728	GO:0005507	copper ion binding
ML1728	GO:0005886	plasma membrane
ML1728	GO:0006810	transport
ML1728	GO:0009055	electron carrier activity
ML1728	GO:0009060	aerobic respiration
ML1728	GO:0016021	integral component of membrane
ML1728	GO:0020037	heme binding
ML1728	GO:0022900	electron transport chain
ML1728	GO:0055114	oxidation-reduction process
ML1729	GO:0005488	binding
ML1730	GO:0008270	zinc ion binding
ML1730	GO:0016491	oxidoreductase activity
ML1730	GO:0055114	oxidation-reduction process
ML1731	GO:0005971	ribonucleoside-diphosphate reductase complex
ML1731	GO:0009186	deoxyribonucleoside diphosphate metabolic process
ML1731	GO:0009263	deoxyribonucleotide biosynthetic process
ML1731	GO:0016491	oxidoreductase activity
ML1731	GO:0055114	oxidation-reduction process
ML1733	GO:0003677	DNA binding
ML1734	GO:0004748	ribonucleoside-diphosphate reductase activity, thioredoxin disulfide as acceptor
ML1734	GO:0005524	ATP binding
ML1734	GO:0006260	DNA replication
ML1734	GO:0055114	oxidation-reduction process
ML1736	GO:0009055	electron carrier activity
ML1736	GO:0015035	protein disulfide oxidoreductase activity
ML1736	GO:0045454	cell redox homeostasis
ML1740	GO:0016491	oxidoreductase activity
ML1750	GO:0005515	protein binding
ML1751	GO:0008641	small protein activating enzyme activity
ML1751	GO:0016491	oxidoreductase activity
ML1753	GO:0003677	DNA binding
ML1753	GO:0005515	protein binding
ML1753	GO:0006355	regulation of transcription, DNA-templated
ML1753	GO:0009190	cyclic nucleotide biosynthetic process
ML1753	GO:0016849	phosphorus-oxygen lyase activity
ML1753	GO:0035556	intracellular signal transduction
ML1755	GO:0003941	L-serine ammonia-lyase activity
ML1755	GO:0006094	gluconeogenesis
ML1755	GO:0051539	4 iron, 4 sulfur cluster binding
ML1756	GO:0016021	integral component of membrane
ML1764	GO:0006813	potassium ion transport
ML1768	GO:0006810	transport
ML1768	GO:0016020	membrane
ML1769	GO:0006810	transport
ML1769	GO:0016020	membrane
ML1770	GO:0005215	transporter activity
ML1770	GO:0006810	transport
ML1784	GO:0008270	zinc ion binding
ML1784	GO:0016491	oxidoreductase activity
ML1784	GO:0055114	oxidation-reduction process
ML1787	GO:0005506	iron ion binding
ML1787	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML1787	GO:0020037	heme binding
ML1787	GO:0055114	oxidation-reduction process
ML1794	GO:0003824	catalytic activity
ML1794	GO:0009058	biosynthetic process
ML1794	GO:0030170	pyridoxal phosphate binding
ML1798	GO:0003924	GTPase activity
ML1798	GO:0005525	GTP binding
ML1799	GO:0003824	catalytic activity
ML1799	GO:0004494	methylmalonyl-CoA mutase activity
ML1799	GO:0008152	metabolic process
ML1799	GO:0016853	isomerase activity
ML1799	GO:0016866	intramolecular transferase activity
ML1799	GO:0031419	cobalamin binding
ML1799	GO:0046872	metal ion binding
ML1800	GO:0003824	catalytic activity
ML1800	GO:0004494	methylmalonyl-CoA mutase activity
ML1800	GO:0008152	metabolic process
ML1800	GO:0016866	intramolecular transferase activity
ML1800	GO:0019652	lactate fermentation to propionate and acetate
ML1800	GO:0031419	cobalamin binding
ML1800	GO:0046872	metal ion binding
ML1802	GO:0016020	membrane
ML1805	GO:0004325	ferrochelatase activity
ML1805	GO:0006783	heme biosynthetic process
ML1806	GO:0004318	enoyl-[acyl-carrier-protein] reductase (NADH) activity
ML1806	GO:0006633	fatty acid biosynthetic process
ML1806	GO:0055114	oxidation-reduction process
ML1807	GO:0016491	oxidoreductase activity
ML1810	GO:0005524	ATP binding
ML1810	GO:0016887	ATPase activity
ML1814	GO:0008152	metabolic process
ML1816	GO:0005524	ATP binding
ML1816	GO:0016887	ATPase activity
ML1818	GO:0045454	cell redox homeostasis
ML1831	GO:0004177	aminopeptidase activity
ML1831	GO:0006508	proteolysis
ML1831	GO:0008235	metalloexopeptidase activity
ML1832	GO:0004017	adenylate kinase activity
ML1832	GO:0005524	ATP binding
ML1832	GO:0006139	nucleobase-containing compound metabolic process
ML1832	GO:0016776	phosphotransferase activity, phosphate group as acceptor
ML1832	GO:0019205	nucleobase-containing compound kinase activity
ML1833	GO:0015031	protein transport
ML1833	GO:0016020	membrane
ML1835	GO:0003918	DNA topoisomerase type II (ATP-hydrolyzing) activity
ML1835	GO:0005524	ATP binding
ML1839	GO:0004252	serine-type endopeptidase activity
ML1839	GO:0006465	signal peptide processing
ML1839	GO:0006508	proteolysis
ML1839	GO:0008233	peptidase activity
ML1839	GO:0016021	integral component of membrane
ML1840	GO:0003735	structural constituent of ribosome
ML1840	GO:0005622	intracellular
ML1840	GO:0005840	ribosome
ML1840	GO:0006412	translation
ML1840	GO:0015934	large ribosomal subunit
ML1841	GO:0003735	structural constituent of ribosome
ML1841	GO:0006412	translation
ML1841	GO:0015934	large ribosomal subunit
ML1842	GO:0003723	RNA binding
ML1842	GO:0003735	structural constituent of ribosome
ML1842	GO:0005840	ribosome
ML1842	GO:0006412	translation
ML1842	GO:0015935	small ribosomal subunit
ML1843	GO:0003735	structural constituent of ribosome
ML1843	GO:0005622	intracellular
ML1843	GO:0005840	ribosome
ML1843	GO:0006412	translation
ML1844	GO:0003735	structural constituent of ribosome
ML1844	GO:0005622	intracellular
ML1844	GO:0005840	ribosome
ML1844	GO:0006412	translation
ML1844	GO:0019843	rRNA binding
ML1845	GO:0003735	structural constituent of ribosome
ML1845	GO:0005840	ribosome
ML1845	GO:0006412	translation
ML1846	GO:0003735	structural constituent of ribosome
ML1846	GO:0005622	intracellular
ML1846	GO:0005840	ribosome
ML1846	GO:0006412	translation
ML1847	GO:0003735	structural constituent of ribosome
ML1847	GO:0005622	intracellular
ML1847	GO:0005840	ribosome
ML1847	GO:0006412	translation
ML1848	GO:0003735	structural constituent of ribosome
ML1848	GO:0005622	intracellular
ML1848	GO:0005840	ribosome
ML1848	GO:0006412	translation
ML1849	GO:0003735	structural constituent of ribosome
ML1849	GO:0005840	ribosome
ML1849	GO:0006412	translation
ML1849	GO:0015934	large ribosomal subunit
ML1854	GO:0003735	structural constituent of ribosome
ML1854	GO:0005622	intracellular
ML1854	GO:0005840	ribosome
ML1854	GO:0006412	translation
ML1855	GO:0003735	structural constituent of ribosome
ML1855	GO:0005622	intracellular
ML1855	GO:0005840	ribosome
ML1855	GO:0006412	translation
ML1856	GO:0003735	structural constituent of ribosome
ML1856	GO:0005622	intracellular
ML1856	GO:0005840	ribosome
ML1856	GO:0006412	translation
ML1856	GO:0019843	rRNA binding
ML1857	GO:0003676	nucleic acid binding
ML1857	GO:0003723	RNA binding
ML1857	GO:0003735	structural constituent of ribosome
ML1857	GO:0005840	ribosome
ML1857	GO:0006412	translation
ML1857	GO:0015935	small ribosomal subunit
ML1858	GO:0003735	structural constituent of ribosome
ML1858	GO:0005622	intracellular
ML1858	GO:0005840	ribosome
ML1858	GO:0006412	translation
ML1858	GO:0015934	large ribosomal subunit
ML1859	GO:0003723	RNA binding
ML1859	GO:0003735	structural constituent of ribosome
ML1859	GO:0005840	ribosome
ML1859	GO:0006412	translation
ML1859	GO:0015935	small ribosomal subunit
ML1860	GO:0003723	RNA binding
ML1860	GO:0003735	structural constituent of ribosome
ML1860	GO:0005622	intracellular
ML1860	GO:0005840	ribosome
ML1860	GO:0006412	translation
ML1860	GO:0015934	large ribosomal subunit
ML1860	GO:0016740	transferase activity
ML1861	GO:0000166	nucleotide binding
ML1861	GO:0003735	structural constituent of ribosome
ML1861	GO:0005622	intracellular
ML1861	GO:0005840	ribosome
ML1861	GO:0006412	translation
ML1862	GO:0003735	structural constituent of ribosome
ML1862	GO:0005840	ribosome
ML1862	GO:0006412	translation
ML1863	GO:0003735	structural constituent of ribosome
ML1863	GO:0005622	intracellular
ML1863	GO:0005840	ribosome
ML1863	GO:0006412	translation
ML1864	GO:0003723	RNA binding
ML1864	GO:0003735	structural constituent of ribosome
ML1864	GO:0005622	intracellular
ML1864	GO:0005840	ribosome
ML1864	GO:0006412	translation
ML1877	GO:0003746	translation elongation factor activity
ML1877	GO:0003924	GTPase activity
ML1877	GO:0005525	GTP binding
ML1877	GO:0005622	intracellular
ML1877	GO:0006414	translational elongation
ML1878	GO:0003746	translation elongation factor activity
ML1878	GO:0003924	GTPase activity
ML1878	GO:0005525	GTP binding
ML1878	GO:0005622	intracellular
ML1878	GO:0006414	translational elongation
ML1879	GO:0003723	RNA binding
ML1879	GO:0003735	structural constituent of ribosome
ML1879	GO:0006412	translation
ML1879	GO:0015935	small ribosomal subunit
ML1880	GO:0003735	structural constituent of ribosome
ML1880	GO:0005622	intracellular
ML1880	GO:0005840	ribosome
ML1880	GO:0006412	translation
ML1880	GO:0015935	small ribosomal subunit
ML1889	GO:0003677	DNA binding
ML1889	GO:0006281	DNA repair
ML1889	GO:0008270	zinc ion binding
ML1890	GO:0003677	DNA binding
ML1890	GO:0003899	DNA-directed RNA polymerase activity
ML1890	GO:0006351	transcription, DNA-templated
ML1891	GO:0003677	DNA binding
ML1891	GO:0003899	DNA-directed RNA polymerase activity
ML1891	GO:0006351	transcription, DNA-templated
ML1892	GO:0005524	ATP binding
ML1892	GO:0016887	ATPase activity
ML1895	GO:0003735	structural constituent of ribosome
ML1895	GO:0005622	intracellular
ML1895	GO:0005840	ribosome
ML1895	GO:0006412	translation
ML1896	GO:0003735	structural constituent of ribosome
ML1896	GO:0005622	intracellular
ML1896	GO:0005840	ribosome
ML1896	GO:0006412	translation
ML1896	GO:0042254	ribosome biogenesis
ML1900	GO:0008610	lipid biosynthetic process
ML1903	GO:0008610	lipid biosynthetic process
ML1904	GO:0003723	RNA binding
ML1904	GO:0003735	structural constituent of ribosome
ML1904	GO:0006412	translation
ML1904	GO:0015934	large ribosomal subunit
ML1905	GO:0003735	structural constituent of ribosome
ML1905	GO:0005840	ribosome
ML1905	GO:0006412	translation
ML1906	GO:0006355	regulation of transcription, DNA-templated
ML1906	GO:0032784	regulation of DNA-templated transcription, elongation
ML1907	GO:0006605	protein targeting
ML1907	GO:0006886	intracellular protein transport
ML1907	GO:0009306	protein secretion
ML1907	GO:0015450	P-P-bond-hydrolysis-driven protein transmembrane transporter activity
ML1907	GO:0016020	membrane
ML1907	GO:0016021	integral component of membrane
ML1911	GO:0003735	structural constituent of ribosome
ML1911	GO:0005622	intracellular
ML1911	GO:0005840	ribosome
ML1911	GO:0006412	translation
ML1919	GO:0004089	carbonate dehydratase activity
ML1919	GO:0008270	zinc ion binding
ML1919	GO:0015976	carbon utilization
ML1920	GO:0003824	catalytic activity
ML1920	GO:0006281	DNA repair
ML1920	GO:0006284	base-excision repair
ML1920	GO:0051539	4 iron, 4 sulfur cluster binding
ML1925	GO:0004784	superoxide dismutase activity
ML1925	GO:0006801	superoxide metabolic process
ML1925	GO:0046872	metal ion binding
ML1925	GO:0055114	oxidation-reduction process
ML1936	GO:0005525	GTP binding
ML1938	GO:0019288	isopentenyl diphosphate biosynthetic process, methylerythritol 4-phosphate pathway
ML1938	GO:0046872	metal ion binding
ML1938	GO:0050992	dimethylallyl diphosphate biosynthetic process
ML1938	GO:0051745	4-hydroxy-3-methylbut-2-en-1-yl diphosphate reductase activity
ML1940	GO:0003676	nucleic acid binding
ML1940	GO:0006308	DNA catabolic process
ML1940	GO:0008855	exodeoxyribonuclease VII activity
ML1940	GO:0009318	exodeoxyribonuclease VII complex
ML1941	GO:0006308	DNA catabolic process
ML1941	GO:0008855	exodeoxyribonuclease VII activity
ML1941	GO:0009318	exodeoxyribonuclease VII complex
ML1942	GO:0003854	3-beta-hydroxy-delta5-steroid dehydrogenase activity
ML1942	GO:0006694	steroid biosynthetic process
ML1942	GO:0016616	oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
ML1942	GO:0055114	oxidation-reduction process
ML1946	GO:0006071	glycerol metabolic process
ML1946	GO:0006094	gluconeogenesis
ML1946	GO:0042132	fructose 1,6-bisphosphate 1-phosphatase activity
ML1947	GO:0003824	catalytic activity
ML1947	GO:0004333	fumarate hydratase activity
ML1947	GO:0006099	tricarboxylic acid cycle
ML1947	GO:0006106	fumarate metabolic process
ML1947	GO:0016829	lyase activity
ML1947	GO:0045239	tricarboxylic acid cycle enzyme complex
ML1950	GO:0003824	catalytic activity
ML1950	GO:0005975	carbohydrate metabolic process
ML1950	GO:0016810	hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds
ML1951	GO:0005524	ATP binding
ML1952	GO:0006631	fatty acid metabolic process
ML1952	GO:0016491	oxidoreductase activity
ML1952	GO:0045300	acyl-[acyl-carrier-protein] desaturase activity
ML1952	GO:0055114	oxidation-reduction process
ML1953	GO:0003824	catalytic activity
ML1953	GO:0004372	glycine hydroxymethyltransferase activity
ML1953	GO:0006544	glycine metabolic process
ML1953	GO:0006563	L-serine metabolic process
ML1953	GO:0016740	transferase activity
ML1953	GO:0030170	pyridoxal phosphate binding
ML1954	GO:0004594	pantothenate kinase activity
ML1954	GO:0005524	ATP binding
ML1954	GO:0005737	cytoplasm
ML1954	GO:0008152	metabolic process
ML1954	GO:0015937	coenzyme A biosynthetic process
ML1954	GO:0016301	kinase activity
ML1955	GO:0001522	pseudouridine synthesis
ML1955	GO:0003723	RNA binding
ML1955	GO:0009451	RNA modification
ML1955	GO:0009982	pseudouridine synthase activity
ML1956	GO:0003735	structural constituent of ribosome
ML1956	GO:0005622	intracellular
ML1956	GO:0005840	ribosome
ML1956	GO:0006412	translation
ML1957	GO:0003677	DNA binding
ML1957	GO:0003899	DNA-directed RNA polymerase activity
ML1957	GO:0006351	transcription, DNA-templated
ML1957	GO:0046983	protein dimerization activity
ML1958	GO:0003723	RNA binding
ML1958	GO:0003735	structural constituent of ribosome
ML1958	GO:0005622	intracellular
ML1958	GO:0006412	translation
ML1958	GO:0015935	small ribosomal subunit
ML1958	GO:0019843	rRNA binding
ML1959	GO:0003735	structural constituent of ribosome
ML1959	GO:0005622	intracellular
ML1959	GO:0005840	ribosome
ML1959	GO:0006412	translation
ML1960	GO:0003676	nucleic acid binding
ML1960	GO:0003723	RNA binding
ML1960	GO:0003735	structural constituent of ribosome
ML1960	GO:0005622	intracellular
ML1960	GO:0005840	ribosome
ML1960	GO:0006412	translation
ML1961	GO:0003735	structural constituent of ribosome
ML1961	GO:0005622	intracellular
ML1961	GO:0005840	ribosome
ML1961	GO:0006412	translation
ML1962	GO:0003723	RNA binding
ML1962	GO:0003743	translation initiation factor activity
ML1962	GO:0006413	translational initiation
ML1964	GO:0008460	dTDP-glucose 4,6-dehydratase activity
ML1964	GO:0009225	nucleotide-sugar metabolic process
ML1965	GO:0008830	dTDP-4-dehydrorhamnose 3,5-epimerase activity
ML1966	GO:0016020	membrane
ML1974	GO:0003333	amino acid transmembrane transport
ML1974	GO:0015171	amino acid transmembrane transporter activity
ML1974	GO:0016020	membrane
ML1985	GO:0003824	catalytic activity
ML1985	GO:0004451	isocitrate lyase activity
ML1985	GO:0008152	metabolic process
ML1985	GO:0019752	carboxylic acid metabolic process
ML1987	GO:0000166	nucleotide binding
ML1987	GO:0006812	cation transport
ML1987	GO:0016021	integral component of membrane
ML1987	GO:0019829	cation-transporting ATPase activity
ML1987	GO:0046872	metal ion binding
ML1992	GO:0016491	oxidoreductase activity
ML1992	GO:0055114	oxidation-reduction process
ML1994	GO:0003824	catalytic activity
ML1994	GO:0008152	metabolic process
ML1996	GO:0003824	catalytic activity
ML1996	GO:0008152	metabolic process
ML1998	GO:0016021	integral component of membrane
ML1999	GO:0003824	catalytic activity
ML2000	GO:0000166	nucleotide binding
ML2000	GO:0006812	cation transport
ML2000	GO:0016021	integral component of membrane
ML2000	GO:0019829	cation-transporting ATPase activity
ML2000	GO:0030001	metal ion transport
ML2000	GO:0046872	metal ion binding
ML2011	GO:0003884	D-amino-acid oxidase activity
ML2011	GO:0016491	oxidoreductase activity
ML2011	GO:0046416	D-amino acid metabolic process
ML2011	GO:0055114	oxidation-reduction process
ML2011	GO:0071949	FAD binding
ML2020	GO:0008168	methyltransferase activity
ML2020	GO:0032259	methylation
ML2025	GO:0055114	oxidation-reduction process
ML2038	GO:0006826	iron ion transport
ML2038	GO:0006879	cellular iron ion homeostasis
ML2038	GO:0008199	ferric iron binding
ML2041	GO:0003700	sequence-specific DNA binding transcription factor activity
ML2041	GO:0006355	regulation of transcription, DNA-templated
ML2042	GO:0016209	antioxidant activity
ML2042	GO:0016491	oxidoreductase activity
ML2042	GO:0055114	oxidation-reduction process
ML2045	GO:0003824	catalytic activity
ML2045	GO:0005975	carbohydrate metabolic process
ML2046	GO:0003824	catalytic activity
ML2046	GO:0010181	FMN binding
ML2046	GO:0016491	oxidoreductase activity
ML2046	GO:0055114	oxidation-reduction process
ML2048	GO:0016491	oxidoreductase activity
ML2048	GO:0055114	oxidation-reduction process
ML2053	GO:0008270	zinc ion binding
ML2053	GO:0016491	oxidoreductase activity
ML2053	GO:0055114	oxidation-reduction process
ML2054	GO:0016021	integral component of membrane
ML2055	GO:0005576	extracellular region
ML2055	GO:0050840	extracellular matrix binding
ML2061	GO:0016491	oxidoreductase activity
ML2061	GO:0055114	oxidation-reduction process
ML2063	GO:0003677	DNA binding
ML2063	GO:0045892	negative regulation of transcription, DNA-templated
ML2064	GO:0004222	metalloendopeptidase activity
ML2064	GO:0006508	proteolysis
ML2065	GO:0004616	phosphogluconate dehydrogenase (decarboxylating) activity
ML2065	GO:0006098	pentose-phosphate shunt
ML2065	GO:0016491	oxidoreductase activity
ML2065	GO:0055114	oxidation-reduction process
ML2066	GO:0003824	catalytic activity
ML2066	GO:0003938	IMP dehydrogenase activity
ML2066	GO:0006164	purine nucleotide biosynthetic process
ML2066	GO:0055114	oxidation-reduction process
ML2069	GO:0003824	catalytic activity
ML2069	GO:0004474	malate synthase activity
ML2069	GO:0006097	glyoxylate cycle
ML2072	GO:0003824	catalytic activity
ML2072	GO:0004375	glycine dehydrogenase (decarboxylating) activity
ML2072	GO:0006544	glycine metabolic process
ML2072	GO:0006546	glycine catabolic process
ML2072	GO:0055114	oxidation-reduction process
ML2073	GO:0003677	DNA binding
ML2073	GO:0006355	regulation of transcription, DNA-templated
ML2074	GO:0004518	nuclease activity
ML2075	GO:0003677	DNA binding
ML2075	GO:0006355	regulation of transcription, DNA-templated
ML2076	GO:0005515	protein binding
ML2077	GO:0005960	glycine cleavage complex
ML2077	GO:0019464	glycine decarboxylation via glycine cleavage system
ML2081	GO:0008444	CDP-diacylglycerol-glycerol-3-phosphate 3-phosphatidyltransferase activity
ML2081	GO:0008654	phospholipid biosynthetic process
ML2081	GO:0016020	membrane
ML2081	GO:0016021	integral component of membrane
ML2081	GO:0016780	phosphotransferase activity, for other substituted phosphate groups
ML2082	GO:0005524	ATP binding
ML2082	GO:0006605	protein targeting
ML2082	GO:0006886	intracellular protein transport
ML2082	GO:0016020	membrane
ML2082	GO:0017038	protein import
ML2083	GO:0000287	magnesium ion binding
ML2083	GO:0003824	catalytic activity
ML2083	GO:0030976	thiamine pyrophosphate binding
ML2084	GO:0005524	ATP binding
ML2084	GO:0006810	transport
ML2084	GO:0016021	integral component of membrane
ML2084	GO:0016887	ATPase activity
ML2084	GO:0042626	ATPase activity, coupled to transmembrane movement of substances
ML2084	GO:0055085	transmembrane transport
ML2088	GO:0005506	iron ion binding
ML2088	GO:0016705	oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
ML2088	GO:0020037	heme binding
ML2088	GO:0055114	oxidation-reduction process
ML2093	GO:0005315	inorganic phosphate transmembrane transporter activity
ML2093	GO:0005887	integral component of plasma membrane
ML2093	GO:0006810	transport
ML2093	GO:0016020	membrane
ML2093	GO:0035435	phosphate ion transmembrane transport
ML2094	GO:0005315	inorganic phosphate transmembrane transporter activity
ML2094	GO:0006810	transport
ML2094	GO:0006817	phosphate ion transport
ML2094	GO:0016020	membrane
ML2094	GO:0016021	integral component of membrane
ML2095	GO:0035435	phosphate ion transmembrane transport
ML2095	GO:0042301	phosphate ion binding
ML2095	GO:0043190	ATP-binding cassette (ABC) transporter complex
ML2098	GO:0005215	transporter activity
ML2098	GO:0006810	transport
ML2098	GO:0016020	membrane
ML2118	GO:0003824	catalytic activity
ML2118	GO:0008152	metabolic process
ML2123	GO:0000160	phosphorelay signal transduction system
ML2123	GO:0003677	DNA binding
ML2123	GO:0006355	regulation of transcription, DNA-templated
ML2124	GO:0000155	phosphorelay sensor kinase activity
ML2124	GO:0004871	signal transducer activity
ML2124	GO:0007165	signal transduction
ML2124	GO:0016021	integral component of membrane
ML2124	GO:0016310	phosphorylation
ML2124	GO:0016772	transferase activity, transferring phosphorus-containing groups
ML2130	GO:0004108	citrate (Si)-synthase activity
ML2130	GO:0005737	cytoplasm
ML2130	GO:0006099	tricarboxylic acid cycle
ML2130	GO:0046912	transferase activity, transferring acyl groups, acyl groups converted into alkyl on transfer
ML2131	GO:0004733	pyridoxamine-phosphate oxidase activity
ML2131	GO:0008615	pyridoxine biosynthetic process
ML2131	GO:0010181	FMN binding
ML2131	GO:0016491	oxidoreductase activity
ML2131	GO:0016638	oxidoreductase activity, acting on the CH-NH2 group of donors
ML2131	GO:0055114	oxidation-reduction process
ML2134	GO:0016491	oxidoreductase activity
ML2134	GO:0055114	oxidation-reduction process
ML2136	GO:0003824	catalytic activity
ML2136	GO:0004648	O-phospho-L-serine:2-oxoglutarate aminotransferase activity
ML2136	GO:0006564	L-serine biosynthetic process
ML2136	GO:0009058	biosynthetic process
ML2140	GO:0003700	sequence-specific DNA binding transcription factor activity
ML2140	GO:0006355	regulation of transcription, DNA-templated
ML2143	GO:0016021	integral component of membrane
ML2143	GO:0055085	transmembrane transport
ML2147	GO:0003676	nucleic acid binding
ML2147	GO:0003677	DNA binding
ML2147	GO:0006355	regulation of transcription, DNA-templated
ML2157	GO:0003677	DNA binding
ML2157	GO:0005524	ATP binding
ML2157	GO:0016787	hydrolase activity
ML2161	GO:0003824	catalytic activity
ML2161	GO:0003857	3-hydroxyacyl-CoA dehydrogenase activity
ML2161	GO:0006631	fatty acid metabolic process
ML2161	GO:0008152	metabolic process
ML2161	GO:0016491	oxidoreductase activity
ML2161	GO:0055114	oxidation-reduction process
ML2162	GO:0003824	catalytic activity
ML2162	GO:0008152	metabolic process
ML2162	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML2167	GO:0000287	magnesium ion binding
ML2167	GO:0003824	catalytic activity
ML2167	GO:0016831	carboxy-lyase activity
ML2167	GO:0030976	thiamine pyrophosphate binding
ML2173	GO:0016491	oxidoreductase activity
ML2173	GO:0055114	oxidation-reduction process
ML2174	GO:0003824	catalytic activity
ML2174	GO:0004126	cytidine deaminase activity
ML2174	GO:0008270	zinc ion binding
ML2174	GO:0009972	cytidine deamination
ML2174	GO:0016787	hydrolase activity
ML2177	GO:0003824	catalytic activity
ML2177	GO:0004850	uridine phosphorylase activity
ML2177	GO:0005737	cytoplasm
ML2177	GO:0009116	nucleoside metabolic process
ML2177	GO:0009166	nucleotide catabolic process
ML2177	GO:0016763	transferase activity, transferring pentosyl groups
ML2185	GO:0006631	fatty acid metabolic process
ML2185	GO:0016491	oxidoreductase activity
ML2185	GO:0045300	acyl-[acyl-carrier-protein] desaturase activity
ML2185	GO:0055114	oxidation-reduction process
ML2186	GO:0003824	catalytic activity
ML2186	GO:0008033	tRNA processing
ML2186	GO:0016491	oxidoreductase activity
ML2186	GO:0017150	tRNA dihydrouridine synthase activity
ML2186	GO:0050660	flavin adenine dinucleotide binding
ML2186	GO:0055114	oxidation-reduction process
ML2188	GO:0005737	cytoplasm
ML2188	GO:0030643	cellular phosphate ion homeostasis
ML2188	GO:0045936	negative regulation of phosphate metabolic process
ML2189	GO:0005315	inorganic phosphate transmembrane transporter activity
ML2189	GO:0005524	ATP binding
ML2189	GO:0016020	membrane
ML2189	GO:0016887	ATPase activity
ML2189	GO:0035435	phosphate ion transmembrane transport
ML2192	GO:0035435	phosphate ion transmembrane transport
ML2192	GO:0042301	phosphate ion binding
ML2192	GO:0043190	ATP-binding cassette (ABC) transporter complex
ML2193	GO:0008080	N-acetyltransferase activity
ML2193	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML2196	GO:0045454	cell redox homeostasis
ML2198	GO:0004792	thiosulfate sulfurtransferase activity
ML2205	GO:0004641	phosphoribosylformylglycinamidine cyclo-ligase activity
ML2205	GO:0005737	cytoplasm
ML2205	GO:0006189	'de novo' IMP biosynthetic process
ML2206	GO:0004044	amidophosphoribosyltransferase activity
ML2206	GO:0009113	purine nucleobase biosynthetic process
ML2206	GO:0009116	nucleoside metabolic process
ML2209	GO:0016772	transferase activity, transferring phosphorus-containing groups
ML2210	GO:0004115	3',5'-cyclic-AMP phosphodiesterase activity
ML2210	GO:0016787	hydrolase activity
ML2211	GO:0004642	phosphoribosylformylglycinamidine synthase activity
ML2211	GO:0005737	cytoplasm
ML2211	GO:0006189	'de novo' IMP biosynthetic process
ML2213	GO:0004177	aminopeptidase activity
ML2213	GO:0006508	proteolysis
ML2213	GO:0008270	zinc ion binding
ML2219	GO:0004642	phosphoribosylformylglycinamidine synthase activity
ML2219	GO:0005737	cytoplasm
ML2219	GO:0006189	'de novo' IMP biosynthetic process
ML2225	GO:0003677	DNA binding
ML2226	GO:0004252	serine-type endopeptidase activity
ML2226	GO:0006508	proteolysis
ML2226	GO:0008236	serine-type peptidase activity
ML2226	GO:0070008	serine-type exopeptidase activity
ML2227	GO:0004639	phosphoribosylaminoimidazolesuccinocarboxamide synthase activity
ML2227	GO:0005524	ATP binding
ML2227	GO:0006164	purine nucleotide biosynthetic process
ML2230	GO:0003824	catalytic activity
ML2230	GO:0004018	N6-(1,2-dicarboxyethyl)AMP AMP-lyase (fumarate-forming) activity
ML2230	GO:0009152	purine ribonucleotide biosynthetic process
ML2235	GO:0003824	catalytic activity
ML2235	GO:0004637	phosphoribosylamine-glycine ligase activity
ML2235	GO:0005524	ATP binding
ML2235	GO:0009113	purine nucleobase biosynthetic process
ML2237	GO:0003824	catalytic activity
ML2254	GO:0003824	catalytic activity
ML2254	GO:0005992	trehalose biosynthetic process
ML2257	GO:0003824	catalytic activity
ML2257	GO:0008152	metabolic process
ML2260	GO:0005315	inorganic phosphate transmembrane transporter activity
ML2260	GO:0006817	phosphate ion transport
ML2260	GO:0016020	membrane
ML2263	GO:0003824	catalytic activity
ML2263	GO:0008152	metabolic process
ML2263	GO:0008935	1,4-dihydroxy-2-naphthoyl-CoA synthase activity
ML2263	GO:0009234	menaquinone biosynthetic process
ML2268	GO:0000287	magnesium ion binding
ML2268	GO:0009234	menaquinone biosynthetic process
ML2268	GO:0016836	hydro-lyase activity
ML2269	GO:0003824	catalytic activity
ML2270	GO:0009234	menaquinone biosynthetic process
ML2270	GO:0030976	thiamine pyrophosphate binding
ML2270	GO:0070204	2-succinyl-5-enolpyruvyl-6-hydroxy-3-cyclohexene-1-carboxylic-acid synthase activity
ML2273	GO:0008168	methyltransferase activity
ML2276	GO:0016491	oxidoreductase activity
ML2276	GO:0016628	oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor
ML2276	GO:0055114	oxidation-reduction process
ML2276	GO:0071949	FAD binding
ML2277	GO:0008299	isoprenoid biosynthetic process
ML2278	GO:0004222	metalloendopeptidase activity
ML2278	GO:0006508	proteolysis
ML2279	GO:0008272	sulfate transport
ML2279	GO:0015116	sulfate transmembrane transporter activity
ML2279	GO:0016021	integral component of membrane
ML2297	GO:0003824	catalytic activity
ML2298	GO:0004252	serine-type endopeptidase activity
ML2298	GO:0006508	proteolysis
ML2298	GO:0009403	toxin biosynthetic process
ML2298	GO:0016020	membrane
ML2299	GO:0000287	magnesium ion binding
ML2299	GO:0009132	nucleoside diphosphate metabolic process
ML2299	GO:0016787	hydrolase activity
ML2299	GO:0016818	hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides
ML2299	GO:0030145	manganese ion binding
ML2300	GO:0016491	oxidoreductase activity
ML2300	GO:0045454	cell redox homeostasis
ML2301	GO:0003824	catalytic activity
ML2301	GO:0003906	DNA-(apurinic or apyrimidinic site) lyase activity
ML2301	GO:0006281	DNA repair
ML2301	GO:0006284	base-excision repair
ML2301	GO:0051539	4 iron, 4 sulfur cluster binding
ML2302	GO:0003677	DNA binding
ML2302	GO:0006355	regulation of transcription, DNA-templated
ML2308	GO:0008658	penicillin binding
ML2314	GO:0004370	glycerol kinase activity
ML2314	GO:0005975	carbohydrate metabolic process
ML2314	GO:0006072	glycerol-3-phosphate metabolic process
ML2314	GO:0016773	phosphotransferase activity, alcohol group as acceptor
ML2322	GO:0003942	N-acetyl-gamma-glutamyl-phosphate reductase activity
ML2322	GO:0004073	aspartate-semialdehyde dehydrogenase activity
ML2322	GO:0005737	cytoplasm
ML2322	GO:0006520	cellular amino acid metabolic process
ML2322	GO:0008652	cellular amino acid biosynthetic process
ML2322	GO:0009086	methionine biosynthetic process
ML2322	GO:0009088	threonine biosynthetic process
ML2322	GO:0009089	lysine biosynthetic process via diaminopimelate
ML2322	GO:0009097	isoleucine biosynthetic process
ML2322	GO:0016620	oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
ML2322	GO:0046983	protein dimerization activity
ML2322	GO:0050661	NADP binding
ML2322	GO:0051287	NAD binding
ML2322	GO:0055114	oxidation-reduction process
ML2323	GO:0004072	aspartate kinase activity
ML2323	GO:0008152	metabolic process
ML2323	GO:0008652	cellular amino acid biosynthetic process
ML2323	GO:0009089	lysine biosynthetic process via diaminopimelate
ML2323	GO:0016597	amino acid binding
ML2324	GO:0003824	catalytic activity
ML2324	GO:0003852	2-isopropylmalate synthase activity
ML2324	GO:0009098	leucine biosynthetic process
ML2324	GO:0019752	carboxylic acid metabolic process
ML2324	GO:0046912	transferase activity, transferring acyl groups, acyl groups converted into alkyl on transfer
ML2326	GO:0005524	ATP binding
ML2326	GO:0009058	biosynthetic process
ML2327	GO:0003824	catalytic activity
ML2327	GO:0009236	cobalamin biosynthetic process
ML2329	GO:0003677	DNA binding
ML2329	GO:0006281	DNA repair
ML2329	GO:0006310	DNA recombination
ML2331	GO:0008745	N-acetylmuramoyl-L-alanine amidase activity
ML2331	GO:0009253	peptidoglycan catabolic process
ML2333	GO:0003824	catalytic activity
ML2333	GO:0016491	oxidoreductase activity
ML2333	GO:0016614	oxidoreductase activity, acting on CH-OH group of donors
ML2333	GO:0050660	flavin adenine dinucleotide binding
ML2333	GO:0055114	oxidation-reduction process
ML2334	GO:0008610	lipid biosynthetic process
ML2335	GO:0003677	DNA binding
ML2335	GO:0003887	DNA-directed DNA polymerase activity
ML2335	GO:0005524	ATP binding
ML2335	GO:0006260	DNA replication
ML2335	GO:0009360	DNA polymerase III complex
ML2336	GO:0003824	catalytic activity
ML2341	GO:0009190	cyclic nucleotide biosynthetic process
ML2341	GO:0016849	phosphorus-oxygen lyase activity
ML2341	GO:0035556	intracellular signal transduction
ML2343	GO:0006520	cellular amino acid metabolic process
ML2348	GO:0005975	carbohydrate metabolic process
ML2348	GO:0008152	metabolic process
ML2348	GO:0016758	transferase activity, transferring hexosyl groups
ML2348	GO:0030259	lipid glycosylation
ML2350	GO:0006810	transport
ML2350	GO:0016020	membrane
ML2350	GO:0042891	antibiotic transport
ML2350	GO:0043215	daunorubicin transport
ML2350	GO:0046677	response to antibiotic
ML2350	GO:1900753	doxorubicin transport
ML2351	GO:0006810	transport
ML2351	GO:0016020	membrane
ML2351	GO:0042891	antibiotic transport
ML2351	GO:0043215	daunorubicin transport
ML2351	GO:0046677	response to antibiotic
ML2351	GO:1900753	doxorubicin transport
ML2352	GO:0005524	ATP binding
ML2352	GO:0016887	ATPase activity
ML2352	GO:0043215	daunorubicin transport
ML2352	GO:1900753	doxorubicin transport
ML2353	GO:0003824	catalytic activity
ML2353	GO:0008152	metabolic process
ML2353	GO:0016740	transferase activity
ML2353	GO:0031177	phosphopantetheine binding
ML2354	GO:0003824	catalytic activity
ML2354	GO:0008152	metabolic process
ML2354	GO:0016740	transferase activity
ML2354	GO:0031177	phosphopantetheine binding
ML2355	GO:0003824	catalytic activity
ML2355	GO:0008152	metabolic process
ML2355	GO:0016491	oxidoreductase activity
ML2355	GO:0016740	transferase activity
ML2355	GO:0031177	phosphopantetheine binding
ML2355	GO:0055114	oxidation-reduction process
ML2356	GO:0003824	catalytic activity
ML2356	GO:0008152	metabolic process
ML2356	GO:0016740	transferase activity
ML2356	GO:0031177	phosphopantetheine binding
ML2357	GO:0003824	catalytic activity
ML2357	GO:0008152	metabolic process
ML2357	GO:0016740	transferase activity
ML2357	GO:0031177	phosphopantetheine binding
ML2358	GO:0003824	catalytic activity
ML2358	GO:0008152	metabolic process
ML2359	GO:0009058	biosynthetic process
ML2359	GO:0016788	hydrolase activity, acting on ester bonds
ML2366	GO:0005887	integral component of plasma membrane
ML2378	GO:0016020	membrane
ML2378	GO:0016021	integral component of membrane
ML2387	GO:0004148	dihydrolipoyl dehydrogenase activity
ML2387	GO:0016491	oxidoreductase activity
ML2387	GO:0016668	oxidoreductase activity, acting on a sulfur group of donors, NAD(P) as acceptor
ML2387	GO:0045454	cell redox homeostasis
ML2387	GO:0050660	flavin adenine dinucleotide binding
ML2387	GO:0055114	oxidation-reduction process
ML2391	GO:0010126	mycothiol metabolic process
ML2393	GO:0003677	DNA binding
ML2393	GO:0032784	regulation of DNA-templated transcription, elongation
ML2393	GO:0070063	RNA polymerase binding
ML2394	GO:0003824	catalytic activity
ML2394	GO:0030170	pyridoxal phosphate binding
ML2396	GO:0004122	cystathionine beta-synthase activity
ML2396	GO:0005737	cytoplasm
ML2396	GO:0019343	cysteine biosynthetic process via cystathionine
ML2401	GO:0003860	3-hydroxyisobutyryl-CoA hydrolase activity
ML2402	GO:0003824	catalytic activity
ML2402	GO:0008152	metabolic process
ML2406	GO:0004659	prenyltransferase activity
ML2406	GO:0009234	menaquinone biosynthetic process
ML2406	GO:0016021	integral component of membrane
ML2406	GO:0046428	1,4-dihydroxy-2-naphthoate octaprenyltransferase activity
ML2409	GO:0017004	cytochrome complex assembly
ML2409	GO:0020037	heme binding
ML2411	GO:0016020	membrane
ML2411	GO:0017004	cytochrome complex assembly
ML2411	GO:0055114	oxidation-reduction process
ML2412	GO:0016209	antioxidant activity
ML2412	GO:0016491	oxidoreductase activity
ML2412	GO:0045454	cell redox homeostasis
ML2412	GO:0055114	oxidation-reduction process
ML2414	GO:0003824	catalytic activity
ML2414	GO:0008483	transaminase activity
ML2414	GO:0030170	pyridoxal phosphate binding
ML2414	GO:0033014	tetrapyrrole biosynthetic process
ML2414	GO:0042286	glutamate-1-semialdehyde 2,1-aminomutase activity
ML2419	GO:0003824	catalytic activity
ML2419	GO:0004655	porphobilinogen synthase activity
ML2419	GO:0033014	tetrapyrrole biosynthetic process
ML2419	GO:0046872	metal ion binding
ML2420	GO:0004852	uroporphyrinogen-III synthase activity
ML2420	GO:0008152	metabolic process
ML2420	GO:0008168	methyltransferase activity
ML2420	GO:0033014	tetrapyrrole biosynthetic process
ML2421	GO:0004418	hydroxymethylbilane synthase activity
ML2421	GO:0018160	peptidyl-pyrromethane cofactor linkage
ML2421	GO:0033014	tetrapyrrole biosynthetic process
ML2422	GO:0008883	glutamyl-tRNA reductase activity
ML2422	GO:0033014	tetrapyrrole biosynthetic process
ML2422	GO:0050661	NADP binding
ML2422	GO:0055114	oxidation-reduction process
ML2424	GO:0008152	metabolic process
ML2424	GO:0016791	phosphatase activity
ML2426	GO:0008610	lipid biosynthetic process
ML2427	GO:0008152	metabolic process
ML2427	GO:0016746	transferase activity, transferring acyl groups
ML2428	GO:0003824	catalytic activity
ML2428	GO:0050662	coenzyme binding
ML2429	GO:0003677	DNA binding
ML2430	GO:0004735	pyrroline-5-carboxylate reductase activity
ML2430	GO:0006561	proline biosynthetic process
ML2430	GO:0055114	oxidation-reduction process
ML2439	GO:0000160	phosphorelay signal transduction system
ML2439	GO:0003677	DNA binding
ML2439	GO:0006355	regulation of transcription, DNA-templated
ML2440	GO:0000155	phosphorelay sensor kinase activity
ML2440	GO:0007165	signal transduction
ML2440	GO:0016310	phosphorylation
ML2440	GO:0016772	transferase activity, transferring phosphorus-containing groups
ML2441	GO:0003824	catalytic activity
ML2441	GO:0004619	phosphoglycerate mutase activity
ML2441	GO:0006096	glycolytic process
ML2441	GO:0008152	metabolic process
ML2441	GO:0016868	intramolecular transferase activity, phosphotransferases
ML2443	GO:0008375	acetylglucosaminyltransferase activity
ML2443	GO:0010125	mycothiol biosynthetic process
ML2446	GO:0016740	transferase activity
ML2447	GO:0003824	catalytic activity
ML2447	GO:0008762	UDP-N-acetylmuramate dehydrogenase activity
ML2447	GO:0016491	oxidoreductase activity
ML2447	GO:0016614	oxidoreductase activity, acting on CH-OH group of donors
ML2447	GO:0050660	flavin adenine dinucleotide binding
ML2447	GO:0055114	oxidation-reduction process
ML2449	GO:0006807	nitrogen compound metabolic process
ML2449	GO:0016810	hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds
ML2451	GO:0003824	catalytic activity
ML2451	GO:0004139	deoxyribose-phosphate aldolase activity
ML2451	GO:0005737	cytoplasm
ML2451	GO:0009264	deoxyribonucleotide catabolic process
ML2451	GO:0016829	lyase activity
ML2454	GO:0007155	cell adhesion
ML2454	GO:0008201	heparin binding
ML2454	GO:0009405	pathogenesis
ML2454	GO:0009986	cell surface
ML2457	GO:0003677	DNA binding
ML2459	GO:0008610	lipid biosynthetic process
ML2461	GO:0003857	3-hydroxyacyl-CoA dehydrogenase activity
ML2461	GO:0006631	fatty acid metabolic process
ML2461	GO:0016491	oxidoreductase activity
ML2461	GO:0055114	oxidation-reduction process
ML2461	GO:0070403	NAD+ binding
ML2463	GO:0006633	fatty acid biosynthetic process
ML2463	GO:0016790	thiolester hydrolase activity
ML2465	GO:0051920	peroxiredoxin activity
ML2465	GO:0055114	oxidation-reduction process
ML2467	GO:0016765	transferase activity, transferring alkyl or aryl (other than methyl) groups
ML2472	GO:0004665	prephenate dehydrogenase (NADP+) activity
ML2472	GO:0006571	tyrosine biosynthetic process
ML2472	GO:0008977	prephenate dehydrogenase activity
ML2472	GO:0055114	oxidation-reduction process
ML2474	GO:0002100	tRNA wobble adenosine to inosine editing
ML2474	GO:0003824	catalytic activity
ML2474	GO:0008251	tRNA-specific adenosine deaminase activity
ML2474	GO:0008270	zinc ion binding
ML2474	GO:0016787	hydrolase activity
ML2485	GO:0003723	RNA binding
ML2485	GO:0006396	RNA processing
ML2485	GO:0008173	RNA methyltransferase activity
ML2487	GO:0004588	orotate phosphoribosyltransferase activity
ML2487	GO:0006221	pyrimidine nucleotide biosynthetic process
ML2487	GO:0009116	nucleoside metabolic process
ML2490	GO:0005524	ATP binding
ML2490	GO:0005737	cytoplasm
ML2490	GO:0009408	response to heat
ML2490	GO:0016485	protein processing
ML2490	GO:0019538	protein metabolic process
ML2493	GO:0003677	DNA binding
ML2493	GO:0006355	regulation of transcription, DNA-templated
ML2494	GO:0005524	ATP binding
ML2494	GO:0006457	protein folding
ML2494	GO:0009408	response to heat
ML2494	GO:0031072	heat shock protein binding
ML2494	GO:0051082	unfolded protein binding
ML2495	GO:0000774	adenyl-nucleotide exchange factor activity
ML2495	GO:0006457	protein folding
ML2495	GO:0042803	protein homodimerization activity
ML2495	GO:0051087	chaperone binding
ML2496	GO:0005524	ATP binding
ML2496	GO:0006457	protein folding
ML2496	GO:0051082	unfolded protein binding
ML2497	GO:0003677	DNA binding
ML2498	GO:0003824	catalytic activity
ML2498	GO:0008152	metabolic process
ML2501	GO:0051536	iron-sulfur cluster binding
ML2502	GO:0003824	catalytic activity
ML2502	GO:0009058	biosynthetic process
ML2502	GO:0030170	pyridoxal phosphate binding
ML2503	GO:0008879	glucose-1-phosphate thymidylyltransferase activity
ML2503	GO:0009058	biosynthetic process
ML2503	GO:0016779	nucleotidyltransferase activity
ML2503	GO:0045226	extracellular polysaccharide biosynthetic process
ML2507	GO:0006229	dUTP biosynthetic process
ML2507	GO:0008829	dCTP deaminase activity
ML2507	GO:0016787	hydrolase activity
ML2507	GO:0046080	dUTP metabolic process
ML2510	GO:0003824	catalytic activity
ML2510	GO:0008152	metabolic process
ML2528	GO:0004252	serine-type endopeptidase activity
ML2528	GO:0006508	proteolysis
ML2535	GO:0000166	nucleotide binding
ML2535	GO:0003677	DNA binding
ML2535	GO:0005524	ATP binding
ML2537	GO:0005515	protein binding
ML2537	GO:0005524	ATP binding
ML2546	GO:0003824	catalytic activity
ML2546	GO:0008152	metabolic process
ML2561	GO:0010181	FMN binding
ML2561	GO:0016491	oxidoreductase activity
ML2561	GO:0055114	oxidation-reduction process
ML2563	GO:0003995	acyl-CoA dehydrogenase activity
ML2563	GO:0008152	metabolic process
ML2563	GO:0016627	oxidoreductase activity, acting on the CH-CH group of donors
ML2563	GO:0050660	flavin adenine dinucleotide binding
ML2563	GO:0055114	oxidation-reduction process
ML2564	GO:0003824	catalytic activity
ML2564	GO:0008152	metabolic process
ML2564	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML2565	GO:0016491	oxidoreductase activity
ML2566	GO:0004312	fatty acid synthase activity
ML2566	GO:0005835	fatty acid synthase complex
ML2566	GO:0006633	fatty acid biosynthetic process
ML2566	GO:0055114	oxidation-reduction process
ML2568	GO:0003677	DNA binding
ML2569	GO:0004553	hydrolase activity, hydrolyzing O-glycosyl compounds
ML2569	GO:0005975	carbohydrate metabolic process
ML2573	GO:0008152	metabolic process
ML2573	GO:0016491	oxidoreductase activity
ML2573	GO:0016620	oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
ML2573	GO:0055114	oxidation-reduction process
ML2580	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML2584	GO:0008152	metabolic process
ML2584	GO:0008168	methyltransferase activity
ML2587	GO:0006810	transport
ML2587	GO:0043190	ATP-binding cassette (ABC) transporter complex
ML2588	GO:0006810	transport
ML2588	GO:0043190	ATP-binding cassette (ABC) transporter complex
ML2607	GO:0003824	catalytic activity
ML2607	GO:0008152	metabolic process
ML2608	GO:0003824	catalytic activity
ML2608	GO:0004160	dihydroxy-acid dehydratase activity
ML2608	GO:0008152	metabolic process
ML2608	GO:0009082	branched-chain amino acid biosynthetic process
ML2609	GO:0003677	DNA binding
ML2609	GO:0006355	regulation of transcription, DNA-templated
ML2609	GO:0046872	metal ion binding
ML2613	GO:0004222	metalloendopeptidase activity
ML2613	GO:0006508	proteolysis
ML2613	GO:0008237	metallopeptidase activity
ML2616	GO:0003677	DNA binding
ML2617	GO:0016020	membrane
ML2620	GO:0016020	membrane
ML2622	GO:0006400	tRNA modification
ML2622	GO:0008176	tRNA (guanine-N7-)-methyltransferase activity
ML2624	GO:0004611	phosphoenolpyruvate carboxykinase activity
ML2624	GO:0004613	phosphoenolpyruvate carboxykinase (GTP) activity
ML2624	GO:0005525	GTP binding
ML2624	GO:0006094	gluconeogenesis
ML2624	GO:0017076	purine nucleotide binding
ML2631	GO:0003824	catalytic activity
ML2631	GO:0016491	oxidoreductase activity
ML2631	GO:0016614	oxidoreductase activity, acting on CH-OH group of donors
ML2631	GO:0050660	flavin adenine dinucleotide binding
ML2631	GO:0055114	oxidation-reduction process
ML2634	GO:0008750	NAD(P)+ transhydrogenase (AB-specific) activity
ML2634	GO:0016021	integral component of membrane
ML2634	GO:0050661	NADP binding
ML2634	GO:0055114	oxidation-reduction process
ML2636	GO:0016491	oxidoreductase activity
ML2636	GO:0055114	oxidation-reduction process
ML2639	GO:0004030	aldehyde dehydrogenase [NAD(P)+] activity
ML2639	GO:0006081	cellular aldehyde metabolic process
ML2639	GO:0008152	metabolic process
ML2639	GO:0016491	oxidoreductase activity
ML2639	GO:0016620	oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
ML2639	GO:0055114	oxidation-reduction process
ML2640	GO:0008168	methyltransferase activity
ML2640	GO:0032259	methylation
ML2647	GO:0008113	peptide-methionine (S)-S-oxide reductase activity
ML2647	GO:0055114	oxidation-reduction process
ML2649	GO:0003824	catalytic activity
ML2649	GO:0005975	carbohydrate metabolic process
ML2649	GO:0016810	hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds
ML2659	GO:0004252	serine-type endopeptidase activity
ML2659	GO:0005515	protein binding
ML2659	GO:0006508	proteolysis
ML2661	GO:0003824	catalytic activity
ML2661	GO:0008152	metabolic process
ML2663	GO:0003700	sequence-specific DNA binding transcription factor activity
ML2663	GO:0006355	regulation of transcription, DNA-templated
ML2664	GO:0016740	transferase activity
ML2667	GO:0005215	transporter activity
ML2667	GO:0006810	transport
ML2667	GO:0016020	membrane
ML2670	GO:0016747	transferase activity, transferring acyl groups other than amino-acyl groups
ML2671	GO:0000166	nucleotide binding
ML2671	GO:0016021	integral component of membrane
ML2671	GO:0046872	metal ion binding
ML2672	GO:0004450	isocitrate dehydrogenase (NADP+) activity
ML2672	GO:0006099	tricarboxylic acid cycle
ML2672	GO:0016616	oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
ML2672	GO:0055114	oxidation-reduction process
ML2677	GO:0003677	DNA binding
ML2680	GO:0003677	DNA binding
ML2680	GO:0003678	DNA helicase activity
ML2680	GO:0005524	ATP binding
ML2680	GO:0006260	DNA replication
ML2682	GO:0003735	structural constituent of ribosome
ML2682	GO:0005622	intracellular
ML2682	GO:0005840	ribosome
ML2682	GO:0006412	translation
ML2683	GO:0003735	structural constituent of ribosome
ML2683	GO:0005622	intracellular
ML2683	GO:0005840	ribosome
ML2683	GO:0006412	translation
ML2684	GO:0003697	single-stranded DNA binding
ML2684	GO:0006260	DNA replication
ML2685	GO:0003735	structural constituent of ribosome
ML2685	GO:0005840	ribosome
ML2685	GO:0006412	translation
ML2685	GO:0019843	rRNA binding
ML2687	GO:0016758	transferase activity, transferring hexosyl groups
ML2688	GO:0008658	penicillin binding
ML2692	GO:0004512	inositol-3-phosphate synthase activity
ML2692	GO:0006021	inositol biosynthetic process
ML2692	GO:0008654	phospholipid biosynthetic process
ML2696	GO:0003700	sequence-specific DNA binding transcription factor activity
ML2696	GO:0006355	regulation of transcription, DNA-templated
ML2697	GO:0003723	RNA binding
ML2697	GO:0006396	RNA processing
ML2697	GO:0016779	nucleotidyltransferase activity
ML2698	GO:0016787	hydrolase activity
ML2703	GO:0004791	thioredoxin-disulfide reductase activity
ML2703	GO:0005737	cytoplasm
ML2703	GO:0006662	glycerol ether metabolic process
ML2703	GO:0015035	protein disulfide oxidoreductase activity
ML2703	GO:0016491	oxidoreductase activity
ML2703	GO:0019430	removal of superoxide radicals
ML2703	GO:0045454	cell redox homeostasis
ML2703	GO:0055114	oxidation-reduction process
ML2704	GO:0008745	N-acetylmuramoyl-L-alanine amidase activity
ML2704	GO:0009253	peptidoglycan catabolic process
ML2706	GO:0003677	DNA binding
ML2708	GO:0005737	cytoplasm
ML2708	GO:0006364	rRNA processing
ML2708	GO:0008649	rRNA methyltransferase activity
ML2709	GO:0003676	nucleic acid binding
ML2710	GO:0016021	integral component of membrane
ML2710	GO:0051205	protein insertion into membrane
ML2712	GO:0000049	tRNA binding
ML2712	GO:0004526	ribonuclease P activity
ML2712	GO:0008033	tRNA processing
ML2713	GO:0003735	structural constituent of ribosome
ML2713	GO:0005622	intracellular
ML2713	GO:0005840	ribosome
ML2713	GO:0006412	translation
