name: Build and Push Docker Image

# when to run the workflow
on:
  push:
    branches: [master]

# the jobs to run
jobs:
  build:
    # the os to run the job on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # build the image now
      - name: Build Docker image

        run: |
          docker build -t evidente:latest .

      - name: save images
        run: |
          docker save evidente:latest | gzip > image_evidente.tar.gz

      - name: Release WebImage to Repo
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: image_evidente.tar.gz
          asset_name: Evidente
          tag: ${{ github.ref }}
          overwrite: true
          body: "The image for the web app of Evidente"
